### ISSUE TITLE
SMS not showing after restore

### ISSUE THREAD

**Issue by Guillaume350** [jberkel/sms-backup-plus#1004]
Hi everyone,
I have an issue with restoring my SMS, I had to do a factory reset on my phone because of major issues, after a successful restore according to the app (almost 4000 SMS were saved), none of them show up in my SMS app. Any help appreciated.
Regards

* Android version : 7.1.2
* Phone model / brand : Fairphone 2
* SMS Backup+ version installed: 1.5.11
* Messaging app: Default SMS android app (5.2.062 Pegasus_RC17_xxhdpi.armeabi-v7a.phone)

**Comment by kurahaupo** [comment]
Can you confirm that you've sighted the SMSes in your GMail?
Are they still tagged with "SMS" (or with the label configured into SMS Backup+, if you've changed if)?

**Comment by Cinnagar** [comment]
I had the same issue this morning.  I am also using Pegasus_RC17, but the v8a version, and I was able to fix this to get the messages to show up.

1. I started by going into the Messages app, going to **Settings > Chat Features**, and turning off the **"Enable chat features"** (I think this is the new RCS feature that I enabled when setting up my new phone, and might be what is causing this issue).
2. After that, I went into **Android Settings** and then the **App settings**.  I found the **Messages app** in app settings, and I **Force Closed** the app, then went to storage to **Clear Cache** and then **Clear Data**.
3. Finally, I did a **Reboot** for good measure, and after the reboot, I opened the Messages app, where the app reinitialized and all the messages that I restored started populating the app.

**Comment by Guillaume350** [comment]
> I had the same issue this morning. I am also using Pegasus_RC17, but the v8a version, and I was able to fix this to get the messages to show up.
> 
> 1. I started by going into the Messages app, going to **Settings > Chat Features**, and turning off the **"Enable chat features"** (I think this is the new RCS feature that I enabled when setting up my new phone, and might be what is causing this issue).
> 2. After that, I went into **Android Settings** and then the **App settings**.  I found the **Messages app** in app settings, and I **Force Closed** the app, then went to storage to **Clear Cache** and then **Clear Data**.
> 3. Finally, I did a **Reboot** for good measure, and after the reboot, I opened the Messages app, where the app reinitialized and all the messages that I restored started populating the app.

Thanks !, you solved it, I followed your way except step #1 which doesn't apply to my phone (not compatible).
All my SMS are back (tagged as "SMS " to answer the first reply)
