### ISSUE TITLE
Many years of SMS missing from Restore

### ISSUE THREAD

**Issue by amandablum** [jberkel/sms-backup-plus#1010]
### Expected behaviour
1. Set "restore" to "All messages" in restore settings. 
2. set default messaging to "SMS Backup and Restore"
3. Restore messages
4. Confirm all messages have been restored (it will say 96,111 restored, 96,111 dups)
5. Set default messaging back to Android
6. Go to messages, and 2015-2020 sms will be missing.  

### Actual behaviour
1. Most recent messages (5 days) and messages from 2015-2011 are restored. Everything from 2015-2020 is not restore. 

### Steps to reproduce the behaviour
See above. 

### Please specify the following:

Pixel 4, running most recent Android update
SMS Backup + version. 1.5.11
default messaging app

**Comment by kurahaupo** [comment]
@amandablum can you confirm

1. How many messages are _reported_ as restored? Does this match the number expected?
1. Are there any differences in the messages in the 3 periods, such as the "unread" status, or the format used for the `To:` and `From:` headers?
1. Are the messages completely missing, or are they perhaps present but in the wrong conversation?

It seems especially odd to have behaviour switch twice; can you confirm that restoring both new and pre-2015 messages works in the same restoration session?

Can you please attach three examples of raw messages to this [ticket in Github](#1010): one from before 2015 that does restore, one from 2015-2020 that does not restore, and one recent one that does restore? (Please remember to redact any personal data belonging to other people, including all surnames and the last 4 digits from any phone number.)

Also please attach a recent logfile from the app.

**Comment by kurahaupo** [comment]
no response, closing
