### ISSUE TITLE
missing automated backups

### ISSUE THREAD

**Issue by skrosen1** [jberkel/sms-backup-plus#1015]
My SMS Backup+ has worked perfectly without using  2 step authorization, since I made the small IMAP modification you suggested back in July.  I noticed today that the last time it backed up automatically was on March 1st.  The log shows the last backup as successful and does not show any failed attempts after that.  It only shows my manual backups after the last automatic backup.  I am able to back up manually with no problem and have been doing so throughout the day.  What could have suddenly changed?  I am using 1.5.11 version for android 8.0 on my Samsung Galaxy S7.   Using stock Samsung Messaging app.  It is very odd unless a setting accidentally got changed, but I don't see evidence of that.  I'd appreciate any help.

**Comment by skrosen1** [comment]
After posting this I found the solution.  Very simple.  All I had to do was turn off battery optimization on my Samsung Galaxy S7 and all went cack to normal.

**Comment by kurahaupo** [comment]
thanks
