### ISSUE TITLE
problem using Google account authentication

### ISSUE THREAD

**Issue by noskarsubhash** [jberkel/sms-backup-plus#1017]
Unable to Link App with Google Account. Please help me out.

* Android version : 9 (Pie)
* Phone model / brand : Asus Zenfone Max Pro M1
* SMS Backup+ version installed : SmS Backup Plus 1.5.11
* Messaging app : Messages form Google

**Comment by kurahaupo** [comment]
@noskarsubhash do you still need assistance with this issue?

There is an issue with Google declining to grant "sensitive access" to SMS Backup+, leading to it being unable to access Gmail messages by using your Google account credentials. It's not clear from your description whether that is the problem you have encountered, but I'm guessing it's the most likely problem.

If you have not already done so, you will need to generate an application password and use that to sign in using IMAP.

This issue has been written up in many many places, but probably the best summarized instructions are https://github.com/jberkel/sms-backup-plus/issues/959#issuecomment-513018820

If you have already gone through those steps and are still having problems then there is some other issue that we need to resolve.

Please reply and let me know either way.
