### ISSUE TITLE
problem using android 10 

### ISSUE THREAD

**Issue by mbelgrano** [jberkel/sms-backup-plus#1019]
Android 10 
Xiaomi Mi 10
version 1.6.0 beta2
not wordk backup  need username and password
could not get token from system

**Comment by kurahaupo** [comment]
Note that SMSBackup+ cannot use your normal Google sign-in to access your Gmail messages. You need to create an "application password", as explained at https://github.com/jberkel/sms-backup-plus/issues/959#issuecomment-513018820
