### ISSUE TITLE
Custom folder to put SMS/Call log into

### ISSUE THREAD

**Issue by sphh** [jberkel/sms-backup-plus#1020]
I looked through the FAQ and the issues (open and closed) and might have missed it. So I am happy if I am pointed into the right direction.

I tried to set a parent IMAP folder for the `SMS` and `Call log`, but could not find the place where to do it. Is this possible at all? If not, please consider this as a feature request. Thanks.

BTW thanks for your wonderful app!!!

### Please specify the following:

* Android version 8.1.0
* SMS Backup+ version installed 1.5.11
* Messaging app QKSMS

**Comment by kurahaupo** [comment]
You can specify any IMAP path, not just a single level. Gmail seemingly supports both `.` and `/` as separators, but I would stick with the former as it's strongly recommended by RFC-3501.

So you can specify folders as `My Phone.SMS` and `My Phone.Call log`.

**Comment by kurahaupo** [comment]
For example, I use
*  `Phone.SMS.`*`name_of_device`*`
*  `Phone.Calls.`*`name_of_device`*`

I periodically move all the messages from that folder into one that is named for the phone number of the SIM that's currently in that device, as I move them around each time I go roaming. (Strangely enough, I haven't done that for several months.)

I'm hoping to make a change to allow SMS Backup+ to include this automatically.

**Comment by sphh** [comment]
Thanks @kurahaupo! That's what I was hoping for, but I was not sure if it would work and I did not want to risk to loose my text messages. Maybe it's worth to be included into the FAQ?

Your periodically performed tasks would call for placeholders in `SMS Backup+`'s  IMAP path …

**Comment by sphh** [comment]
Well, I feel really stupid: Where in `SMS Backup+` exactly do I set the IMAP folder?

**Comment by kurahaupo** [comment]
- Backup Settings → Gmail label / IMAP folder
- Backup Settings → Call log settings → Call log label

**Comment by sphh** [comment]
YES! It worked. Thanks!

But it is not the obvious place... What you named "Gmail label / IMAP folder" is called "Gmail label assigned to SMS" and "Call log label" "Gmail label assigned to call log". There is absolutely no hint, that this is the IMAP folder where to put the text messages and call logs. I would suggest to rename the settings accordingly, that's why I leave this issue open for now.

**Comment by kurahaupo** [comment]
@sphh  I've raised proposal #1021 that sjpi;should resolve this for future users.
