### ISSUE TITLE
Error: System shows future date in backup

### ISSUE THREAD

**Issue by android987987** [jberkel/sms-backup-plus#1024]
Recent messages not backing up because last backup date shows July 7, 2020 which is in the future (today is June 25, 2020)

* Android version 9
* Samsung Galaxy S8
* SMS Backup+ version installed 1.5.11
* Messaging app standard google messages version 10.1.45.20

![SMS Backup Error 6-25-2020](https://user-images.githubusercontent.com/67428983/85749064-247e5a00-b6ce-11ea-8607-8212cafc1cbc.jpg)

**Comment by kurahaupo** [comment]
Any chance your cellular provider messed up the clock on your device?

**Comment by android987987** [comment]
Hi Martin,
I don't think the carrier is the problem. I haven't had any other issues.

I uninstalled and reinstalled the app.

Same problem persists today. I attached a screenshot I just took. The app
updated the mms & call log today. The sms date is still incorrect.

Thanks for replying!

**Comment by kurahaupo** [comment]
I'm considering the case where the clock in your phone is wrong for a brief period, during which a backup occurs. Unless you're looking at the phone at the time you probably wouldn't notice anything. And yes, phone carriers do screw up their clocks quite often.

Then to avoid overloading the IMAP server, SMS Backup+ does not make another backup until a minimum time after the previous backup - which happens to be 2 weeks in the future.

Restarting or even reinstalling the app won't help so long as that "lasted backed up" time is still recorded.

The problem will resolve itself in 9 days' time, but I will see if I can track down where the last-backed-up date is stored.

**Comment by kurahaupo** [comment]
@android987987 can you confirm that backups have returned to normal operation as the "future" date has now passed?

(I will continue to investigate in case anyone else encounters this problem.)

**Comment by android987987** [comment]
Yes they have. Thank you!

**Comment by haroldong8** [comment]
I have a similar problem. I received an SMS dated for the year 2221, so SMS Backup is stuck until that time. Unlike the first poster, I can't wait this out! Can someone help suggest a resolution?

**Comment by kurahaupo** [comment]
@haroldong8 Some possibilities include:
* setting the system clock of your device to the far future (requires turning off GPS and NTP/network time synch), or
* going "clear data" (or equivalently, uninstalling and reinstalling),
* or using adb to download the database file, modify it, and upload it again. Sadly the latter requires your phone to be in unrestricted developer mode (aka "rooted"), and getting into unrestricted developer mode requires erasure of the whole device.

Fortunately `SMS Backup+` doesn't store messages on your phone, just its settings and its next-time-to-run timestamp, so clearing the app data isn't the end of the world. Just make sure you've written down the settings including the app password first - or you could generate a new app password and revoke the old one.

Reminder: Google's IMAP server is `imap.gmail.com`, not `imap.google.com`.
