### ISSUE TITLE
Won't recognize that messages aren't backed up 

### ISSUE THREAD

**Issue by ardunster** [jberkel/sms-backup-plus#1043]
I got SMS Backup+ working using a custom email address run through my web host, since the Gmail steps quit working and I wasn't willing to use the security settings required these days. 

It has been working great, until.... apparently I had limited space in that email address and hadn't noticed. I fixed the limited space problem, but for the past month it hasn't been receiving my backup attempts.

### Expected behaviour

SMS Backup+ should recognize that the messages are not stored in the email and back them up, if not automatically, at least on a manual backup. 
 
### Actual behaviour

It didn't.  I reset and tried a backup from only the most important contact I wanted to back up, it said it was backing up some 20k messages, but apparently decided they'd all been backed up as it went through them in only a minute or two and no new messages are stored in my email. 

### Steps to reproduce the behaviour

Try to back up messages on a full email account. Make the email account not full. Try again. 

### Please specify the following:

* 5.0.1
* Samsung Galaxy S4 / SCH-I545PP
* SMS Backup+ version installed: 1.5.11
* Messaging app: Verizon Message +

**Comment by kurahaupo** [comment]
Try "clear app data", which will reset the app's idea of what the last-backed-up message was.

(Sometimes this gets out of synch, especially if the clock in your device is wrong.)

**Comment by ardunster** [comment]
Thanks for the suggestion. That phone is unfortunately no longer functional so I won't be able to try it, my new phone is iOS.

**Comment by kurahaupo** [comment]
Thanks for letting us know.
