### ISSUE TITLE
ERROR: " IMAP authorization error. Make sure login and password are set correctly"

### ISSUE THREAD

**Issue by amreggie** [jberkel/sms-backup-plus#1052]
ERROR: " IMAP authorization error. Make sure login and password are set correctly"
Have used this app for years and love it. I just got a new phone (Galaxy 20+). Set it up two days ago and it worked then (last backup), but it has not backed up since that initial run and cannot get it to work again. And yes, IMAP is enabled. Two step auth is set. Generated password (5 times now) Typed it in with no spaces. Tried my email address/ user name both with and without "@gmail.com" Made sure Security is TLS. Like I said, it worked a few days ago on initial run.

Also tried clearing cache and data of app. Uninstalled, reinstalled numerous times.  Reset the app numerous times. Tried battery optimizer turned both on and off. Tried with phone plugged in and not.

Do I need to uninstall it from my old phone (no longer has a SIM card)? Could that be the issue?

Tried this too:

Still having trouble signing in?
If you still can’t sign in to your account on the app, try the following:

On your device’s browser, go to https://accounts.google.com/DisplayUnlockCaptcha.
Enter your username and password, then enter the letters on the screen.
Go back to the app and try signing in again.

Tried the Microsoft Edge method that I read elsewhere. (I get a different error then: "Could not get token from the system -> try browser method..." That leads to "This app is blocked".)

What, for heaven's sake, am missing? Thanks in advance.

### Please specify the following:

* Android version: 10
* Phone model / brand: Samsung Galaxy 20+ 5G
* SMS Backup+ version installed" 1.5.11
* Messaging app: Textra

**Comment by amreggie** [comment]
Update: I uninstalled the app for my previous phone, that seemed to do the trick. I thought I had read it earlier that you could have it on two phones, so I left it on (since it worked on that phone, in case I had to use it as a backup). But since uninstalling, the app on the new phone is working correctly! Hope this helps others.

**Comment by kurahaupo** [comment]
Thanks for the update.
I'm guessing that concurrent IMAP sessions are a problem, unlike concurrent XOAUTH Gmail sessions, so this will be useful for future users.
