### ISSUE TITLE
How to delete messages on Gmail (SMS label) and mirroring the clean on the phone ?

### ISSUE THREAD

**Issue by nonobio** [jberkel/sms-backup-plus#1073]
Hello,

I have a little question:

If I delete messages SMS on my phone and then I restore all messages with SMS Backup+: all is restored, including the deleted message: ok (https://github.com/jberkel/sms-backup-plus/issues/4)

But today I tried to delete messages on my Gmail backup, and then I did a restore: I hoped I would have the "cleaned" version of my messages but the deleted messages are always here on the phone after restoration completed.

I think it is because the SMS phone database hasn't been deleted before the restoration? Am I right?

If yes, should I delete it manually (if possible), before the restoration, or do you have any other recommendations?

What I would like is to clean my message by deleting which I don't want anymore. I found doing the cleaning on Gmail (or Thunderbird), easier, but is it possible?

Thanks :)

### Expected behaviour
Delete messages on Gmail (SMS label) and mirroring the clean on the phone

### Actual behaviour
Delete messages on Gmail (SMS label) are always present on the phone after a SMS Backup+ restoration.

### Steps to reproduce the behaviour
Delete message on Gmail on the SMS label.
Start a restoration on SMS Backup+.

### Please specify the following:

* Android version 10
* Phone model / brand Moto G7 Plus Motorola
* SMS Backup+ version installed 1.6.0-BETA2
* Messaging app Android Messages

**Comment by ajhepple** [comment]
Have you taken into account that when you delete a message in Gmail it isn't actually deleted immediately? Instead, Gmail adds a `Bin` label to the message which has the effect of hiding it from your inbox. Messages retain any other labels, including the `SMS` label. Messages labelled `Bin` are permanently deleted at some later date, determined by your account settings I think. I doubt SMS Backup excludes messages that have the `Bin` label when performing a restore.

**Comment by nonobio** [comment]
Hi,

Thanks for your reply, it's a good tip, but it seems that as I thought, by deleting the SMS database on my phone (done with SMS Backup & Restore: tools), I do not have my deleted SMS displayed anymore :).

Bye
