### ISSUE TITLE
Donations Failing

### ISSUE THREAD

**Issue by pyoungberg** [jberkel/sms-backup-plus#1090]
Before you report your issue, please consider perusing the
[FAQ](https://github.com/jberkel/sms-backup-plus#faq) and searching the issues
page to see if it has already been reported.

### Expected behaviour
Gpay donations go through

### Actual behaviour
Donations get 'unspecified error:3'

### Steps to reproduce the behaviour
Make a donation, any amount

### Please specify the following:

* Android version
13
* Phone model / brand
Pixel 6
* SMS Backup+ version installed
1.6B2
* Messaging app
Stock Android Messenger

**Comment by kurahaupo** [comment]
Jan is no longer working on this project, so he is not taking donations.
I can triage and respond to issues, but I can't push updates to fDroid or PlayStore (See #1059 for details).
