### ISSUE TITLE
[BUG] Google blocks when connecting

### ISSUE THREAD

**Issue by c0fe** [jberkel/sms-backup-plus#1101]
### Expected behaviour

A successful account connection

### Actual behaviour

Receive an error "This app is blocked"

### Reproduce by

Connect account

### Android version

13 (2022)

### Phone brand

Pixel

### Phone model number

7

### SMS Backup+ version

v1.5.11

### Messaging app

Google Messages

**Comment by kurahaupo** [comment]
@c0fe Just checking; have you configured IMAP?

**Comment by c0fe** [comment]
@kurahaupo I fixed it, apparently this app connected to one of my GMail account but not to the other and that threw me off.
