### ISSUE TITLE
Archive Project If Discontinued 

### ISSUE THREAD

**Issue by ThePieMonster** [jberkel/sms-backup-plus#1109]
If this project is discontinued then a link to a replacement should be posted and then archive the project to prevent further confusion.

**Comment by kurahaupo** [comment]
@ThePieMonster I've been bug wrangling for a while, hoping that @jberkel would return, but it's been a few years now.

I've been delegated the ability to wrangle bugs and accept patches here, but I don't have access to the Google Play publisher account, or the F-Droid publisher account, so those have stagnated.

(I'm also completely lost when it comes to fixing the automated build process. I could really do with some help with that.)

**Comment by kurahaupo** [comment]
There's already #1104 "removal from Play Store"; I know this isn't strictly about the same thing, but I'm going to close this as a duplicate because the same action will resolve both, one way or the other.

**Comment by ThePieMonster** [comment]
@kurahaupo I can understand the frustration with the owner being gone. As its been more than a year, I would close everything down entirely. If you want to keep working on it then starting your own repo (and G-Play app) would be the next step. Keeping this up is just causing confusion, and honestly, after a few years the chance is almost zero there will be a return. You can see on projects I have, that I archive them if I know my time is up. That lets other people take over with their own forks. If they reach out I will put a link to their fork in the main readme on my project so others know where to go from there. If you make your own repo, put a link to it in this repo first and then archive. I'm sure the community can come together and help fix what ever is broken. All the best.
