### ISSUE TITLE
Restored call-logs all show as "unknown" (HTC Sense)

### ISSUE THREAD

**Issue by heval-zz** [jberkel/sms-backup-plus#112]
Hi, 
I just used the restore call-log feature of your really awesome app. 
Unfortunately, all the restored call-log entries now show up as "unknown" ("unbekannt" in german), while the number is displayed under "unknown". Even though I know most of those people and also have their numbers stored on my phone (google contacts). 
Would be great if the restored call-log does not only show the number, but also the name of the person I called.

Thanks, and keep up the good work!
Heval

**Comment by eagletracker1** [comment]
I just had this same problem on an HTC One M8.  The way I fixed it was to go into People and then click on the Phonebook drop down on the top left.  It says to show contacts from.........  After a factory reset, only phone is checked so you have to check google contacts.....or messenger, etc.....whatever you use.  Suddenly all the unknowns were changed.
