### ISSUE TITLE
X-smssync-address does not parse correctly when it has utf-8 string in it

### ISSUE THREAD

**Issue by priv** [jberkel/sms-backup-plus#171]
When the contact name has utf-8, for example:
(+886987654321 below is a fake example number I created for example)

X-smssync-address: =?UTF-8?Q?=E6=AD=A3=E8=8A=AC-GSM_=3C+886987654321=3E?=

sms backup+ failed to parse out the number +886987654321
I restore the contact, and in messaging AP it shows the contact as "=?UTF-8?Q?=E6=AD=A3=E8=8A=AC-GSM_=3C+886987654321=3E?="

But when exact same contact(And actually they're in the same dialogues if you view them in gmail), but only has number in X-smssync-address, ie. X-smssync-address: +886 987654321

Sms backup+ restore can correctly file the message to correct contact in my phone.

What's your suggestion that I can prevent this problem?  Will you fix this?  Either you should strip the utf-8 string in X-smssync-address, or you should convert it back to a valid utf-8 string.

**Comment by jberkel** [comment]
hopefully fixed with new K9
