### ISSUE TITLE
setting backup for group causes only my messages backed up

### ISSUE THREAD

**Issue by gideondsouza** [jberkel/sms-backup-plus#172]
simple problem,

I made a contact group and assigned only ONE person(my girlfriend) to this group. 

I then, in advanced settings choose to only backup this group.

When I hit backup, it sent only MY messages to gmail and not my girlfriend? I tried to backup all starred contacts and when I hit backup it says backup already done?

Is it possible to just re backup everything? Or would I have to delete the messages from gmail and reback?

**Comment by backupuser11** [comment]
I have the same problem.  This conversation was closed twice, but never resolved!  No solution given!  Help!!!!!
