### ISSUE TITLE
Error during backup/restore: Temporary Gmail IMAP error, try again later.

### ISSUE THREAD

**Issue by tonya** [jberkel/sms-backup-plus#174]
I get this error all the time whenever I try to backup my messages. I have not fiddled with the IMAP server settings, and IMAP access is enabled in my Gmail account. I managed to backup about 70 out of 500+ SMS a while back over several tries, but it has not worked since. None of my MMS were backed up.

**Comment by adrian-vg** [comment]
This is still a problem. While on wifi I get the error, when not, it seems to work.
Running SMS Backup+ v1.5.10 on a Oneplus One. Had the same problem on my previous Galaxy 2 and 3. Does not seem to be a problem on my Nexus 6P.

**Comment by jberkel** [comment]
@adrian-vg Can you try again with the latest beta?

See https://github.com/jberkel/sms-backup-plus/#beta-testing

**Comment by adrian-vg** [comment]
Hi,

 

Seems to be working.
Thanks!

 

Is it still that token-problem mentioned earlier, or something else?

 

--

//Sorin

**Comment by adrian-vg** [comment]
It’s strange though that only the last four texts are backed up. The other 2000+ texts and almost 200 calls are not.

 

--

//Sorin

 

 

From: Sorin Srbu 
Sent: den 29 mars 2018 10:37
To: 'jberkel/sms-backup-plus' <reply@reply.github.com>
Subject: RE: [jberkel/sms-backup-plus] Error during backup/restore: Temporary Gmail IMAP error, try again later. (#174)

 

Hi,

 

Seems to be working.
Thanks!

 

Is it still that token-problem mentioned earlier, or something else?

 

--

//Sorin

**Comment by jberkel** [comment]
@adrian-vg not sure why what would be. maybe reset the backup state? (Select "Reset" from the menu)

**Comment by adrian-vg** [comment]
Will try, thanks.
