### ISSUE TITLE
Support for Nested Labels

### ISSUE THREAD

**Issue by jparris** [jberkel/sms-backup-plus#181]
Howdy,
I'd perfer to keep my sms & call logs in a nested label rather than cluttering up the label bar. Gmail tells me label's path is /personal/logs/phone_sms but SMS Backup + complains when I give it that path. 
Thanks,
-Jon

**Comment by dymm2000** [comment]
Currently does not works with nested labels:
Both "backup\sms" and "backup/sms" corresponds to the regular labels.
"backup-sms" (as GMail shows nested label) returns error:
"SELECT "backup-sms"; response: #6# [NO, [NONEXISTANT], Unknown mailbox: backup-sms (Failutre)]
