### ISSUE TITLE
XOAuth logon error

### ISSUE THREAD

**Issue by hhallman** [jberkel/sms-backup-plus#184]
I'm using google apps and the application has been working until recently.
(Last successful backup was on 25th of september.)
Error output is "Authentication error: null" in the log. No settings have been changed in neither gmail nor the application. IMAP is enabled.

**Comment by Ulopes** [comment]
Uninstall and reinstall SMS Backup+ solved the problem.

**Comment by sf395** [comment]
Seems strange but uninstalling and reinstallinmg SMS Backup+ solved the problem too.
