### ISSUE TITLE
Instant backup

### ISSUE THREAD

**Issue by gigozz** [jberkel/sms-backup-plus#234]
Hi sir, is it possible to backup a sms in the same moment that it arrive or decrease wait time from one minute to few seconds?
Kind regards

**Comment by chaoqing** [comment]
@jberkel Hi, I know this issue have been closed a long time ago, but the feature request seems still not handled. The minimal "Incoming Schedule" interval is one minute, which make me wondering whether this is somehow a really needed minimal interval or just one of enum configurations. If it is the second case, do it mean that I can add one interval option like "1 seconds" without introducing bugs?

**Comment by chaoqing** [comment]
> if you heavy care about that, you can try to bulid it yourself before jberkel to update.
> just change the value of "auto_backup_incoming_schedule_values" in /res/values/arrays.xml

I have already tried this, adding options like `5 seconds`. But it seems the `incoming backup` no longer work. I tried to search the code for some kind of hard limit on minimal interval but do not success. I noticed the actual trigger is done through `com.firebase.jobdispatcher`.

@jberkel can you explain why this do not work?
