### ISSUE TITLE
HTC One (Android 4.1.2) - sms backup+ not backing up incoming txts?

### ISSUE THREAD

**Issue by harkamus** [jberkel/sms-backup-plus#329]
Heya. First of all, great app and much thanks for this. Unfortunately, it only worked fine for a few days. Now whenever I back up texts, only my sent texts get backed up. Incoming texts never get backed up. I can only think of one reason this is happening since the application used to work fine. HTC sent out an update to Android over the air shortly after I installed this application. It didn't upgrade Android to 4.2.2, but did upgrade it to another version of 4.1.2. Now, I've never had the automatic back up enabled, so I never noticed until now that my incoming texts weren't backed up to google. Is this a known issue with the HTC One after the update to Android?

And if it is, will the issue be resolved once 4.2.2 gets released for HTC One later this month?

**Comment by jberkel** [comment]
not sure what to do about this, never could reproduce locally, seems device specific. closing.
