### ISSUE TITLE
Regularly scheduled backups don't occur

### ISSUE THREAD

**Issue by swamp2** [jberkel/sms-backup-plus#340]
This used to work. It stopped sometime recently. I regularly accept new versions. Am currently using v 1.5.4 on Droid DNA with Android 4.2. Sync log here: https://gist.github.com/swamp2/5973659 (showing two recent successful manual backup).

**Comment by jberkel** [comment]
the only reliable way to fix this is to rewrite big portions of the backup code (using SyncManager), but not happening soon since it works for a large group of users.
