### ISSUE TITLE
I/O Error in the middle of Initial Backup.

### ISSUE THREAD

**Issue by c-maloney** [jberkel/sms-backup-plus#361]
I installed SMS Backup+ v1.5.5 to my Samsung Galaxy Proclaim running on Android 2.3.6 OS on August 09, 2013.

After following the setup instructions given on the README.md thread, I started the initial backup of some 8000+ texts. After 2 hours, I examined my phone to find that the app had backed up text messages through 22:49.50 on June 18, 2013 before suffering an I/O error. Since that time, I have tried turning off the "require wifi" and backing up using 3G as well as rechecking all the settings both on the app and on my Google email, but continually hit the same "I/O Error" before anything is backed up.

As I do not understand how to link a "gist" to this message, I would appreciate someone explaining how to do that once I paste the "sync log" to one from my notepad file. I am not tech savy, but I do see that there is some type of a "time out" issue. It reads:

"General error: IO Error (exception: com.fsck.k9.mail.MessagingException: IO Error, underlying=java.net.SocketTimeoutException: Read timed out)"

**Comment by jberkel** [comment]
there were some I/O timeout errors fixed in a previous version, closing for now
