### ISSUE TITLE
Restoring doesnt put messages into SMS anymore

### ISSUE THREAD

**Issue by PDConner** [jberkel/sms-backup-plus#379]
I just got a new Samsung Note 3 and installed your software and signed in and did a restore ( I use it all the time on my note 2 worked great ) anyway I did a restore and it was restoring all my message (9034) or so of them and then when it finished I opened up Messages and nothing was there.. They went somewhere but not there.. What do I need to do .. Please Help
I am using versions:
Android Version - 4.3
SMS Backup+ Version - 1.5.5

Please let me know what I need to do to get them all back.. 

Thanks again 
Patrick

**Comment by chorrid** [comment]
Hello can I get this app on my new iPhone?
