### ISSUE TITLE
Incoming SMS not backing up

### ISSUE THREAD

**Issue by chaime11211** [jberkel/sms-backup-plus#380]
My incoming SMS is not backing up
everything else does  like  outgoing SMS, whats app and call logs

Please help  im using samsung Galaxy S4 Active

**Comment by brj319** [comment]
I am having same problem on Note 4/Android 4.4.4 - Send all my sent SMS to GMail, but NONE of my received SMS.
https://gist.github.com/brj319/ccdc88393ed124ab1168/download#file-brj319-note-4-sync-log-31615

**Comment by jcrben** [comment]
This from version 1.5.5 and latest stable is 1.5.10. @jberkel feel free to change name of the stale label if you'd prefer something else
