### ISSUE TITLE
Restore by Date Range

### ISSUE THREAD

**Issue by iTeedee** [jberkel/sms-backup-plus#384]
I'm back!  This is the second time, in a year, your software has saved my butt by restoring my text messages from Gmail when my S3 died and I moved to a new S3!  I love it!   

This time my S3 died and I've moved to an S4.  The restore started and is working fine but taking quite awhile as it's restoring 59,782 (honestly) text messages.  

I started it yesterday at 2pm and it ran all evening and all night, but when I got in the car this morning to come to work, at some point it lost it's data connection to Gmail and stopped with 6,895 left to restore.  I tried to restart, but it's going through all 59,782 again.  

Is there any way to restore by date range?  So I could restore 3 months and then the next 4 months and the next 3 months, during times I know there's a stable connection?

Thanks very much

Carolyn

**Comment by caseyjhol** [comment]
@jberkel Manually changing message labels from within Gmail is really more of a workaround than an actual solution. I think this issue should be reopened.

**Comment by jberkel** [comment]
The current beta contain some improvements around restoring (see #586). Is restoring the last X messages not good enough? Do you really need more fine-grained control?

**Comment by caseyjhol** [comment]
Sorry - didn't see the beta was up for download. Last X messages is good enough for my use, although I could still see a date range feature being useful at some point. Thanks for the app - love it!
