### ISSUE TITLE
[Whatsapp] Decrypted databases in data/cache folder takes up too much space if whatsapp db is large 

### ISSUE THREAD

**Issue by asdofindia** [jberkel/sms-backup-plus#386]
My phone specs:
Low internal memory
Huge whatsapp database (20 MB)
SMS Backup+ version 1.5.5

Issue:
Decrypted whatsapp databases (sqlite files) in /data/com.zegoggles.smssync/cache was taking about 200 MB space for me

Probable reasons:
1) I had used titanium backup twice to restore smssync along with data. This might have pulled the earlier cache too which smssync didn't delete because it didn't create it. In this case, please close this issue.
2) SMSsync doesn't delete cache immediately, in which case the internal memory will run out fast. In this case, please consider a patch.

**Comment by jberkel** [comment]
no longer supported
