### ISSUE TITLE
1st backup of SMS successful, nothing backing up since then

### ISSUE THREAD

**Issue by rodger2882** [jberkel/sms-backup-plus#418]
When initially setting up it backed up all texts to gmail, but since that time nothing has backed up. I had it set up for automatic backup and it never did it. I tried tweaking the auto backup and still nothing. I tried resetting it to try and redo the initial setup, nothing again. Is there anything I can try or do to get it to work? Either automatically or manually?

**Comment by jcrben** [comment]
Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta

**Comment by Logochic** [comment]
I have the same issue...Does not automatically back up and when I try to manually back up I get this message..."There were no items to backup" while I have lot of new SMS. Stopped working after last text received at 9:00am on 3/31/18 made no changes to phone etc. Please help. thank you!
