### ISSUE TITLE
Only backup sent sms, not received half of conversation

### ISSUE THREAD

**Issue by simonkbike** [jberkel/sms-backup-plus#440]
Newly installed on jelly-bean (4.1.1).  Backup seemed to run just fine and entries appeared in my Gmail account with SMS label.  However, can only see the sms I sent, not any I received.
Help?

**Comment by chenj0726** [comment]
Same symptoms, Galaxy Note3(SM-N9005). Android 4.4.2. Uninstalled and re-installed. Did not fix.

**Comment by armst14** [comment]
Tried this one on the note 2 ....seems to be working https://play.google.com/store/apps/details?id=tv.studer.smssync&hl=en_GB  just make sure when it asks you to back up that you do.DO NOT press skip.

**Comment by brj319** [comment]
I am having same problem on Note 4/Android 4.4.4 - Send all my sent SMS to GMail, but NONE of my received SMS.
https://gist.github.com/brj319/ccdc88393ed124ab1168/download#file-brj319-note-4-sync-log-31615

**Comment by maryd06** [comment]
This is how I fixed it:

Open the app > Auto backup settings > Incoming schedule set to Never,
Regular schedule set to anything other than Never.

I think....
