### ISSUE TITLE
MMS I send not getting backed up

### ISSUE THREAD

**Issue by hexfield** [jberkel/sms-backup-plus#447]
Picture messages I receive are getting backed up to Gmail fine, but ones I send don't appear in the thread and don't seem to be elsewhere either. Using v. 1.5.5

**Comment by dg4u** [comment]
Do the MMS messages appear in All Mail? They may not be showing up in conversational thread view because the MMS to/from headers are messed up. See issue #390.

**Comment by roumano** [comment]
Hi,

I have the same issue , my sms are correctly backup,
my receive mms are correctly backuped
but my sent mms are not backuped (or don't see them) into gmail


i have enabled the debug mode and get these when making the sync only for only 1mms send (no receive )



01-06 15:57 Démarrage de la sauvegarde (MANUAL)
01-06 15:57 Sauvegarde en cours (0 SMS, 1 MMS, 1 appels)
01-06 15:57 Utiliser la configuration BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
01-06 15:57 need to perform xoauth2 token refresh
01-06 15:57 token refreshed, retrying
01-06 15:57 Sauvegarde en cours (0 SMS, 1 MMS, 1 appels)
01-06 15:57 Utiliser la configuration BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=1, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
01-06 15:57 BackupState{currentSyncedItems=2, itemsToSync=2, backupType=MANUAL, exception=null, state =FINISHED_BACKUP}
01-06 15:57 Sauvegarde effectuée


Android version : 6.0

**Comment by kurahaupo** [comment]
@hexfield , @oioisud and @roumano does this problem still exist for you with the current version of SMS Backup+ ?

Are you sending MMS, or RCS (do you have "Advanced Messaging" enabled)? Please note that RCS backup is not currently supported.

Could you find your messages in the "All Mail" gmail folder (fr: "Touts Courriels") as dg4u noted above?

**Comment by hexfield** [comment]
This doesn't appear to be an issue anymore. I'm seeing the pics I send properly now. Thanks!

**Comment by kurahaupo** [comment]
Thanks, closing ticket.
