### ISSUE TITLE
Error during backup/restore: Unable to connect

### ISSUE THREAD

**Issue by typhoe** [jberkel/sms-backup-plus#451]
Hi,

I'm using the beta channel (1.5.6), and have an issue with trying to restore my previously saved sms.
I was using OmniRom on my Galaxy S4 and switched back to CyanogenMod 11 Nightly (24/05/2014) when I hit the problem.
All my old SMS seem to be present in my gmail account.

The adblog output after connecting my gmail account in SMS Backup+ and hitting Restore is:

D/SMSBackup+(10164): onResume()
D/SMSBackup+(10164): clearing cache in /data/data/com.zegoggles.smssync/cache
D/SMSBackup+(10164): using new contacts API
E/SMSBackup+(10164): error
E/SMSBackup+(10164): com.fsck.k9.mail.MessagingException: Unable to connect
E/SMSBackup+(10164): 	at com.fsck.k9.mail.store.ImapStore.checkSettings(ImapStore.java:399)
E/SMSBackup+(10164): 	at com.zegoggles.smssync.service.RestoreTask.restore(RestoreTask.java:91)
E/SMSBackup+(10164): 	at com.zegoggles.smssync.service.RestoreTask.doInBackground(RestoreTask.java:78)
E/SMSBackup+(10164): 	at com.zegoggles.smssync.service.RestoreTask.doInBackground(RestoreTask.java:40)
E/SMSBackup+(10164): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/SMSBackup+(10164): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/SMSBackup+(10164): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/SMSBackup+(10164): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/SMSBackup+(10164): 	at java.lang.Thread.run(Thread.java:841)
E/SMSBackup+(10164): Caused by: java.net.ConnectException: failed to connect to imap.gmail.com/2a00:1450:400c:c03::6c (port 993) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
E/SMSBackup+(10164): 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
E/SMSBackup+(10164): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
E/SMSBackup+(10164): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
E/SMSBackup+(10164): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
E/SMSBackup+(10164): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
E/SMSBackup+(10164): 	at java.net.Socket.connect(Socket.java:833)
E/SMSBackup+(10164): 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2207)
E/SMSBackup+(10164): 	at com.fsck.k9.mail.store.ImapStore.checkSettings(ImapStore.java:394)
E/SMSBackup+(10164): 	... 8 more
E/SMSBackup+(10164): Caused by: libcore.io.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
E/SMSBackup+(10164): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
E/SMSBackup+(10164): 	... 15 more
D/SMSBackup+(10164): finished (RestoreStateChanged{state=ERROR, currentRestoredCount=0, itemsToRestore=0, actualRestoredCount=0, duplicateCount=0}/0)
D/SMSBackup+(10164): restoring SMS provider com.google.android.talk
D/SMSBackup+(10164): stopping service, stateRestoreStateChanged{state=ERROR, currentRestoredCount=0, itemsToRestore=0, actualRestoredCount=0, duplicateCount=0}
D/SMSBackup+(10164): onResume()

I tried removing all authorization to my phone from the Google Dashboard and even switching the authentication method from oauth to imap with the same result.

The log file on the SD card is empty.

Thank you!

**Comment by jberkel** [comment]
@sunshinejnjn any luck with the logs ? would like to include this fix in the next version

**Comment by jberkel** [comment]
can't do anything without logs, closing this

**Comment by peeinwind** [comment]
I am in china,error message: Unable to connect.
The android phone can sign in gmail.


----------------------------------------------------------
10-29 14:11 备份请求 (手动)
10-29 14:11 开始备份 (MANUAL)
10-29 14:11 正在备份 (469 条短信, 1 条彩信, 0 条通话记录)
10-29 14:11 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
10-29 14:12 一般错误：Unable to connect (exception: com.fsck.k9.mail.MessagingException: Unable to connect, underlying=java.net.SocketTimeoutException: failed to connect to imap.gmail.com/216.239.38.123 (port 993) after 30000ms)
10-29 14:12 java.net.SocketTimeoutException: failed to connect to imap.gmail.com/216.239.38.123 (port 993) after 30000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
	at libcore.io.IoBridge.connect(IoBridge.java:112)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
	at java.net.Socket.connect(Socket.java:833)
	at com.fsck.k9.mail.store.imap.ImapConnection.connect(ImapConnection.java:584)
	at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:110)
	at com.fsck.k9.mail.store.imap.ImapStore.checkSettings(ImapStore.java:576)
	at com.zegoggles.smssync.service.BackupTask.backupCursors(BackupTask.java:247)
	at com.zegoggles.smssync.service.BackupTask.fetchAndBackupItems(BackupTask.java:146)
	at com.zegoggles.smssync.service.BackupTask.acquireLocksAndBackup(BackupTask.java:126)
	at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:119)
	at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:46)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

10-29 14:12 --------- beginning of /dev/log/main
D/k9      (25437): Connecting to imap.gmail.com as imap.gmail.com/216.239.38.123
W/k9      (25437): Local key store has not been initialized
E/k9      (25437): Failed to login, closing connection for conn1107000712

10-29 14:12 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=com.fsck.k9.mail.MessagingException: Unable to connect, state =ERROR}
10-29 14:12 备份已完成
10-29 14:46 Not set up to back up. autoSync=false, loginInfoSet=true, firstBackup=true

**Comment by peeinwind** [comment]
after change the host ip of imap.google.com, it work pefect!

**Comment by primaleph** [comment]
I just experienced this same issue today. Would you like a log file?

**Comment by jberkel** [comment]
@primaleph sure!

**Comment by primaleph** [comment]
04-15 14:31 Not set up to back up. autoSync=true, loginInfoSet=true, firstBackup=true
04-15 17:51 Backup requested (regular)
04-15 17:51 Starting backup (REGULAR)
04-15 17:51 Backing up (1254 SMS, 67 MMS, 500 call log)
04-15 17:51 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=REGULAR, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
04-15 17:55 General error: IO Error (exception: com.fsck.k9.mail.MessagingException: IO Error, underlying=javax.net.ssl.SSLException: Read error: ssl=0x7fac62eb80: I/O error during system call, Connection timed out)
04-15 17:55 BackupState{currentSyncedItems=184, itemsToSync=1821, backupType=REGULAR, exception=com.fsck.k9.mail.MessagingException: IO Error, state =ERROR}
04-15 17:55 Backup finished
04-15 17:55 Next backup scheduled for: 19:55
04-15 18:08 Backup requested (regular)
04-15 18:08 Starting backup (REGULAR)
04-15 18:08 Backing up (1073 SMS, 67 MMS, 500 call log)
04-15 18:08 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=REGULAR, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
04-15 18:08 General error: Cannot connect to host (exception: com.fsck.k9.mail.MessagingException: Cannot connect to host, underlying=java.net.ConnectException: failed to connect to imap.gmail.com/173.194.205.108 (port 993) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused))
04-15 18:08 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=REGULAR, exception=com.fsck.k9.mail.MessagingException: Cannot connect to host, state =ERROR}
04-15 18:08 Backup finished
04-15 18:08 Next backup scheduled for: 20:08

**Comment by primaleph** [comment]
I didn't see a way to include an attachment, so hopefully pasting is ok.

FWIW, I had this issue at work, but on my home WiFi the restore worked perfectly.

**Comment by jberkel** [comment]
@primaleph looks like a regular network connectivity issue, maybe there's a firewall blocking certain connections at your work wifi
