### ISSUE TITLE
Old sms not restoring

### ISSUE THREAD

**Issue by melissamedina1** [jberkel/sms-backup-plus#456]
I've used the software for years. I recently got the Samsung s4 and tried to restore from my gmail account and it says its restoring 1884 messages however only one comes in stating that they are all duplicates. Has anyone had this issue and how do I fix?

**Comment by chrisspar** [comment]
Not fully restoring on 1 SMS  contact. I followed all the FAQ, restoring and archiving details provided, but still can't restore it.
