### ISSUE TITLE
Unable to restore SMS

### ISSUE THREAD

**Issue by Quinnavere3** [jberkel/sms-backup-plus#460]
I have a Motorola Droid Razr Maxx HD, android version 4.4.2. I'm using SMS Backup+ 1.5.5. I've been able to restore sms messages before, but I can no longer restore. It appears that the restored messages show up for a split second and then are deleted/removed. I had already changed my message settings to no longer delete old messages so I do not have a limit on how many message my phone can store. I've tried going through the closed issues looking for a solution but have not been able to find a fix. It's very frustrating that there's no support email or phone number to contact. I'd like to restore my messages.

**Comment by mrninkoz** [comment]
The app is so great.  Dr.Fone is another great desktop app that can [recover messages](http://www.androidphonesoft.com/resources/recover-lost-sms-from-android-phone.html) from a wide range of Android devices.

**Comment by Clairepitch** [comment]
> The app is so great. Dr.Fone is another great desktop app that can recover messages from a wide range of Android devices.

I also tried Dr.Fone but I found it doesn't identify my Galaxy S6, it asked me to root my phone, I gave up!

**Comment by hasll** [comment]
As far me, i use Android rescuer tool to [recover  deleted messages from android](url="http://www.android-rescuer.com/recover-deleted-messages-from-android-phone.html") ,it is capable of recovering contacts ,photos,music,video from an android phone or iPhone,it is ideal for everyone,and never damage to device,

**Comment by Joobsens** [comment]
If you need to backup your contacts, there are many free apps or servers like Gmail, dropbox, kies.
If you wanna back up messages, or [recover messages from android](https://www.tunesbro.com/recover-deleted-messages-on-android.html) backup, I suggest you try sms+backup or TunesBro DiskLab for Android, which can help recover messages to your computer.

**Comment by kasncpy** [comment]
Thanks for you infor
