### ISSUE TITLE
On new/updated contact info, update existing (unknown) email threads

### ISSUE THREAD

**Issue by ambarisch** [jberkel/sms-backup-plus#462]
Scenarios:

1. Quite often, you receive an SMS from a new contact and you add the contact to your phone afterwards.
2. It is also common for people to send SMS like "This is my new phone number - XYZ", which we add to an existing contact afterwards.
3. Missed call is used commonly to share your number with stranger, which then is added manually to contacts.

However, the SMS / Call logs of these remain marked with "@unknown.email" even after the contact is added/updated.

* Is there a way to manually correct this?
* Can the app sniff for newly added or updated contact information and if the phone number is same as one of the "unknown" contacts, update the names/email addresses of those SMS/Call log threads?

**Comment by jberkel** [comment]
too complicated
