### ISSUE TITLE
show  error during backup/restore io error sms backup

### ISSUE THREAD

**Issue by drkpsarora** [jberkel/sms-backup-plus#466]
sir  i  am  getting  this  error   from last   few  days   tried  every thing  
1 factory    wipe
2 imap   setting 
3 internet  connection 
but  no  help 
plz  let  me  know   what  should i  do   
second    plz   add  a    cloud   storage    back   up   the   whole  phone   including the  application   apk 
plz  charge  for  it   so   we   can   get   a    better  service   
like  for   cloud   storage   different   categories  that need   renewal   just   like  antivirus  
that  will  be   great  
thanks 
i  hope  to hear  from    you   regarding the  issue  "error during backup/restore io error sms backup"

**Comment by jberkel** [comment]
probably duplicated of #499
