### ISSUE TITLE
[misleading title] Nothing is backing up

### ISSUE THREAD

**Issue by jenbarber** [jberkel/sms-backup-plus#473]
I just purchased a Galaxy S5 and I spent hours trying to restore my 27,000 text messages to my new phone.  Most of the time after about an hour the program cancelled, but after about 3 hours yesterday it completed the process, but there were no messages there--just phone numbers, but no texts.  
Now, I'm returning the Galaxy S5 and using my cracked S3 until I can be directed what to do.  I love this app and need my text messages for my business.  Does the program just not work on S5 and if that's the case, what upgraded phone does it work on?

**Comment by jcrben** [comment]
Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta
