### ISSUE TITLE
SMS Backup start date

### ISSUE THREAD

**Issue by laramon** [jberkel/sms-backup-plus#477]
When I backed up my phone I had about 57,000 texts. It took about 16 hours to complete. I looked in my gmail and it seemed like maybe there wasn't all of them there so I looked. Sure enough, the texts only start from January 16, 2013. I have texts from well before then that never got backed up. I checked and made sure that in the advanced options there wasn't anything selected limiting my texts; i.e. "all" was selected for how many to back up instead of, say, 100. It's backing up new SMS as they come in just fine, but the oldest messages are ignored.

I need all of my texts backed up so I can print some of them out for court.

This is also something I noticed but not important. I don't think a single MMS was backed up since I didn't see a paperclip icon next to any of the conversation threads.

My phone is a HTC Droid something, running Ice Cream Sandwich. I'm sorry I can't be more specific than that. It's from Verizon if it helps.

**Comment by mwisnicki** [comment]
Same thing here except I have very little texts (possibly less than 100) and yet I'm missing around a dozen texts before 2014-07-05 (oldest being from 2013-0-25).

**Comment by mwisnicki** [comment]
My phone is Samsung Galaxy Grand 2

**Comment by mwisnicki** [comment]
Here is my backup log: https://gist.github.com/mwisnicki/6c5ad27ad20cefba8118

My phone has Android 4.4.2.

**Comment by jcrben** [comment]
Sorry it didn't get all your texts.

Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta
