### ISSUE TITLE
Restore order 

### ISSUE THREAD

**Issue by ashh87** [jberkel/sms-backup-plus#480]
I restored my sms messages and found them to be in the wrong order. From what I can see, this is due to #269, and also maybe #94. I'm not sure if they're the same thing and they've both been inactive for a while, so I've started a new issue.

To get messages in the right order on (for example) Sony phones, it looks like they have to be inserted oldest first, which conflicts with peoples' want to have newer messages available at the start of the restore, so cancelling midway gets the most recent ones restored.

To deal with this, I propose splitting the restoration process into two phases: message download and then message restore. Instead of adding messages one by one, messages should be downloaded newest first and added to a local storage. Instead of the local cache, which I see gets wiped, the messages could be saved locally using something like the k9 LocalStore. If the restore is cancelled, then the messages can be added to the real sms store as a 'tidying up' stage. The downloaded messages would be iterated through in reverse order, meaning they display correctly (hopefully) on Sony etc devices, and fulfill the newest restored first idea. Hopefully, this tidying up should be relatively quick, as the messages are already downloaded...

In #269, MarSoft describes another problem with restoring on Sony devices. If new sms messages aren't synced, then restoring older messages will bury them. I think the solution to this could be to first ensure that a backup is made if the user has allowed it. Remaining unsynced messages should then be added to the (top of the) local storage, and the sync can continue as normal. I've not looked at what duplicate detection the app does, but restoring messages one by one will allow duplicates to be deleted one by one (so crashes/cancelling doesn't trash the lot) and reinserted.

After all this, the workaround linked to in #94 could be considered in necessary. There might also be the possibility of reducing overhead by calling ImapStore's fetch with more than one message at a time, as messages would no longer be processed individually at the download stage.

**Comment by jberkel** [comment]
@ashh87 the restore improvements you describe sound reasonable. unfortunately i probably won't work on it anytime soon.
