### ISSUE TITLE
Restore triggers the messaging app notification for new messages

### ISSUE THREAD

**Issue by ricferr1976** [jberkel/sms-backup-plus#494]
In a Oneplus One running Android 4.4.4 and using Hangouts as default messaging app, when using the SMS Backup + beta to restore, after restoring i get a recurrent notification from the Messaging app saying that i have new messages. The number of new messages is the same as the messages i just restored. I can't get rid of the notification.

Steps:

1. Successfully restore SMS with SMS Backup + beta.
2. Messaging app notification appears saying i have X new messages.
3. Enter messaging app through the notification. It warns that i have Hangouts as default.
4. The notification appears again.

This is not a show stopper but is annoying.

**Comment by jberkel** [comment]
sorry not fixing this

**Comment by bmedici** [comment]
Do you have anything new about this? Having the same troubles, though it doesn't seem to be related to any restoration method.
