### ISSUE TITLE
I/O ERROR (timeout after 5 minutes)

### ISSUE THREAD

**Issue by LSmith6938** [jberkel/sms-backup-plus#499]
getting I/O Error when trying to back up about 22k text messages. error occurs after several hundred messages have been "backed up"... it stops backing up between 500 and 1000 messages, randomly. i have disabled wifi backup, enabled wifi backup, restarted the app, reset the app, uninstalled the app, checked gmail settings, etc.

what's interesting is that the app says it's backing up, but does not create gmail messages. the folder is empty, even though SMS backup tells me it's backed up a number of messages. i only have 1 gmail account linked on my phone.

please help. i desperately need to data reset my nexus 5, and i dont want to lose my texts, so i've been waiting to data reset the phone until after i have backed up all my texts.

here is the link to the sync log:
https://gist.github.com/LSmith6938/dc9b14681caf6d2592dc

**Comment by robotcmastr5000** [comment]
Was running a Sprint Note 4 With Marshmallow update. SMS Backup + has worked on there. I can see all the messages in my gmail. However, my note 4 stopped working. And I now have a galaxy s7 running marshmallow as well. But i cannot get SMS Backup + to restore with out the I/O Error - Please help?

**Comment by Fisherpon** [comment]
I'm on a Samsung S8 running Android 7.0, and I'm having the same issue as this thread (I/O error between 500 and 1000 messages). I tried installing the beta APK that seemed to fix it for others (https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.6-BETA10), but it wouldn't let me install it as 'the packet seems to be corrupt' (Can't remember if it said packet or package). Was that beta APK rolled out into the main app at any point?

**Comment by Keyupgiorgio** [comment]
@jberkel https://stackdev.space/questions/transforming-a-java-string-into-a-7-bit-string
