### ISSUE TITLE
Connected, but 'unable to connect', not in account permissions

### ISSUE THREAD

**Issue by SimonDedman** [jberkel/sms-backup-plus#506]
Hi, I restored my apps & settings from one Nexus5 to another with adb which may be the blame for this.
Issue: SMS Backup+ 1.5.5 setup and was working fine until 5th Dec (now 11th). TriCrypt setup & working. Says it's connected to my gmail BUT it's not listed in the gmail account settings; hitting backup waits then fails, "unable to connect".

If this is caused by my adb manoeuvre, can I trigger a google authentication request without uninstalling & reinstalling the app? I tried disconnecting & reconnecting but it didn't trigger it.

Also, semi related: in the github main page, the link to google accounts is out of date, it should be: https://security.google.com/settings/security/permissions

Cheers!

**Comment by SimonDedman** [comment]
Hi J, thanks again for the tip, I uninstalled & reinstalled, and have found an interesting bug: when I've been on certain wifis, sms backup + (SB+?) connects fine and starts syncing*. But with >15000 items to sync I couldn't finish as I had to check out of the hotel. It worked on a bus wifi. It worked on my home wifi. But it does the "can't connect" thing now I'm at work, either patching through my laptop (using Connectify, so the laptop's on the net and it turns its wifi adapter into a hub), or via the uni wifi (which has webpage signin).
My google security page STILL doesn't say I've got permission.... but then how come I was able to sync some 1000 items already?

Apologies that this isn't a well formatted bug report but hopefully it'll get the ball rolling.


*the progress counter often "double counts", e.g. 1,5,2,6,3,7,4,8, rather than 1,2,3,4. Don't know if this has been bug reported, if not let me know & I'll create one.
Similarly, a bug that's not too easy to explain: the 'backup' button isn't very responsive. Often I have to hit it a random number of times before it reacts, and there's loads of delay when cancelling also. The progress status messages could be improved also. Again, please let me know if a bug has already been reported and if not I'll do so. Cheers.

**Comment by jberkel** [comment]
please file a separate bug report if still needed. thanks.
