### ISSUE TITLE
Cannot restore on Motorola Droid Turbo

### ISSUE THREAD

**Issue by Gimrall** [jberkel/sms-backup-plus#511]
I just upgraded from the droid razr maxx to the droid turbo.  The restore worked perfectly on the maxx, but I'm not getting anywhere with the turbo.  It says that it is restoring items, but when I open up messenger, there are no messages.  p.s. The call logs have never worked for me on either phone.

**Comment by myviewnow** [comment]
Lucky you! I look with envy, the Turbo's not been released in the UK. Seems like a perfect mix of phone!

**Comment by jberkel** [comment]
very likely device specific bug
