### ISSUE TITLE
App stops unexpectedly immediately after log-in phase

### ISSUE THREAD

**Issue by Faelights** [jberkel/sms-backup-plus#515]
Hi there,

A friend recommended SMS Backup+ to me last week, so I installed version 1.5.6 on my LG-P999 (Optimus 2x), Android version 2.2.2.

Every time I try to initiate the very first manual back-up, the application stops unexpectedly right after the log-in phase. I've already uninstalled and reinstalled a couple of times to see if that would fix it, and I tried changing the IMAP settings (same thing happened in plain text as in XOAuth), and none of it has changed a thing. Please help!

Thank you,

-- Fae.

**Comment by Faelights** [comment]
That seems to have done the job. Thank you so much!!!

**Comment by jberkel** [comment]
you're welcome.
(closed w/ 21019e6ed76e82b5281837c120105acd6d573b93)
