### ISSUE TITLE
Special character scrambled after SMS restore

### ISSUE THREAD

**Issue by patmu** [jberkel/sms-backup-plus#519]
SMS Backup Version 1.5.8
Android Version 4.4.2, tested on HTC One Mini and Wiko Birdy

After restoring SMS, all special characters and German Umlaut (ä,ö,ü,..) are scrambled. It seems  to be an UTF8 coding issue because hex (C3 A4) is the code for 'ä'.

Example: 
Restored Text: Hey p=C3=A4de, ...
Orig Text in Gmail: Hey päde

I also tested the restore with previous version 1.5.x from Google play store (don't know the version number...) without this issue.

**Comment by jberkel** [comment]
closed in fd420c75fd4fc5457da8e94cace1d470e51c771c
sorry about that, just pushed a new apk to google play.
