### ISSUE TITLE
bluetooth incar phone sync disabled

### ISSUE THREAD

**Issue by michaeldaly600** [jberkel/sms-backup-plus#522]
SMS backup+ was great at restoring to KitKat 4.4.4 phone after ROM reflashing, but had to be uninstalled before phone would again sync via Bluetooth the 'contacts' and 'call history' to the built-in car system. It seems that SMS backup+ somehow blocks the phone from transmitting the information, but does not block the bluetooth entirely as calls can still be made through the hands free car unit...
Any ideas?

**Comment by jberkel** [comment]
very unlikely
