### ISSUE TITLE
Dependency to commons-io and apache-mime4j-core missing?

### ISSUE THREAD

**Issue by RealRancor** [jberkel/sms-backup-plus#523]
Hi,

i'm not absolutely sure but it seems the current pom.xml is missing the dependencies to:

http://mvnrepository.com/artifact/commons-io/commons-io/2.4
http://mvnrepository.com/artifact/org.apache.james/apache-mime4j-core/0.7.2

for building the app from source.

**Comment by jberkel** [comment]
the dependencies are specified in the pom of k9-maillib: http://dl.bintray.com/jberkel/maven/com/fsck/k9/mail/lib/0.0.1.f7b2f26/lib-0.0.1.f7b2f26.pom

i guess it doesn't work the way you build the software because the mail-lib jar is installed manually, with a generated pom?

**Comment by RealRancor** [comment]
Hi,

aahh i see. Thanks for the info. Closing this because it seems a problem our side.

**Comment by ildar** [comment]
excuse me, where can I find the corresponding f-droid issue? Anyone?
