### ISSUE TITLE
[Minor] A single call log entry has the incorrect date. Always shows: Last item backup up: Jan 1, 2035, 1:00:00 AM

### ISSUE THREAD

**Issue by kev007** [jberkel/sms-backup-plus#526]
![2015-01-20 21 14 19](https://cloud.githubusercontent.com/assets/3058438/5826368/93ecda26-a0f2-11e4-9935-1952e59d6e0a.jpg)

My last item backup up always shows Jan 1, 2035, 1:00:00 AM because one entry in the call log was dated incorrectly after flashing a ROM. I never noticed because I would check my backups by looking at the contents of the IMAP folder in my GMail. It hasn't really bothered me, but it might be troublesome for others. 
Solutions?

**Comment by kev007** [comment]
It was stupid of me not to check the call log! It hasn't been backed up since 17/5/2013, presumably when the error occurred!

**Comment by jberkel** [comment]
you'll need to reset the sync state.
