### ISSUE TITLE
Problems Restoring SMS

### ISSUE THREAD

**Issue by tbgreen** [jberkel/sms-backup-plus#527]
I have a problem, currently with restoring SMS messages. I have made backups using a number of versions of SMS B + from a number of Phones.

I have loaded my gmail account in Thunderbird and used the 'duplicate removal' plugin to ensure that the SMS folder has no duplicate messages (surprisingly few considering the amount of time I have used this product!)

I have moved to a new phone (Galaxy S4 mini, Android 4.4.2 and SMS B + 1.5.8) and want to restore all messages and call logs to new phone, all has gone well I think with the call logs, but when resting SMS I get a final message saying that out of 7000 odd messages only 3000 odd imported the rest are duplicates. repeating the process will restore more messages and I can repeat this till I have most of the messages in, however I then end up with a lot of my sent messages being duplicated, non of my received messages are duplicated, just my sent. I have deselected the option to delete messages in thread over a threshold.

I have turned on logging but end up with a 0 byte file.

**Comment by romainneutron** [comment]
Same issue here. About 26000 SMS are in my backup, only few hundreds / thousands (its not constant) are imported when I try to restore.

To restore, I empty all threads of SMS, I reset SMS Backup +, and I press the restore button. Most of SMS are marked as duplicate, all SMS are few years old, I never got a recent SMS in the restored ones

**Comment by angryziber** [comment]
Is it a problem with RestoreTask.updateAllThreads()?

**Comment by angryziber** [comment]
Actually, updateAllThreads() must definitely run in case of a problem with restore (e.g. IMAP timeout) so that the stuff that was restored so far would become visible.

**Comment by samrsmart** [comment]
I am having the same problem when trying to restore to new phone, an ASUS ZenFone 2 (Model # ASUS_Z00AD) w/android 5.0. There are 3821 SMSs that were restored yet I only see 1 from yesterday, and a few hundred that stop July 2014, very large gap there. I uninstalled/reinstalled SMS BU + and verified that Gmail had IMAP enabled. Reran the restore and had 3821 duplicates, 0 restored with the same messages available. Any suggestions?

**Comment by jberkel** [comment]
Addressed in #586

**Comment by jcrben** [comment]
@participants are any of you up for trying the latest beta to confirm that this is fixed?  https://github.com/jberkel/sms-backup-plus#beta

**Comment by TheMattD** [comment]
Hey guys, 
I have used the restore before with success but it takes 2-5 days for large amounts of sms.. 
However, I'm now having an issue restoring where it's only finding 2 messages instead of the thousands which are on my gmail account.. 
Any ideas?

**Comment by jcrben** [comment]
@TheMattD restoring thousands is not designed - see https://github.com/jberkel/sms-backup-plus#im-not-able-to-restore-all-of-my-insert-huge-number-messages

also you should always disclose your version

**Comment by jcrben** [comment]
Given the lack of response in 2 weeks, closing.
