### ISSUE TITLE
Telegram Support

### ISSUE THREAD

**Issue by Someguy123** [jberkel/sms-backup-plus#528]
Since it seems no progress is being made by Telegram themselves, how about someone looks into putting a backup option into SMS Backup Plus.?

The biggest problem is that it probably would need to be a small telegram client built into the app for it to access messages and media stored in the cloud.

https://github.com/DrKLO/Telegram/issues/384

**Comment by jberkel** [comment]
sorry i won't add any more features to the app

https://github.com/jberkel/sms-backup-plus#can-you-add-feature-x-
