### ISSUE TITLE
undefined behaviour when new SMS received during restore

### ISSUE THREAD

**Issue by Lx** [jberkel/sms-backup-plus#529]
The FAQ states that if SMS Backup+ is not deactivated as the default messaging app after a restore, new messages may be lost.

This suggests that any new messages received during a restore could be lost as well.

Explicit documentation of this would be greatly appreciated so that users can time restore operations to minimise the loss of new incoming messages.

Ideally, SMS Backup+ would just write these messages to the inbox and make a note to back them up during the next backup operation.

**Comment by jberkel** [comment]
I haven't tried this myself but the best option for now would be to put the phone in airplane mode during restore. however you're right, it might be possible to just store the incoming message (similar to the way restore works)

**Comment by jberkel** [comment]
Has been addressed in #809
