### ISSUE TITLE
Select "SMS"; response: #6# [NO, [NONEXISTENT] error

### ISSUE THREAD

**Issue by osubuckeyechick** [jberkel/sms-backup-plus#530]
I got this error while backing up my texts. How do I fix this? The full error code is ;

Select "SMS"; response: #6# [NO, [NONEXISTENT], unknown mailbox: SMS (failure)]

**Comment by jberkel** [comment]
it could be this: https://github.com/jberkel/sms-backup-plus#i-get-the-following-error-during-backuprestore-command-select-sms-response-6-no-unknown-mailbox-sms-failure

**Comment by osubuckeyechick** [comment]
That was it. Thank you!

**Comment by comp9** [comment]
That was the issue for me as well. Thanks for the link, solved it for me as well! Hope they'll update the error message, wouldn't have guessed need to check imap based on that :D.
