### ISSUE TITLE
No log entries for unknown callers (CLIR)

### ISSUE THREAD

**Issue by cdrfun** [jberkel/sms-backup-plus#532]
If the caller has CLIR enabled the call is not logged. (Calendar and Gmail tested).

**Comment by merrill-oakland** [comment]
I too am seeing the problem too. Would love it if I could get Unknown number calls logged.

**Comment by myviewnow** [comment]
I've just noticed this happens, no unknown caller entry when I went to add a note to the calendar entry for an important incoming call. First bug I've found that is a problem, apart from the totally not-your-fault demise of WhatsApp logging. This is an amazing app. Thanks so much. I'm amazed Google hasn't tried to swallow you up (with deserved £$$) and make this a core android feature....

**Comment by jberkel** [comment]
Since this used to work and the code has not been touched in a long time I wonder if something on the Android side has changed. Not sure if this is reproducible in an emulator, and I don't have a device to test right now.

**Comment by myviewnow** [comment]
Wow. Prompt reply. Maybe also changes in calendar, as I use the google play rather then stock android?  I've also changed phones, so I'll could go back and see if that's an issue, whether this dropped at the changeover, though both ran KitKat, I think. Moto RAZR i --> Sony z3 compact. Would that help?

**Comment by cdrfun** [comment]
My current configuration: OnePlus One with Stock ROM (Android 4.4.4). If needed I can test it with an old Nexus 4 and any ROM this weekend. I'll also try to check with an emulator.

**Comment by jberkel** [comment]
I managed to reproduce in an emulator running Android 5.0, will see if I can fix it soon.

**Comment by myviewnow** [comment]
Thanks very much JB!

**Comment by jberkel** [comment]
think i fixed the problem, can you try the apk from https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA3

**Comment by cdrfun** [comment]
Great, it works! Thank you so much for your effort.
