### ISSUE TITLE
Nothing Backs Up

### ISSUE THREAD

**Issue by Xipherisroot** [jberkel/sms-backup-plus#536]
DroidX (2013) Running 4.4.4

Installed the application and kept all the default items its set to back up, and I have many contacts and a few SMS messages but no MMS that I know of for the application to backup, however when I press the "backup" button it instantly says "There were no items to backup.", and if I login to the account being used to backup to, there's nothing that it saved.

Looking at the log with all extra information on, I get the following

Backup requested (manual)
Starting backup (MANUAL)
Skipped (no items found)
BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=null, state =FINISHED_BACKUP}

All within the same second.

I am using the default SMS app on the phone, there is maybe 20-30 messages total.

I /am/ attempting to use a specific IMAP server, however I have confirmed many times that the settings are correct and that the account is working just fine, it has a valid SSL cert, is running AOK from other clients at port 993, the username and password are confirmed and correct too.

Very odd, any ideas?

**Comment by jberkel** [comment]
could be a timestamp issue. maybe try to reset backup state?
