### ISSUE TITLE
Contacts disappearing due to @unknown.email syntax

### ISSUE THREAD

**Issue by thrillofachase** [jberkel/sms-backup-plus#537]
Many of my contacts have "disappeared" from my address book, and I just realized that it might be due to SMS Backup+. It looks like certain contacts in Gmail have split from their phone numbers because the phone numbers have been stored using the syntax "number@unknown.email"

As an example, I've had James as a contact in my phone for a long time. James is no longer coming up in my phone's directory when I search for his name. When I check old texts from him that were backed up by SMS Backup+, they only use his email address and look like this in Gmail:

Subject: SMS from james@gmail.com

His contact no longer has his phone number in my Gmail contacts. On the texts from him stored in my phone, it comes up like this:
From: 8025550000

When I view that contact, the email address is stored as 8025550000@unknown.email

Essentially, they are viewed as two different contacts. It looks like this has happened with over 100 contacts in my phone, and I only noticed it in the last two weeks.

I have an HTC One, Android version 4.4.3. Not sure if this is an app problem, a Gmail problem, a phone problem, or some combination thereof.

Amanda

**Comment by jberkel** [comment]
no idea, the app itself doesn't change your contact entries. if you're numbers are correctly mapped in the contacts this should not happen.
