### ISSUE TITLE
Crash ("SMS Backup+ stopped working") when trying to backup

### ISSUE THREAD

**Issue by sputtene** [jberkel/sms-backup-plus#538]
Hi,

Since Jan 12th SMS Backup+ crashes when I try to manually backup or when I restart my phone and the SMS Backup+ service gets started (which triggers an automatic backup, I assume).

I've cleared the cache and data through the Android manage apps menu, but it still crashes.

I'm using a regular IMAP server, not a GMail account for my backup. It worked for over 6 months with SMS Backup+, so I think that's not the problem.
I'm running SMS Backup+ 1.5.8, installed from F-Droid. My Android version is 4.2.2.

If I can help you with extra debugging logs or you need more information, I'd be happy to provide them to you.

**Comment by jberkel** [comment]
I think there was a broken version posted on f-droid for some time. Could you post the full stack trace?

**Comment by sputtene** [comment]
I've enabled `Sync log` and `Extra debug information` in the advanced settings, `sms_backup_plus.log` is created.
After I trigger the crash by pressing the `Backup` button in the main UI screen, the log file is 0 bytes.

Is there another way to get a stack trace?

**Comment by jberkel** [comment]
you need to run "adb logcat" from the console. for this you'll need to install the android sdk unfortunately, unless you have a rooted phone.
i would just try to reinstall 1.5.8 from f-droid, because there was a published version with a crash.
(#525 #523). 
@krt16s, does auto-upgrade for the broken version work?

**Comment by sputtene** [comment]
`adb logcat` shows the same error and stacktrace as described in #525.

The f-droid status page for SMS Backup+ states that version 1.5.8 was released on 17 Jan, so it's more recent than the version I have installed.
I'll reinstall, test and report.

**Comment by sputtene** [comment]
Removing and reinstalling version 1.5.8 from f-droid fixed it.

Thanks!

**Comment by krt16s** [comment]
Unfortunately not, since the versioncode is the same. We can force an updated VC on our side, but try to avoid it because upstream might use this VC as well someday. :/
