### ISSUE TITLE
Hasn't worked since I upgraded from a Samsung S3 to a S5

### ISSUE THREAD

**Issue by missmorte** [jberkel/sms-backup-plus#540]
It worked great on my last phone but has never backed up once on the new phone. It says Error during backup/restore:Command: SELECT "SMS"; response: #6# [NO,[NONEXISTENT], Unknown Mailbox:SMS (Failure)]

I have the same gmail account, haven't changed settings, and verified that they were still set the way they were when this app last worked for me. i've recommended this app to so many people. I'm disappointed it isn't working especially since i have many important texts that my phone won't let me lock (yet another S5 issue)

**Comment by jberkel** [comment]
have you verified that imap is enabled ? https://github.com/jberkel/sms-backup-plus#i-get-the-one-of-following-errors-during-backuprestore-command-select-sms-response-6-no-unknown-mailbox-sms-failure-or-response-6-no-nonexistent-unknown-mailbox-sms-failure

**Comment by missmorte** [comment]
Yes

--Miss Stasha

"A heart can stop beating for a while, one can still live."

**Comment by missmorte** [comment]
I unchecked all imap stuff and rechecked it. now it backs up straight text
but no mms or call logs.

On Wed, Mar 11, 2015 at 4:13 PM, Stasha Powell <stashapowell@gmail.com>
wrote:

> Yes
>
> --Miss Stasha
>
> "A heart can stop beating for a while, one can still live."
> On Mar 11, 2015 3:11 AM, "Jan Berkel" <notifications@github.com> wrote:
>
>> have you verified that imap is enabled ?
>> https://github.com/jberkel/sms-backup-plus#i-get-the-one-of-following-errors-during-backuprestore-command-select-sms-response-6-no-unknown-mailbox-sms-failure-or-response-6-no-nonexistent-unknown-mailbox-sms-failure
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jberkel/sms-backup-plus/issues/540#issuecomment-78236050>
>> .
>>
>


-- 
--Miss Stasha

"A heart can stop beating for a while, one can still live."

**Comment by jberkel** [comment]
try with the latest beta from https://github.com/jberkel/sms-backup-plus/releases
