### ISSUE TITLE
How do I know MMS backup is working?

### ISSUE THREAD

**Issue by apoku** [jberkel/sms-backup-plus#543]
Hi--I'm new to smsbackup+ and am interested primarily in the MMS backup restore feature. I'm using version 1.5.8 from the play store. I'm on a Sony Xperia Z1 KitKat device.

I see the SMS messages appearing in my gmail account in the right order and with the correct timestamps. However, I don't see any of the pictures as attachments. Are they supposed to appear in the conversation thread?

**Comment by Mayhem71** [comment]
Per the ReadMe (https://github.com/jberkel/sms-backup-plus/#readme)

MMS backup support (since 1.1), only available on Android 2.x

I, too, wish MMS back up worked under 4.x and 5.x. No idea if the dev plans to fix this or even can.

**Comment by jberkel** [comment]
sorry, won't work on this
