### ISSUE TITLE
Restore causes crash on HTC One M7, 5.0.2, Sense 6

### ISSUE THREAD

**Issue by samuelrhaynes** [jberkel/sms-backup-plus#548]
The app is linked to my google account. I recently change rom to 5.0.2 on my HTC and now the app won't restore any texts. It says logging in, then calculating, then crashes and says "Unfortunately SMS Backup+ has stopped"

The sms_backup_plus.log shows nothing about restoring
Below is an adb logcat export. It starts to fail at line 531.
https://gist.github.com/samuelrhaynes/513463d912598c516d71#file-smsbackup-crash

Hope you can help

**Comment by sachinsuyash** [comment]
I have the same problem but with backing up whatsapp texts. I know they aren't natively supported now the app backs up call logs and SMS just fine but crashes soon after.

**Comment by jberkel** [comment]
the crash is inside the framework code, nothing i can do about it. might be a HTC issue.
