### ISSUE TITLE
Not backing up random messages

### ISSUE THREAD

**Issue by islandgirlturtle** [jberkel/sms-backup-plus#550]
I have a Samsung Galaxy S5 and it's not backing up some messages.  For example, I have two message threads, each with a couple of people as a group message.  It has saved random messages from each thread into my gmail, but not all of them, and it's saved all the messages in my gmail all over the place instead of keeping them all in one thread. Please help

**Comment by reginaharris67** [comment]
I'm having the same issue with my g3 sadly tmobile to who was helping me was a complete lame and erased the vital message from my old phone and now it appears there is no way to retrieve this message although I advised repeatedly of the importance of this message. Can anyone please help with recovery of lost messages which did not back up for some unknown reason? Please help this is my last hope of getting this message back it was the first message my boyfriend ever sent me I' ve worked very diligently to keep this.

**Comment by reginaharris67** [comment]
I'm having the same issue with my g3 sadly tmobile to who was helping me was a complete lame and erased the vital message from my old phone and now it appears there is no way to retrieve this message although I advised repeatedly of the importance of this message. Can anyone please help with recovery of lost messages which did not back up for some unknown reason? Please help this is my last hope of getting this message back it was the first message my boyfriend ever sent me I' ve worked very diligently to keep this.

**Comment by jberkel** [comment]
that's a gmail limitation, see FAQ
