### ISSUE TITLE
Call Log backup to calendar not working

### ISSUE THREAD

**Issue by flyingscot** [jberkel/sms-backup-plus#551]
On Samsung S4 since upgrading to Android 5.0.1
Calls are backed up to GMail, but not added to specified GMail calendar, happened on 17.March when I updated my phone.

**Comment by justr1** [comment]
Same here since 16th of April. Not sure, but I think my Lollipop-Upgrade (Xperia Z1) was some weeks before.

**Comment by flyingscot** [comment]
I did a load of research on this, and found a fix - not ideal but it works.
Remove your GMail account from the device, and then re-add it.
Once this is done, modify all the settings inside SMSBackup+ and it started functioning again ...

**Comment by justr1** [comment]
Workaround confirmed! Thx!
