### ISSUE TITLE
IO Issue when trying to restore messages

### ISSUE THREAD

**Issue by ekospirit** [jberkel/sms-backup-plus#553]
Galaxy S4, Android 5.0.1 Verizon phone, everytime I try to restore my messages back to the phone I got as a replacement. attached is all the log says about it, it also has no problem backing up to my account, it just wont restore my old messages and call log.

"05-07 00:03 Backup requested (incoming)
05-07 00:03 Starting backup (INCOMING)
05-07 00:03 Backing up (7 SMS, 0 MMS, 2 call log)
05-07 00:03 Backing up (7 SMS, 0 MMS, 2 call log)
05-07 00:03 Backup finished
05-07 00:05 Backup requested (incoming)
05-07 00:05 Starting backup (INCOMING)
05-07 00:05 Backing up (0 SMS, 0 MMS, 2 call log)
05-07 00:05 Backup finished
05-07 00:05 Backup requested (incoming)
05-07 00:05 Starting backup (INCOMING)
05-07 00:05 Backing up (0 SMS, 0 MMS, 2 call log)
05-07 00:05 Backup finished"

It seems to not recognize that i'm hitting RESTORE and not backup?

**Comment by jberkel** [comment]
no, these backups are triggered because of incoming messages. no idea what is going on.
