### ISSUE TITLE
Backed up calls subject has [SMS] prefix

### ISSUE THREAD

**Issue by ricardo3m** [jberkel/sms-backup-plus#558]
On advanced settings - Backup settings I activated the "Email subject prefix". Now all backed up SMS subject appears with "[SMS]" at the beginning. The problem is that with this activated all call logs are backed up with the same prefix as SMS. The expected behavior would be a subject with "[Call logs]" at the beginning. I'm using version 1.5.9.

**Comment by jberkel** [comment]
do you store call logs and SMS in the same folder?

**Comment by ricardo3m** [comment]
No. SMS are backed up to folder "SMS" and the call log is backed up to "Call log". When I activate the "Email subject prefix" everything is backed up to the SMS folder.

**Comment by jberkel** [comment]
I just checked the code, "Email subject prefix" can't possible influence in which folder the mail is stored. I also can't reproduce the bug. Make sure that you have a different label set for call logs, it looks like it is set to "SMS" for some reason.

**Comment by ricardo3m** [comment]
Sorry, I didn't describe the issue well. What is affected is the subject of the e-mail. Here goes an example of what is happening on gmail

![capture](https://cloud.githubusercontent.com/assets/12570951/8129692/8ca1d6aa-1103-11e5-9893-1ca14cda219a.JPG)

The folders for the call log and sms are being set correctly on gmail. The problem is with the subject of the e-mail. All SMS are being stored with a subject beginning with "[Call log]".

**Comment by jberkel** [comment]
So maybe the SMS label configuration is wrong then. can you double check the preferences?

**Comment by ricardo3m** [comment]
Here are some screenshots of my settings

![screenshot_2015-06-12-13-18-47](https://cloud.githubusercontent.com/assets/12570951/8129886/cb0381bc-1105-11e5-971b-2e4d4d235f57.png)
![screenshot_2015-06-12-13-18-10](https://cloud.githubusercontent.com/assets/12570951/8129887/cf5ee31e-1105-11e5-9fb3-4e96df7b9cd2.png)

**Comment by jberkel** [comment]
your settings look ok. another explanation could be that gmail is threading conversations from SMS + call log into one, and it only looks like the subject is wrong. maybe check on individual mails?

**Comment by ricardo3m** [comment]
I checked individual messages and the subject is correct. Gmail is threading messages with different subjects. I didn't know gmail did this

**Comment by jberkel** [comment]
ah, good. gmail does all sort of crazy things behind the scenes :)

**Comment by ricardo3m** [comment]
I never noticed before that it did this sort of thing. Sorry about wasting your time looking for a bug in your app.

**Comment by jberkel** [comment]
no problem! if you want to help in any way I'd appreciate if you could test the latest beta from https://github.com/jberkel/sms-backup-plus/releases. i'd like to do another release soon and need more people to actually test the code.

**Comment by ricardo3m** [comment]
I installed the latest beta. If there are any issues I'll let you know
