### ISSUE TITLE
SMS B + Only Backs Up Sent SMS mssgs, not received ones

### ISSUE THREAD

**Issue by TechGuy545** [jberkel/sms-backup-plus#559]
Hello, I have been using SMS Backup + on an older Android 2.2 phone for quite some time, and it has been working very well.  Now I am trying to get it to work on an Alcatel Onetouch Fierce 2 Android 4.4.2 and SMS Backup + 1.5.8 will only backup SENT SMS messages, not RECEIVED ones.  It will backup received MMS mssgs and the call log just fine.

I've uninstalled SMS Backup +, reinstalled it, and combed through the settings but received SMS messages are still not getting backed up.  What could be the problem here?

**Comment by jberkel** [comment]
this happens on some phones, not much I can do about it, it's a firmware issue
