### ISSUE TITLE
 Can't backup automatically (just manual) in plain text mode

### ISSUE THREAD

**Issue by Smsbackup** [jberkel/sms-backup-plus#560]
in 5/5/2015 my apps error by "Server does not support XOAUTH". for replace, i switching to plain text authentication but apps can't backup automatically, it just succeed in manual: fill all blank such as imap address,user nam/password anh click backup each time i login my apps. Who know why? help me, i want it auto.

**Comment by jberkel** [comment]
XOAUTH2 is now supported, see #554
