### ISSUE TITLE
General error: Command: SELECT "SMS"; response: #6#

### ISSUE THREAD

**Issue by markwaters** [jberkel/sms-backup-plus#561]
Trying to backup to a private (Non-GMail) IMAP server via WiFi.
SMS BAckup+ version 1.5.9

There is a current SMS folder , I have also tried renaming it so that a new SMS folder could be created.

I have used SMS Backup+ previously and it has worked perfectly.

03-06 14:18 Starting backup (MANUAL)
03-06 14:18 Backing up (1 SMS, 0 MMS, 0 call log)
03-06 14:18 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl://PLAIN:XXXXXXXXXXXXXXXXXXXXXXXXX@mail.collective-b.org.uk:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS]}
03-06 14:18 General error: Command: SELECT "SMS"; response: #6# [NO, Mailbox does not exist, or must be subscribed to.] (exception: com.fsck.k9.mail.store.imap.ImapException: Command: SELECT "SMS"; response: #6# [NO, Mailbox does not exist, or must be subscribed to.])
03-06 14:18 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=com.fsck.k9.mail.store.imap.ImapException: Command: SELECT "SMS"; response: #6# [NO, Mailbox does not exist, or must be subscribed to.], state =ERROR}
03-06 14:18 Backup finished

**Comment by jberkel** [comment]
could it be this issue?

https://github.com/jberkel/sms-backup-plus#i-get-the-one-of-following-errors-during-backuprestore-command-select-sms-response-6-no-unknown-mailbox-sms-failure-or-response-6-no-nonexistent-unknown-mailbox-sms-failure

**Comment by markwaters** [comment]
Thanks @jberkel , I did see that in another issue but I am not using GMail and am definitely subscribed to the SMS and Call Log IMAP folders.

**Comment by jberkel** [comment]
oh i see. i don't really know, doesn't look the problem is on the app side to be honest. could it be a casing issue? can you see the folder in your mail client? maybe try moving some messages there to make sure it is usable.

**Comment by markwaters** [comment]
I moved the previous SMS folder to SMS-old and created a new SMS folder , still failed.

So I have switched from version 1.5.8 to 1.5.6-beta4 (in the F-Droid repo) and its working!

**Comment by jberkel** [comment]
hm, interesting. 1.5.8 uses a new version k9 to handle IMAP, maybe something has changed there. which server do you use?

**Comment by markwaters** [comment]
Courier IMAP on a Debian Wheezy ARMHF.

I am using the K9-Mail client on the phone with no problems.

**Comment by jberkel** [comment]
hm, running out of things to suggest. but looking at the logs it's just the SELECT command which fails. i'll release a beta with a new version of k9 soon, maybe you can test it then, i'll add some more logging.

**Comment by markwaters** [comment]
great , looking forward to it , happy to help with testing.

**Comment by jberkel** [comment]
ok, can you try https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA5 ?
getting the debug log is a bit tricky. you'll need to enable sync log + extra debug information in the SMS Backup+ preferences.

then perform the backup, when it errors press POWER+VOL UP+VOL DOWN.

you should get a notification about a bug report. the only import part is the system log, it has the following header:

```
------ SYSTEM LOG (logcat -v threadtime -d *:v) ------
```

post it as gist or send it to me. thanks!

**Comment by markwaters** [comment]
I downloaded the 1.5.9.-BETA5 version this morning , uninstalled the older version and installed it.
Setup my server and credentials and enabled all the logging.
Started a backup and it worked without the 'General error: Command: SELECT "SMS"'
I have not got the system log out yet , but here is the application log which doesn't show any errors.

07-06 09:56 Backup requested (manual)
07-06 09:56 Starting backup (MANUAL)
07-06 09:56 Backing up (1 SMS, 0 MMS, 1 call log)
07-06 09:56 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl://PLAIN:XXXXXXXXXXXXXXXXXXXXXXXXX@mail.collective-b.org.uk:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
07-06 09:56 BackupState{currentSyncedItems=2, itemsToSync=2, backupType=MANUAL, exception=null, state =FINISHED_BACKUP}
07-06 09:56 Backup finished

**Comment by jberkel** [comment]
is everything working? reopen if now.

**Comment by markwaters** [comment]
Yep , all working now , no error messages and new messages are backed-up to correct directory.
Thanks @jberkel !
