### ISSUE TITLE
dismiss "Could Not Connect" notification at next scheduled backup

### ISSUE THREAD

**Issue by Lx** [jberkel/sms-backup-plus#562]
During times of no data signal, scheduled backups will necessarily fail and a notification to the effect of "could not connect" will appear.

I often see this notification many successful backups later, and I start diagnosing connectivity issues before realising that there's no issue to diagnose at this time.

Coding the notification to be removed when the next scheduled backup commences would prevent the notification from being displayed when there's no actual problem.

**Comment by jberkel** [comment]
can you try with 1.5.9-BETA6 ? https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA6

**Comment by Lx** [comment]
Thanks.  I've installed it and I'll let you know if I have any issues, although the intermittent nature of my underlying network means it might take a while.

**Comment by Lx** [comment]
Seems to be working well.  I've had a few intermittent network dropouts, and the notification hasn't persisted past network restoration.
