### ISSUE TITLE
1.5.9-BETA4 can not sync the call log to calendar?

### ISSUE THREAD

**Issue by ruleroller** [jberkel/sms-backup-plus#563]
I update from beta3, every thing goes well but this.

**Comment by jberkel** [comment]
weird nothing has changed w/ the call log code. what exactly does not work? can you post a log file?

**Comment by ruleroller** [comment]
I did these steps, now it seems works again.
- clear the smsbackup's date and uninstall the beta4
- install 1.5.8 from Google Play market
- configer the smsbackup's settings
- make a call and sync
- works
- upgrade to 1.5.9 beta4
- make a call and sync 
- works

:)

**Comment by jberkel** [comment]
alright :)
