### ISSUE TITLE
Remove whatsapp code from app

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#564]

**Comment by tatablack** [comment]
@jberkel, would it be possible for you to add a comment to this thread with the rationale for this decision? I tried to find a discussion about it here and on G+ but couldn't find much. Thanks in advance.

**Comment by jberkel** [comment]
@tatablack i understood that some users would be disappointed about this decision, it was not easy but makes more sense in the long run, i don't really want to support a feature which does not work for 95% of users. here's a repost of a comment on #434 

>Sorry I removed this feature because it was too complicated to support for the majority of users who always complained that WhatsApp backup was not working as expected.

>Of course there are workarounds, but they are too complicated to set up for a non-technical user, and they might also stop working any day.

>You can always manually install an older version which has WhatsApp support: https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA5

>From my perspective the best solution would be if somebody who is willing to support this feature would fork the app, remove the SMS/Call log related code and release a stand-alone WhatsApp backup tool.

**Comment by tatablack** [comment]
Thanks, @jberkel .
Having to play catch-up with some other app (without being able to sync with their changes beforehand) is never nice, I agree. And I guess a fork is a good idea, let's hope someone picks it up. :+1:

**Comment by nibelungen** [comment]
Hey,
did this ever get picked up by a fork??
Tried to find it - with no success so far.

Best regards

**Comment by jberkel** [comment]
@nibelungen don't think so! is it still possible to read whatsapp backups these days, or has it been fixed?

**Comment by nibelungen** [comment]
Hi @jberkel - yes its still possible, but since some month the backup does not include images, maybe its caused by using foldermount?! Just got my new phone and will try it again, but have to use an titanium backup because it looks like whatsapp crypt extractor does not work at the moment.... Give some feedback later on it when im done withe the new device.

best regards

**Comment by nibelungen** [comment]
Her @jberkel, 
After Backup of ~50000 messages (nearly all duplicates) i can confirm it still works.
But as mentioned above, media files are not backed up anymore. With or without foldermount. If you have some hint i will try it. But i also accept your decision if you wont support this.

Best regards, 
andreas

**Comment by Destix** [comment]
Hi @nibelungen have you found any solution to backup media files?

**Comment by kleisauke** [comment]
As a workaround we reintroduced the WhatsApp-code in our fork. When you build the APK from our source you can backup WhatsApp-messages again, but needs assistance of another app to re-crypt the .crypt12 files of WhatsApp to .crypt (OmniCrypt will do).

https://github.com/andrieslouw/sms-backup-plus

Backing-up media files is not supported.

**Comment by nibelungen** [comment]
Hi @kleisauke is there anything better than using the latest version that supports whatsapp?
Did you know why Backing-up media fails? It also occurs with the latest version that supports whatsapp.

best regards

**Comment by Conan179** [comment]
I have a litte problem with
https://github.com/andrieslouw/sms-backup-plus

Where can I report it? There is no issue section there.
(can coose a Calender)
