### ISSUE TITLE
Restore doesnt complete.

### ISSUE THREAD

**Issue by jcbeck** [jberkel/sms-backup-plus#567]
Says I have over 30,000 msgs to be restored. Takes a long time to "restore" but gets abt 2/3 way through & then craps out.

**Comment by jcbeck** [comment]
06-16 21:49 Backup requested (incoming)
06-16 21:49 Skipped because backup already running
06-17 07:53 Backup requested (incoming)
06-17 07:53 Skipped because backup already running
06-17 08:07 Backup requested (incoming)
06-17 08:07 Starting backup (INCOMING)
06-17 08:07 Backing up (13 SMS, 0 MMS, 1 call log)
06-17 08:07 Backing up (13 SMS, 0 MMS, 1 call log)
06-17 08:07 Backup requested (incoming)
06-17 08:07 Skipped because backup already running
06-17 08:08 Backup finished
06-17 08:36 Backup requested (incoming)
06-17 08:36 Starting backup (INCOMING)
06-17 08:37 Backup requested (incoming)
06-17 08:37 Starting backup (INCOMING)
06-17 08:37 Backing up (6 SMS, 0 MMS, 1 call log)
06-17 08:37 Backing up (6 SMS, 0 MMS, 1 call log)
06-17 08:37 Backup finished
06-17 08:38 Backup requested (incoming)
06-17 08:38 Starting backup (INCOMING)
06-17 08:38 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 08:38 Backup finished
06-17 08:41 Backup requested (incoming)
06-17 08:41 Starting backup (INCOMING)
06-17 08:41 Backing up (4 SMS, 0 MMS, 0 call log)
06-17 08:41 Backup finished
06-17 08:42 Backup requested (incoming)
06-17 08:42 Starting backup (INCOMING)
06-17 08:42 Skipped (no items found)
06-17 08:43 Backup finished
06-17 08:47 Backup requested (incoming)
06-17 08:47 Starting backup (INCOMING)
06-17 08:47 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 08:47 Backup finished
06-17 09:04 Backup requested (incoming)
06-17 09:04 Starting backup (INCOMING)
06-17 09:04 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 09:04 Backup finished
06-17 09:32 Backup requested (incoming)
06-17 09:32 Starting backup (INCOMING)
06-17 09:32 Backing up (2 SMS, 0 MMS, 0 call log)
06-17 09:32 Backing up (2 SMS, 0 MMS, 0 call log)
06-17 09:33 Backup finished
06-17 09:34 Backup requested (incoming)
06-17 09:34 Starting backup (INCOMING)
06-17 09:34 Skipped (no items found)
06-17 09:34 Backup finished
06-17 09:40 Backup requested (incoming)
06-17 09:40 Starting backup (INCOMING)
06-17 09:40 Backing up (2 SMS, 0 MMS, 0 call log)
06-17 09:41 Backup finished
06-17 10:08 Backup requested (incoming)
06-17 10:08 Starting backup (INCOMING)
06-17 10:08 Backing up (4 SMS, 0 MMS, 0 call log)
06-17 10:09 Backup requested (incoming)
06-17 10:09 Skipped because backup already running
06-17 10:09 Backup finished
06-17 10:13 Backup requested (incoming)
06-17 10:13 Starting backup (INCOMING)
06-17 10:13 Backing up (2 SMS, 0 MMS, 1 call log)
06-17 10:15 Backup finished
06-17 10:34 Backup requested (incoming)
06-17 10:34 Starting backup (INCOMING)
06-17 10:34 Backing up (3 SMS, 0 MMS, 0 call log)
06-17 10:35 Backing up (3 SMS, 0 MMS, 0 call log)
06-17 10:35 Backup finished
06-17 10:40 Backup requested (incoming)
06-17 10:40 Starting backup (INCOMING)
06-17 10:40 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 10:40 Backup finished
06-17 11:44 Backup requested (incoming)
06-17 11:44 Starting backup (INCOMING)
06-17 11:44 Backing up (8 SMS, 0 MMS, 0 call log)
06-17 11:44 Backing up (8 SMS, 0 MMS, 0 call log)
06-17 11:44 Backup finished
06-17 11:45 Backup requested (incoming)
06-17 11:45 Starting backup (INCOMING)
06-17 11:45 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 11:45 Backup finished
06-17 11:45 Backup requested (incoming)
06-17 11:45 Starting backup (INCOMING)
06-17 11:45 Skipped (no items found)
06-17 11:45 Backup finished
06-17 11:46 Backup requested (incoming)
06-17 11:46 Starting backup (INCOMING)
06-17 11:46 Skipped (no items found)
06-17 11:46 Backup finished
06-17 11:46 Backup requested (incoming)
06-17 11:46 Starting backup (INCOMING)
06-17 11:46 Backing up (1 SMS, 0 MMS, 0 call log)
06-17 11:47 Backup finished
06-17 11:50 Backup requested (incoming)
06-17 11:50 Starting backup (INCOMING)
06-17 11:50 Backing up (3 SMS, 0 MMS, 0 call log)
06-17 11:51 Backup finished
06-17 11:54 Backup requested (incoming)
06-17 11:54 Starting backup (INCOMING)
06-17 11:54 Backing up (3 SMS, 0 MMS, 0 call log)
06-17 11:54 Backup finished
06-17 11:54 Backup requested (incoming)
06-17 11:54 Starting backup (INCOMING)
06-17 11:54 Skipped (no items found)
06-17 11:54 Backup finished
06-17 13:39 Backup requested (incoming)
06-17 13:39 Starting backup (INCOMING)
06-17 13:39 Backing up (1 SMS, 0 MMS, 1 call log)
06-17 13:40 Backing up (1 SMS, 0 MMS, 1 call log)
06-17 13:40 Backup finished
06-17 16:15 Backup requested (incoming)
06-17 16:15 Starting backup (INCOMING)
06-17 16:15 Backing up (1 SMS, 0 MMS, 1 call log)
06-17 16:15 Backing up (1 SMS, 0 MMS, 1 call log)
06-17 16:15 Backup finished
06-17 18:01 Backup requested (incoming)
06-17 18:01 Starting backup (INCOMING)
06-17 18:01 Backing up (1 SMS, 0 MMS, 2 call log)
06-17 18:01 Backing up (1 SMS, 0 MMS, 2 call log)
06-17 18:02 Backup finished
06-18 07:47 Backup requested (regular)
06-18 07:47 Starting backup (REGULAR)
06-18 07:47 Backing up (2 SMS, 0 MMS, 1 call log)
06-18 07:47 Backing up (2 SMS, 0 MMS, 1 call log)
06-18 07:48 Backup finished
06-18 07:48 Next backup scheduled for: 09:48
06-18 09:27 Backup requested (incoming)
06-18 09:27 Starting backup (INCOMING)
06-18 09:27 Backup requested (incoming)
06-18 09:27 Starting backup (INCOMING)
06-18 09:27 Backing up (11 SMS, 0 MMS, 1 call log)
06-18 09:27 Backing up (11 SMS, 0 MMS, 1 call log)
06-18 09:27 Backing up (11 SMS, 0 MMS, 1 call log)
06-18 09:27 Backing up (11 SMS, 0 MMS, 1 call log)
06-18 09:27 Backup requested (incoming)
06-18 09:27 Skipped because backup already running
06-18 09:28 Backup requested (incoming)
06-18 09:28 Skipped because backup already running
06-18 09:28 Backup finished
06-18 09:28 Backup requested (incoming)
06-18 09:28 Starting backup (INCOMING)
06-18 09:28 Backing up (0 SMS, 0 MMS, 1 call log)
06-18 09:28 Backup finished
06-18 09:28 Backup requested (incoming)
06-18 09:28 Starting backup (INCOMING)
06-18 09:28 Backing up (0 SMS, 0 MMS, 1 call log)
06-18 09:28 Backup finished
06-18 09:29 Backup requested (incoming)
06-18 09:29 Starting backup (INCOMING)
06-18 09:29 Backing up (0 SMS, 0 MMS, 1 call log)
06-18 09:29 Backup finished
06-18 09:29 Backup requested (incoming)
06-18 09:29 Starting backup (INCOMING)
06-18 09:29 Backing up (0 SMS, 0 MMS, 1 call log)
06-18 09:29 Backup finished
06-18 09:34 Backup requested (incoming)
06-18 09:34 Starting backup (INCOMING)
06-18 09:34 Backing up (1 SMS, 0 MMS, 1 call log)
06-18 09:34 Backup finished
06-18 09:48 Backup requested (regular)
06-18 09:48 Starting backup (REGULAR)
06-18 09:48 Backing up (0 SMS, 0 MMS, 1 call log)
06-18 09:48 Backup finished
06-18 09:48 Next backup scheduled for: 11:48
06-18 10:49 Backup requested (incoming)
06-18 10:49 Starting backup (INCOMING)
06-18 10:49 Backing up (2 SMS, 0 MMS, 2 call log)
06-18 10:49 Backing up (2 SMS, 0 MMS, 2 call log)
06-18 10:49 Backup finished
06-18 10:52 Backup requested (incoming)
06-18 10:53 Starting backup (INCOMING)
06-18 10:53 Backing up (1 SMS, 0 MMS, 0 call log)
06-18 10:53 Backup finished
06-18 11:10 Backup requested (incoming)
06-18 11:10 Starting backup (INCOMING)
06-18 11:10 Backing up (2 SMS, 0 MMS, 0 call log)
06-18 11:10 Backup finished
06-18 11:21 Backup requested (incoming)
06-18 11:21 Starting backup (INCOMING)
06-18 11:21 Backing up (8 SMS, 0 MMS, 0 call log)
06-18 11:22 Backup requested (incoming)
06-18 11:22 Skipped because backup already running
06-18 11:22 Backup requested (incoming)
06-18 11:22 Skipped because backup already running
06-18 11:22 Backup finished
06-18 11:22 Backup requested (incoming)
06-18 11:22 Starting backup (INCOMING)
06-18 11:22 Skipped (no items found)
06-18 11:22 Backup finished
06-18 11:26 Backup requested (incoming)
06-18 11:26 Starting backup (INCOMING)
06-18 11:26 Backing up (1 SMS, 0 MMS, 0 call log)
06-18 11:26 Backup finished
06-18 11:48 Backup requested (regular)
06-18 11:48 Starting backup (REGULAR)
06-18 11:48 Skipped (no items found)
06-18 11:48 Backup finished
06-18 11:48 Next backup scheduled for: 13:48
06-18 13:22 Backup requested (incoming)
06-18 13:22 Starting backup (INCOMING)
06-18 13:22 Backing up (3 SMS, 0 MMS, 0 call log)
06-18 13:22 Backing up (3 SMS, 0 MMS, 0 call log)
06-18 13:23 Backup finished
06-18 13:23 Backup requested (incoming)
06-18 13:23 Starting backup (INCOMING)
06-18 13:23 Skipped (no items found)
06-18 13:23 Backup finished
06-18 13:24 Backup requested (incoming)
06-18 13:24 Starting backup (INCOMING)
06-18 13:24 Skipped (no items found)
06-18 13:24 Backup finished
06-18 13:48 Backup requested (regular)
06-18 13:48 Starting backup (REGULAR)
06-18 13:48 Skipped (no items found)
06-18 13:48 Backup finished
06-18 13:48 Next backup scheduled for: 15:48
06-18 13:54 Backup requested (incoming)
06-18 13:57 Starting backup (INCOMING)
06-18 13:57 Backing up (1 SMS, 0 MMS, 0 call log)
06-18 13:58 Backup finished
06-18 14:22 Backup requested (incoming)
06-18 14:22 Starting backup (INCOMING)
06-18 14:22 Backing up (3 SMS, 0 MMS, 0 call log)
06-18 14:22 Backing up (3 SMS, 0 MMS, 0 call log)
06-18 14:23 Backup finished
06-18 14:27 Backup requested (incoming)
06-18 14:28 Starting backup (INCOMING)
06-18 14:29 Backing up (2 SMS, 0 MMS, 0 call log)
06-18 14:29 Backup finished
06-18 14:30 Backup requested (incoming)
06-18 14:30 Starting backup (INCOMING)
06-18 14:30 Backing up (2 SMS, 0 MMS, 0 call log)
06-18 14:30 Backup finished
06-18 14:32 Backup requested (incoming)
06-18 14:32 Starting backup (INCOMING)
06-18 14:32 Backing up (2 SMS, 0 MMS, 0 call log)
06-18 14:32 Backup finished
06-18 14:33 Backup requested (incoming)
06-18 14:33 Starting backup (INCOMING)
06-18 14:33 Skipped (no items found)
06-18 14:33 Backup finished
06-18 15:12 Backup requested (regular)
06-18 15:12 Starting backup (REGULAR)
06-18 15:12 Skipped (no items found)
06-18 15:12 Backup finished
06-18 15:12 Next backup scheduled for: 17:12
06-18 15:51 Backup requested (incoming)
06-18 15:51 Starting backup (INCOMING)
06-18 15:51 Backing up (1 SMS, 0 MMS, 0 call log)
06-18 15:51 Backing up (1 SMS, 0 MMS, 0 call log)
06-18 15:51 Backup finished

**Comment by jcbeck** [comment]
Version of SMS Backup Plus: 1.5.8.
Phone: HTC6500LVW
Carrier: Verizon
Android Version: 5.0.2
Software Number: 6.22.605.3

**Comment by jberkel** [comment]
I would not recommend restoring 30000 messages. As it is, SMS Backup+ cannot reliably handle that amount of messages since gmail will very likely time out at some point, and there's no concept of resuming a restore operation.

Do you really need to restore all of them to your phone? Another approach would be to only restore the last X messages. Here's an explanation how you could do this: 

https://github.com/jberkel/sms-backup-plus#how-do-i-restore-the-last-n-weeks--n-messages

**Comment by angryziber** [comment]
Same here, 15983 messages and restore skips the last year of messages.
Maybe it makes sense to restore messages in the opposite order? I.e. starting with the most recent ones?
Or maybe there could be an option in the UI specifying a date or number of most recent messages to restore?

**Comment by jberkel** [comment]
Addressed in #586
