### ISSUE TITLE
OAuth1 token migration does not work

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#568]
From #554, @drHeimskirk 

Sorry to add to a closed bug but just wanted to give you some more information.
The 1.5.9 update finally made it to Google play and I updated today.

I could still not do a backup.

The logcat shows the following...
06-27 19:31:19.552 757 1408 W SMSBackup+: invalid response from server: HTTP/1.1 400 Bad Request
06-27 19:31:19.552 757 1408 W SMSBackup+: did not get a refresh token

This is on Android 2.2.

Is there something else that I should try or should I attempt the steps mentioned above to get things back on track.

**Comment by jberkel** [comment]
@drHeimskirk this is very likely the OAuth1->OAuth2 migration not working as expected. I could never test it since there is no way to get old OAuth1 tokens which can be migrated. If you don't mind I can send you a version which has some more debug logging enabled. Don't disconnect the account for now otherwise the token will  get lost. Could you also post the lines preceding the output you posted ? does it mention token migration somewhere?

**Comment by drHeimskirk** [comment]
Here is all of the data from the logcat from the start intent.  It does not show anything about token migration....

06-27 19:31:08.892   145   145 I ActivityManager: Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.zegoggles.smssync/.activity.MainActivity }
06-27 19:31:09.012   124   124 D AK8973  : Compass Start
06-27 19:31:09.012   145   453 D Sensors : open_akm, fd=128
06-27 19:31:09.272   254   254 W Rosie   : mAddHtcWidgetByOtherActivity = false, mIsOpenSlideWhenLeaveLaunch = true
06-27 19:31:09.282   757   757 D SMSBackup+: onResume()
06-27 19:31:09.442   145   237 D SurfaceFlinger: Layer::setBuffers(this=0x4c1870), pid=757, w=480, h=800
06-27 19:31:09.442   145   237 D SurfaceFlinger: Layer::setBuffers(this=0x4c1870), pid=757, w=480, h=800
06-27 19:31:09.542   646   901 D Finsky  : [27] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:09.572   646   655 D Finsky  : [7] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:09.592   145   885 D SurfaceFlinger: Layer::requestBuffer(this=0x4c1870), index=0, pid=757, w=480, h=800 success
06-27 19:31:09.612   646   653 D Finsky  : [6] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:09.642   145   238 D SurfaceFlinger: Layer::requestBuffer(this=0x4c1870), index=1, pid=757, w=480, h=800 success
06-27 19:31:09.642   646   653 D Finsky  : [6] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:09.662   646   901 D Finsky  : [27] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:09.682   646   901 D Finsky  : [27] InAppBillingUtils.pickAccount: com.zegoggles.smssync: Account determined from installer data - [jX4ipPz84ymQn1hX0hC647FoUrI]
06-27 19:31:13.892   757  1408 I global  : Default buffer size used in BufferedReader constructor. It would be better to be explicit if an 8k-char buffer is required.
06-27 19:31:14.802   646   646 D dalvikvm: GC_EXPLICIT freed 2307 objects / 125680 bytes in 98ms
06-27 19:31:16.722   757  1408 D dalvikvm: GC_FOR_MALLOC freed 7050 objects / 430184 bytes in 40ms
06-27 19:31:16.722   757   758 D NativeCrypto: Freeing OpenSSL session
06-27 19:31:19.552   757  1408 W SMSBackup+: invalid response from server: HTTP/1.1 400 Bad Request
06-27 19:31:19.552   757  1408 W SMSBackup+: did not get a refresh token

I am happy to test a debug version for you.

**Comment by drHeimskirk** [comment]
@jberkel 
I was just wondering if you have any plans for this in the near future and if you still want me to test it.
If it is a low priority for you and won't happen soon, I will do the steps mentioned in the other thread to get things back on track.

Thanks for a great product.
