### ISSUE TITLE
iphone version ?

### ISSUE THREAD

**Issue by terchris** [jberkel/sms-backup-plus#569]
Hi
First of all, thanks for a really useful product. I have been using it for years.
I got a new iphone and I´m trying to get my favorite apps on it. I have searched, but have not found SMS Backup+. Does it exist for iphone ?

**Comment by artjas** [comment]
Technically impossible, there is no API in IOS to read/write SMS.

**Comment by jberkel** [comment]
what would be technically be possible is to build a  tool which would read from the iphone backups, this would have to run on OSX.

i think there are already a few tools out there which do that, but AFAIK none them write the data to gmail  / IMAP in the way SMS Backup does. 

@terchris Is that something you would use?

**Comment by artjas** [comment]
@jberkel I already wrote an android app which parse iPhone backup file and insert SMS to android directly, I can give my source/help to write if needed.

**Comment by jberkel** [comment]
@artjas thanks. don't have plans to publish anything like that at the moment, but have an iphone so it might happen at some point. Are the existing iphone SMS backup tools any good?

**Comment by artjas** [comment]
@jberkel not really, I haven't find anything useful, due to lack of API it's not possible to build something easy and flexible, also I had a problem with importing sms from android to ios using backup file, it was not possible because Apple backup tool detected my backup file is modified and refused to restore

**Comment by 4ourbit** [comment]
there is a [text message forwarding option](https://support.apple.com/en-us/HT204681) but I couldn't figure it out yet how customizable that is to somehow redirect SMS to gmail.

**Comment by terchris** [comment]
Thanks for replying @jberkel @artjas @4ourbit I have been traveling and not been able to reply.
I think that if a tool like sms-backup is going to work then it must be automatic and reliable. I like the way it works on android. I install it and it does what it is supposed to.

**Comment by jberkel** [comment]
out of scope, closing.
