### ISSUE TITLE
Backup not working

### ISSUE THREAD

**Issue by looya** [jberkel/sms-backup-plus#575]
I am in China, and I've use this app for many years but since the OAuth problem it never worked again.

At first it says that OAuth is not supported, I read in Chinese forums that using IMAP and other email accounts can solve this problem. I still wanted to use Gmail so I postponed this issue.

Today I tried again and I find that this app is not working at all. I pressed the backup button but nothing seems to be happening, not even an error message showed up.

I checked the logs and nothing new has been logged today.

I suppose China's great fire wall could have something to do with my problem. But I am using VPN and I can connect to Gmail and other Google services.

**SMS Backup+ v1.5.9**

Using on **Samsung Galaxy Note3 SM-N9008V** (g-apps installed)
**Android Version 4.3**

**Comment by jberkel** [comment]
Sorry, I need logs to be able to debug this. Closing for now.
