### ISSUE TITLE
How to read sms backed up texts on PC

### ISSUE THREAD

**Issue by aishayeoh** [jberkel/sms-backup-plus#576]
Hi, I am new to all this. My android phone cracked (black screen, not usable) and I am not able to fix or replace it right now, but I desperately need to access some text msgs from that phone. I'm wondering if I can log into my Gmail account on my PC and read the backed up text messages on the PC? Thanks.

**Comment by dg4u** [comment]
You would only be able to access those text messages which were successfully backed up to your gmail account before the phone stopped working. They are usually saved with a label of "SMS" applied to them, but if you don't have that label in your gmail then you could search for them in "All Mail".
