### ISSUE TITLE
No backup for almost 2 months

### ISSUE THREAD

**Issue by jdghub** [jberkel/sms-backup-plus#578]
FYI: Just noticed that 1.5.9 hadn't backed up anything since May 5. Can't find any change at that time to explain it. Enabled log file, but manual backup did nothing (no "Working...", no log file, nothing sent).

Eventually uninstalled 1.5.9 and installed 1.5.8. It ran fine, though I only got about half of the 3800 emails it said it was sending. Installed 1.5.9 again and it is now working.

Very strange...

**Comment by jberkel** [comment]
will be fixed with #572
