### ISSUE TITLE
Sent MMS to unsaved contact not getting saved into conversation thread

### ISSUE THREAD

**Issue by tkalus** [jberkel/sms-backup-plus#579]
When I send a MMS message to a phone number not in my address book, the sent message (and attached picture) is saved in a different thread in gmail. It appears an issue with the `X-smssync-address` header and subsequently the generated subject. Only for MMS messages that I send to a phone number that is not in my Contacts, the header is set to my phone number and the Subject is set to my name. 

I suspect this [block of code](https://github.com/jberkel/sms-backup-plus/blob/master/src/main/java/com/zegoggles/smssync/mail/MmsSupport.java#L91-L102) is the root of the issue.

For sent SMS messages sent to and SMS & MMS messages received from unsaved numbers, the email message threading is as expected.

Moto G (with 4G/Gen1) with Android 5.1.

**Comment by dg4u** [comment]
This seems to be the same issues as #390 which as gone unaddressed since 2013-11.

**Comment by jberkel** [comment]
Closing as dup of #390
