### ISSUE TITLE
SMS Backup+ needs a new logo/app icon!

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#580]
I received an email from the Google Play Store team, telling me they decided to take down the app:

>We reviewed SMS Backup +, for package ID com.zegoggles.smssync, and found that it violates our intellectual property policy. The application has been removed from Google Play and won’t be available to users until you submit a compliant update. You can read more about intellectual property and our other policy guidelines in our help center.

While not explicitly stated it is very likely because of the fact that the current icon reuses graphics from Google's Gmail / Messages apps. However the same icon has been in use four more than four years so it's a mystery to me why they decided to take down the app now.

It'd like to use this issue as a call for proposals / discussion to decide on the next logo.

To start things off, here are two concepts by the designer of the current icon, Shimon Simon:

![sms_512_2015a_2_scaled](https://cloud.githubusercontent.com/assets/18891/9090478/57e32dec-3b92-11e5-8f80-b05df03b74ba.png)
![sms_512_2015b_2_scaled](https://cloud.githubusercontent.com/assets/18891/9090481/5963721c-3b92-11e5-834f-388881fcaa89.png)

**Comment by tylerstyle** [comment]
I like the second one better then the first, but would personally like a more slimmed down Material Design inspired icon more.

**Comment by jberkel** [comment]
[Material design icon style guidelines](http://www.google.com/design/spec/style/icons.html)

>Product icon design is inspired by the tactile and physical quality of material. Each icon is cut, folded, and lit as paper would be, but represented by simple graphic elements. The quality of the material is sturdy, with clean folds and crisp edges. The matte-like finish interacts with light through subtle highlights and consistent shadows.

**Comment by tylerstyle** [comment]
Yep. That's it.
Problem I see with these two Icons is, that they look cluttered. There's too much in them.
When you scale them down to the size they will occupy on a smartphone screen they just don't look that good.

**Comment by meksone** [comment]
Hi, I really like your app, and I'm sorry for this problem with Google. I would be very pleased to submit an alternative icon for the app, if you like... here's a sample :)

Bye, and thanks for this great piece of software!


![SMSBackup+ Test Icon](http://www.meksone.com/www.meksone.com/sharing/smsbackup_test01.PNG)

**Comment by McoreD** [comment]
That's not right at all! Jan, all the best with getting it back on Play Store!

**Comment by jberkel** [comment]
shimon's updates based on feedback:

![sms_512_2015d_r](https://cloud.githubusercontent.com/assets/18891/9132426/61e4eaec-3ceb-11e5-8a14-058f3d4923e4.png)
![sms_512_2015c_r](https://cloud.githubusercontent.com/assets/18891/9132431/6b57e67e-3ceb-11e5-85e5-932d5a9dad7f.png)

**Comment by Damounet** [comment]
I Like the first one, remidns me fo the old icon :)

**Comment by tylerstyle** [comment]
The second one is good!

The first one wouldn't look good when placed on a dark background.

**Comment by abandon42** [comment]
Signed up just to thank you for your work on this app. This response from Google is very disappointing - they could have easily requested that you change it by a certain date rather than just pulling you from the store.

**Comment by g-reno** [comment]
I think you should quickly resubmit your apk with any plain icon to make sure it is the icon that is the problem.  If they accept it then go for fancy icon.  Plus SB+ will be back up while new icon is in progress.

**Comment by Gargarospo** [comment]
Thank you jberkel for your great job here. ImI subscribed to GitHub to show support to jberkel. I also couldn't find SMS Backup+ on Google Play, but I could download it from F-Droid. In fact I'm going to stick to F-Droid much more than in the past.

**Comment by x61** [comment]
I went <b>crazy</b> when I searched the google play store for "SMS backup +", after installing a new ROM, and saw a bunch of <i> other </i>sms backup apps but yours was not in the list. I agree with others that you resubmit the app asap. Thank for posting the apk file.

**Comment by abandon42** [comment]
Agreed, being in the store with any icon is better than finding perfection.

Jan does this for free so he probably has other priorities :)

**Comment by airwa1kin7** [comment]
Looking forward to your re-submit of the app. I too freaked out when installing other ROMS and didn't see you app in the store. Lucky I had a backup still.
I like the second icon in your first post.

**Comment by WebDave** [comment]
First of all - thanks for creating this app. I've tried many out there (including the other most popular ones), and they don't compare to yours.

I'd like to suggest the logo be more representative of the distinguishing feature of your app. 

That is, SMS to email chain. As you know, others are inferior in that they simply allow an PDF of SMS to be backed up, or send and email with texts from everyone in one email, etc. Your's allows one to use the power of Gmail to search for specific threads. It's fare more useful when searching through backed-up SMS.

The proposed logos you displayed don't represent anything distinguishing about your excellent app, and they look generic. I suggest a logo that represents SMS 2 Email Chain, with "email" and "chain" represented graphically. I'm sure now many people are searching for your app on Play, as I was when I switched phones, and their search might be hampered a bit by a name change. However, changing the name to SMS 2 Email Chain would allow people to more easily understand the core strength of the app. Further, a name change would allow for your avid online following to virally announce a name change and the reappearance of your app on Play - and that could boost the app's popularity.

If you are interested, I am available to discuss any of these ideas.

Thanks again, your app has been of great use.

**Comment by frozenfire20** [comment]
I also signed up just to comment. I love you app and was stunned to find it missing! I'm very grateful you are working to get it available again. https://cloud.githubusercontent.com/assets/18891/9132431/6b57e67e-3ceb-11e5-85e5-932d5a9dad7f.png  <That's the icon I like the best so far. 

But might I suggest making the blue message block into a green one, to harken back to your original icon? When I went looking for it, the green message in an envelope was what I hunted for first, and only after I didn't see it did I go looking for the exact name of the app. That and the + sign were what I remembered most. 

I needed this to backup my broken phone, and now that I know you are working on it I will wait so I can use this again. Thank you so much for keeping it going! It's an awesome app!

**Comment by krueger80** [comment]
I prefer the first icon of your last post @jberkel . But I would put a little bit more details around the flap where it fold. Maybe have the flap just a little bit folded forward with a bit of shadow effect. Go material design for sure :)

Thanks for having maintained this app all those years!

**Comment by DevanWright** [comment]
Same as x61, I was losing my mind trying to find your app after installing a new rom. It's absurd that they would entirely pull you off Google Play. At least leave a placeholder telling everyone it is temporarily not available. Thank you so much for the app and all your work. It is seriously appreciated. As for the icon, I would choose the second icon in Shimon's second redesign.

**Comment by Gargarospo** [comment]
Downloaded and installed, nice job!
I hope that Google people give up kicking up a fuss.

**Comment by jberkel** [comment]
app is back in play store, with this icon

![sms_192x192](https://cloud.githubusercontent.com/assets/18891/9401196/a4845654-4799-11e5-8cf9-7cec040423c8.png)
