### ISSUE TITLE
How to backup android data to computer?

### ISSUE THREAD

**Issue by eveeve** [jberkel/sms-backup-plus#581]
There are many android phone users, and you would save some important files on it, like sms, contacts, photos, etc. To avoid losing them by accident, we should backup them to computer timely.

Coolmuster Android Assistant could backup android phone data to computer easily.

Step 1:Connect Android Phone to pc
The first thing you need to do is to download and install the Android file manager on your pc and launch it. The next is connecting your Android phone to pc via usb cable. Your device will appear on the screen. The manager would recognise your android device automatically.

Notice: If this is the you cannecting android phone to the problem on computer, you should enbale USB debugging first, and install a USB driver on your computer, then the app would detect your android phone automatically.

Step 2:Select Data and Start Export
You can find many icon on the top, find the one you need and click it, you can preview the file on your phone, then select and check you want to transfer, at last click "Export" to start the work. 

That's all! We can use Coolmuster Android Assistant to move almost everything from android phone to computer, and we can also use it to manage apps, contacts on computer, have a try!
http://download.cnet.com/Coolmuster-Android-Assistant/3000-18511_4-76035854.html
http://www.coolmuster.com/android/android-file-transfer.html

**Comment by Gargarospo** [comment]
This doesn't look to me an issue about SMS Backup+, so I would remove it.

**Comment by dg4u** [comment]
Yes, it looks more like a feature request than a bug report.

**Comment by jberkel** [comment]
unrelated to app, closing
