### ISSUE TITLE
New SMS Backup Plus - download link please

### ISSUE THREAD

**Issue by Colettes77** [jberkel/sms-backup-plus#582]
Hi
I have been a happy user of your SMS Backup Plus for quite some time.  Thank you for the work that has gone into the app.  It has never failed me.  

I have just purchased a new (stop gap) Windows phone - and am desperate to access /restore my safely backed up sms and contact info.  Is there a new link to the app?  I tried the f-droid link and the apk link but every road took me back to the Play Store which as per your post re the logo, is not currently making your product available.

I guess a link to making a donation for your app would be good too.  I have enjoyed this app for free for too long!

Many thanks

Colette

**Comment by jberkel** [comment]
dup of #580
