### ISSUE TITLE
mms restore - why can't i restore them to a new device ?

### ISSUE THREAD

**Issue by advissan** [jberkel/sms-backup-plus#583]
great app ! But i have a problem: i've backed up all my sms and mms from my telephne (glaxy 2) and i can see the full back up in my gmail account. 

However when i restore my sms and mms to my new telephone (lg 2) all the long sms (that are like mms) are not restored - WHY ??

Is there a bug restoring mms ??? Will this bug will be fixed ???

**Comment by dg4u** [comment]
This may be related to issue #390 (with problematic code identified by tkalus in #579).

**Comment by psykauze** [comment]
I'm not sure that is what he expect. I think he just want to restore his previously backed up MMS.

This fonctionnality is not yet implemented due, in part, to some issues to backing up MMS I guess.

**Comment by jberkel** [comment]
MMS restore is not supported
