### ISSUE TITLE
STARTSSL support ?

### ISSUE THREAD

**Issue by lakano** [jberkel/sms-backup-plus#587]
Hello,

Your app seems really useful, but I can't connect to my server because it's STARTSSL protocol (it's the replacement since many years for the deprecated SSL/TLS protocols)

Is it possible to have this support please? 

Regards,

**Comment by jberkel** [comment]
good point. since K-9 is used internally for IMAP handling this should already be supported and just needs to be added to the config options (i think).

**Comment by lakano** [comment]
Good to heard :+1:

**Comment by jberkel** [comment]
sorry, I misunderstood your report. what's STARTSSL protocol? do you mean STARTTLS by any chance? that should already work, with the TLS setting.

**Comment by lakano** [comment]
Oups ! Yes, I would mean STARTTLS, sorry ^^

Ok, I''l try, thanks :)
