### ISSUE TITLE
Backed up messages no longer show as "Sent" in gmail.

### ISSUE THREAD

**Issue by dg4u** [jberkel/sms-backup-plus#588]
I just noticed a new problem: after August 22 none of the backed up SMS messages which I sent are no longer showing in "Sent Mail". 

When I select "Show Original" in gmail for the last message that worked, on August 22, it says "X-smssync-version: 1553". The first message that didn't work, sent on August 25 says "X-smssync-version: 1554". Both messages show the exact same From address, my correct gmail address.

MMS messages haven't been showing up in "Sent Mail" since 2014-05-24, but that's because the To and From fields are all messed up. See issue #390.

**Comment by jberkel** [comment]
this might be related to a change in gmail. i'm not exactly sure how they decided when to show messages, under which labels.

**Comment by dg4u** [comment]
Gmail stores all mail in one stream and then filters "into" various views called labels. The "Sent Mail" label is applied to any messages with From: = your own email address. I am looking into the possibility that something has changes in the way they assign this system label. Reference: http://gmail-tips.blogspot.com/2013/05/managing-sent-mail.html

On the other hand, it is very curious that "Sent mail" assignment worked fine with "X-smssync-version: 1553" but stopped working with "X-smssync-version: 1554". What changed?

**Comment by jberkel** [comment]
Don't think they should show up in "Sent" at all, since they are not really sent messages. Maybe you can do something with gmail filters?
