### ISSUE TITLE
Each time SMS Backup+ is updated, causing Textra to generate MMS error

### ISSUE THREAD

**Issue by weslum** [jberkel/sms-backup-plus#590]
Each time SMS Backup+ is updated automatically and there's a "what's new" popup in SMS Backup+.  This popup seems to cause Textra to generate an error about MMS.  I have to go into SMS Backup+ and close the "What's new" popup, and then Textra will work.  Textra states that this is not something they can fix, but rather something wrong with another application (in this case SMS Backup+).   Seems like that popup is causing SMS Backup+ to put a lock on something that is needed for texting.

I'm using SMS Backup+ 1.5.10 and Android 5.1.1 (Nexus 6).

**Comment by jberkel** [comment]
Sorry, the popup is just informational, don't see how this would interfere with Textra.
