### ISSUE TITLE
Doesn't back up SMS sent via Google Voice

### ISSUE THREAD

**Issue by DPLaC** [jberkel/sms-backup-plus#593]
Does not recognize SMS messages that I send via Google Voice through Google's Hangouts app — which, unfortunately, is the vast majority of SMS that I send/receive, because they're free through Google Voice but not directly through Verizon.

**Comment by dittaeva** [comment]
But does it backup sms sent with the Hangout app at all?

**Comment by jberkel** [comment]
Sorry, think this bypasses the android system, so can't be done.
