### ISSUE TITLE
Unquoted blank in local part of email address

### ISSUE THREAD

**Issue by uafr** [jberkel/sms-backup-plus#595]
My phone provider uses text containing a whitespace as SMS-sender.  Messages get backed up with these headers:
```    
...
From: SMS-Absender O2 <o2 Team@unknown.email>
...
X-smssync-address: o2 Team
X-smssync-datatype: SMS
...
```
Polling mails containing the created email address does not work
`fetchmail: SMTP error: 501 <o2 Team@unknown.email>: "@" or "." expected after "o2"`

Adding quotes around the local part or replacing the blank by an underscore should make the address valid. 

As workaround I added a syntactically correct email address to my address book. But that only works for known senders, so a real fix would be great.

**Comment by jberkel** [comment]
Can you try [1.5.11-BETA1](https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA1) ? should be fixed there.

**Comment by uafr** [comment]
With 1.5.11-BETA1 it works. Wow, that was fast. Thank you.
