### ISSUE TITLE
Doesn't restore all logs and messages

### ISSUE THREAD

**Issue by Ham3D** [jberkel/sms-backup-plus#596]
when i check my gmail all backups are there(untill today), but when i try to restore it only some of it got restored(after a long time counting from zero to 12K).
btw only mesages and logs older than 09/06/2014 are restored.
and i have sms backup + shows 12k messages and logs.

**Comment by gablabelle** [comment]
I have the same issue trying to restore after flashing marshmallow on my Nexus 5.

**Comment by jberkel** [comment]
there are some restore improvements done in the current beta beta (#586), maybe try with this version
https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA2

**Comment by gablabelle** [comment]
Great it worked. Thanks a lot!

**Comment by gablabelle** [comment]
@jberkel actually it seems to works but the dates are off ... Everything is good in Gmail but the dates and time are not good in Hangouts after Restoring.

Also when you do a Backup I can see that the time is not good in the app.

**Comment by kakawait** [comment]
Same issue even with latest release https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA3

**Comment by kurahaupo** [comment]
@gablabelle how far out at the timestamps? Could this be a matter of timezone slippage? Are the timestamps wrong by a whole number of hours, and off by no more than ±1 day?

**Comment by kurahaupo** [comment]
@Ham3D and @kakawait are you still having this problem?

**Comment by gablabelle** [comment]
@kurahaupo i’ve had about 5 phones since that nexus 5 lol ... Sorry i don’t remember how this ended for me.
