### ISSUE TITLE
How to recover lost android phone sms and contacts to computer?

### ISSUE THREAD

**Issue by eveeve** [jberkel/sms-backup-plus#597]
Lost text messages or your contacts list could be a disaster for some people. No one will deny the importance of the SMS and Contacts on your mobile phones. So once the disaster have happed, you'd better to look for a way to reduce your losses. Thus, Coolmuster Lab.Fone for Android could be a ideal program for your reference. It's very easy to use, you just need a few simple steps to recover your android phone sms and contacts to pc.

And you need to root your android phone at first, or the app can't detect your phone successfully. And stop saving new data to your phone, or the deleted data will be covered.

Step1: Connect android phone to pc and start the problem
At first, connect your phone to computer via USB cable, then start the app on your computer. Make sure your phone has been linked to computer correctly, or this data recovery problem couldn't detect it successfully.

Step2: Enable USB Debugging
You need to enable USB debugging on your device, then the data on your android phone will be synced to computer. And the problem will scan your device directly.And you just need to enable USB debugging for once.

Step3: Preview and Recover Messages
After the scan, you can preview all of your messages and contacts on an interface. And this problem could help you distinguish deleted messages with exsiting messages. Then you just need to select and check those you need to recover, and click "Recover" to save lost messages on your computer.

That's all!
http://www.transfer-motorola-recovery.com/how-to/how-to-recover-deleted-text-messages-from-android.html
http://www.android-sms-recovery.com/resources/recover-deleted-contacts-from-android-phone.html

**Comment by Poumccgg** [comment]
Phone contacts lost come from SIM Card or phone Internal Memory.So want to recover phone internal memory ,need to root phone .
Read guide from Samsung Data Recovery software.
http://www.samsung-recovery.net/resource/how-to-recover-deleted-contacts-from-android-phone.html
http://www.how-to-print-text-messages.com/android-message-recovery.html

**Comment by jberkel** [comment]
out of scope
