### ISSUE TITLE
Restore a period

### ISSUE THREAD

**Issue by waghanza** [jberkel/sms-backup-plus#602]
Hi,

I have about **40 000** SMS stored on my [Gmail](http://gmail.com).

It will take a long time to synchronize each, and I do **not need** to have all SMS on my phone.

Is there a way to synchronize a period, for example 

``` each sms since 4 months ```

Regards,

**Comment by jberkel** [comment]
not directly, but you can try
https://github.com/jberkel/sms-backup-plus#how-do-i-restore-the-last-n-weeks--n-messages

**Comment by omikyle** [comment]
HI there--- yes -- I would like to retrieve sms messages on GMAIL not on
the phone and would like to retrieve the last 6 months -- how is this done?
