### ISSUE TITLE
Restoration doesn't restore all messages, only some

### ISSUE THREAD

**Issue by samy** [jberkel/sms-backup-plus#603]
On a OnePlus Two, using Android 5.1.1, the restoration only restore some messages. For example, I have 34k SMS saved on Gmail (and the counter in the app says it restores X on 34k SMS).
But when I open the Messenger app after the end of the restoration, the messages received after mid-2014 are not displayed.

I tried many times, totally wiping the phone between each attempt : same result

**Comment by jberkel** [comment]
try the beta mentioned in #596
