### ISSUE TITLE
Messages restored partially i have android 5.1.1 on galaxy s5 tmobile

### ISSUE THREAD

**Issue by mknuman** [jberkel/sms-backup-plus#604]
I have all the messages restored but it cuts off on oct-4-2014 and then picks up on oct-3-2015 until present time so it's like got the time stamp chornology messed up. so i have about a year's worth of messages gone and i really need the last few months texts messages , they are really critical. Jan is there any way you can help me pleaseeeee

**Comment by jberkel** [comment]
do they show up in gmail, with the correct date?

**Comment by mknuman** [comment]
you mean the ones from 2014 that the backup thinks is 2015 or like the
actual backed up messages from for example sept 12 2015 ?

**Comment by omikyle** [comment]
-- Please help --- I can't get any past messages --- I did not back them up
ever until Oct 3 so can only retrieve Oct 3 to present -- How do I get the
older messages back and emailed to Gmail ---how is this done or even
possible --- thank you

**Comment by jberkel** [comment]
@mknuman the ones where it cuts off. just to double check that they exist on the server / gmail.

**Comment by mknuman** [comment]
I did Jan, they're still there that don't show up on the restored messages
on the phone. they are still here on GMAIL

**Comment by mknuman** [comment]
You figure out the issue?

**Comment by jberkel** [comment]
Do you get any error during the restore?

**Comment by mknuman** [comment]
no not at all, i've tried to restore several times and it cuts off oct 2014
=/

**Comment by jberkel** [comment]
you could try the latest beta which reverses the restore order and limits the number of messages restored: https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA2

**Comment by Careless** [comment]
The lastest version does not seem to restore anything for me. It just says "Calculating..." no matter the restoration size I select.

**Comment by jberkel** [comment]
@Careless how many messages do you have stored?

**Comment by Careless** [comment]
1428 threads x 100 sms per thread, so roughly 15,000. I am not trying to restore all of them. Just the last 500, 200, then 100. None seem to work.

I'm just playing around with my filters/labels right now and seeing if that is what the issue is.

**Comment by jberkel** [comment]
I suspect a timeout on the gmail side. I've seen this happen with lots of emails. Can you move the older emails to another folder? might help.

**Comment by Careless** [comment]
I'll give that a shot, but the most common bug I've found to date since I started using this app years ago is still there. If I choose to do a backup or a restore, and I rotate the screen or go to a different menu and come back, the status indicator/bar says "idle" with a green check mark icon, and shows no status bar animation, or message. Yet the notification bar says "calculating" and continues to show this, and I cannot get rid of it unless I kill the app.

I always kill the app and try to restore again, because I'm not sure if the notification is another bug, and it just doesn't want to go away, or if the app is actually doing something.

**Comment by Careless** [comment]
Ok, so I moved a lot of the convos to "Archived SMS" and then moved 50 threads back into "SMS" label and it is working now.

I will try the 500 item restoration next. 

If I keep doing 500 item restorations, does it keep appending 500 texts to the current ones that have been imported, or does it overwrite the 500 with the same messages?

**Comment by jberkel** [comment]
it should append

**Comment by mknuman** [comment]
Jan,

how many people are in this thread, i'm confused ?

my problem still persists. i have about 64,000 sms that have to be restored

**Comment by Careless** [comment]
nknuman, have you tried moving the sms threads that aren't restored to a new gmail label and then directing SMS Backup+ to restore from that new label only?
