### ISSUE TITLE
How to backup android phone contacts to computer?

### ISSUE THREAD

**Issue by eveevea** [jberkel/sms-backup-plus#605]
Want to copy android contacts to pc avoid losing them accidently? Puzzled in how to transfer contacts from android to pc? Well, try Coolmuster Android Assistant.

It's very easy, we just need 2 steps to finish the work:
Step 1:Connect Android Phone to pc
Download and install the Android contacts manager on your pc and launch it. The next is connect your Android phone to pc via usb cable. Your device will appear on the screen. The manager would recognise your android device automatically.

Notice: If this is the you connect android phone to the problem on computer, you should enbale USB debugging first, and install a USB driver on your computer, then the app would detect your android phone automatically.

Step 2:Select Contacts and Start Export

That's all!
http://www.android-sms-recovery.com/resources/backup-android-contacts-to-computer.html
http://www.cultofmac.com/390694/coolmuster-android-assistant-sponsored-post/

**Comment by Myutouuhh** [comment]
Samsung Assistant software is an almighty data managment tool that enable you to transfer contacts, messages, photos, videos, books, music, documents, apps Android phone to computer.
http://www.samsung-messages-backup.com/resources/transfer-contacts-from-android-phone-to-computer.html

**Comment by jberkel** [comment]
out of scope for this app

**Comment by Myutouuhh** [comment]
If you're an Android user thinking about backup android phone data. The good news is that Android Backup software can help backup contacts,messages,photos ,videos from android to computer . 
http://www.samsung-recovery.net/android-assistant/how-to-transfer-contacts-from-android-to-computer.html

**Comment by lucylla** [comment]
I happen to know an android backup app could transfer file between android and computer in few simple steps, you just need to connect your phone to computer, the app would detect your phone automatically.
[https://www.android-file-manager.com/resources/transfer-contacts-from-android-phone-to-computer.html](https://www.android-file-manager.com/resources/transfer-contacts-from-android-phone-to-computer.html)
