### ISSUE TITLE
"Error during backup/restore"

### ISSUE THREAD

**Issue by msao** [jberkel/sms-backup-plus#606]
I've successfully backcup my sms and call logs on a Samsung Galaxy S3 with Cyanogen Mod (now dead) and when trying to restore my backup on my new phone, an LG G3 with the stock rom, I get the attach error message and no messages are restored.
SMS backup+ version : 1.5.10
Android version : 5.0
Kerrnel version : 3.4.0
On a LG G3

![quickmemo _2015-10-23-14-08-23](https://cloud.githubusercontent.com/assets/15263794/10692352/459abe42-7991-11e5-8530-98d5e5d28765.png)

**Comment by jberkel** [comment]
looks like a backend issue.
