### ISSUE TITLE
Samsung s6 kills the service (Android marshmallow)

### ISSUE THREAD

**Issue by noodleflake** [jberkel/sms-backup-plus#608]
I think the new android release on samsung s6 kills the service. Please include an option im the app to monitor in foreground so that it can stay alive.

**Comment by jberkel** [comment]
Is this during restore?

**Comment by noodleflake** [comment]
No. Let me explain; It doesn't monitor the sms's for backup, it's almost like android detects the sms service as an unused application and hibernates it. If I open the application it works for a couple of days and then stops again until I open it again. I've seen a couple off android apps now do this where they allow you to run whatever monitoring in the foreground (in notification area) so that Android doesn't kill\hibernate it.

**Comment by jberkel** [comment]
Ah, this is with Marshmallow?. I think there's a whitelist feature now to allow apps to run longer, maybe try this.

**Comment by amandablum** [comment]
you can whitelist apps from the optimizer from the battery settings. However, it does not affect the automatic backup settings. It still doesn't update.

**Comment by jberkel** [comment]
Hm, I guess it's time to tackle https://github.com/jberkel/sms-backup-plus/issues/572

**Comment by amandablum** [comment]
I may be incorrect about what I said. While it did not immediately seem to work, I am now getting updates to SMS backup. The only other variable would be that I set a different backup scheme, going from daily to every 6 hours, wondering if doing so would reset it. 

To be specific about "whitelisting apps on marshmallow"  I assume we're talking about excluding them from optimization in Doze, correct? http://www.cnet.com/how-to/stop-specific-apps-from-using-doze-on-android-6-0-marshmallow/

**Comment by jberkel** [comment]
@amandablum correct. don't have a marshmallow device so can't test myself

**Comment by damitas** [comment]
HI there, its not just S6, I've got an S5 Neo running andriod 5.1.1 SMS Back-up stopped backing up a while ago (must have been after I updated Andriod) and I've just noticed.  Now I am unable to trigger the back-up manually, I get 'Error - unable to connect'

I moved SMS Backup+ to the 'disabled for' on the Smart manager along with Dropbox/facebook etc etc anything that runs in the background.  Don't think thats fixed anything!

**Comment by jberkel** [comment]
@damitas If it fails when running manually it must be a different issue at hand. Can you check the sync log, as explained here: https://github.com/jberkel/sms-backup-plus/#faq-general-file-bug-report?

**Comment by fkbreitl** [comment]
I had a similar issues of automatic backups stopping to work on my Samsung S4. It turned out that this was caused by the optimization of the new Smart Manager App which became active after the Android update from version 4 to 5.0.1. After disabling the optimization for SMS backup+ auto backups started working again.

**Comment by Behtaj** [comment]
Where can I find the Smart Manager App to disable optimization for SMS Backup + ?  I have a Note 3.

**Comment by fkbreitl** [comment]
Maybe the Samsung support page can show you:

http://www.samsung.com/us/support/search/?pageType=support&keyword=smart+manager

**Comment by Behtaj** [comment]
Thanks for the suggestion @fkbreitl, I had looked online and in my phone, but not this support page. The Samsung support page offers articles related to the Smart Manager for the S series devices, Notes 4, 5, and the Edge, but not the Note 3. It makes sense for the Note 3 not to have it. It came out before the S5.

On my phone, the last-backup-date is always in the future. So it never backs up. I've reinstalled several times over the past year. At first, it would correct the date and after a day or two, the future date problem would come again. It got worse over time. Now it gives a future date right after the initial backup.

@jberkel In #572  you added this to the 1.6.0 milestone on Jul 16, 2015. But the current version is still 1.5.10.  Was that a fix that didn't pan out?  You also mentioned that you don't have an android, I'm willing to devote whatever amount of time it takes to help from my end. I don't know much about Android phones, but I'm a system analyst so I can follow instructions well and get the logs you need plus give you good problem descriptions. Want to work with me?

**Comment by jberkel** [comment]
@Behtaj sorry work on that release has not started yet. i've been quite busy with an unrelated project but want to dedicate some time to SMS Backup+ soon. Thanks for your offer to help, I definitely need somebody who can test & provide logs for the new version. I'll update the issue once I start working on it, hopefully next month.

**Comment by Behtaj** [comment]
Thank you for your reply @jberkel. From reading the various posts about this problem, I'm under the impression that there were 2 workarounds. One was undoing Optimization via the Smart Manager which Note 3 is not included in. Is there anything I can do till 1.6.0 is out? If not, I would like to make a suggestion which is easily implementable, would help meanwhile and is a nice feature to have anyway.

After doing a reset (removing and putting back the Gmail address), the choices provided by SMS Backup+ are Backup All or none. If we have a choice to limit the backup to everything after a certain date, it would drop the amount of time this takes. For me its 10 hours vs 1 minute.

There are two types of users. Those who delete their text from their phone once backed up, and those who keep the texts handy on the phone to search like a database. This would improve things significantly for the 2nd group. A full backup for me takes about 10 hours right now.

Even after this problem is resolved, The option of a date criterion to limit the backup is a big advantage for the user.

**Comment by eole210** [comment]
Hi,
I don't have a Samsung but a Xiaomi Note 3 and have similar problem with SMS Backup+: works nicely for some time then, with no apparent reason, stops doing auto backup. Starting the app, forcing a manual backup, reloads the machine... for a couple of days. @fkbreitl suggested something very clever: checking performance and battery settings. In there (it is quite deep menus), there is a way to authorize SMS Backup+ not to be "optimized", but instead, allowed to run with **no restrictions**. My assumption is that from now on, no optimisation will occur and SMS Backup+ will be free to operate for ever.
Crossing fingers now, I'll be back in a few days with some feedback.
Thanks,
eole210

**Comment by Behtaj** [comment]
@jberkel how much longer before the backup problem is fixed? I reinstalled today, but the version is still 1.5.10.  

Looking at feedbacks I'm surprised that some people have no problem at all while me and many others can't get the App to do a basic backup. Only when I reinstall and do an initial backup, if I'm lucky it will do the whole backup without stopping in the middle. It takes over 10 hours. If it stops in the middle, I don't have a full backup, plus I have a bunch of duplicates, triplicates, up to 8 copies of the same sms in some cases. This is eating people's time. It's leaving a negative legacy. Please fix it asap. It's been over 2 years now.
Samsung Note3 
Software Version N900PVPUEPH1
Hardware Version N900P12
Model SM-N900P
Android Version 5.0
Kernel Version 3.3.0-4453878  dpi@SWDD6617 #1  Mon Aug 1 14:4651 KST 2016
Build number LRX21V.N900PVPUEPH1
Last check for updates on 1/9/17

**Comment by jberkel** [comment]
there's a new beta now which might improve the situation, see #572

**Comment by jberkel** [comment]
Closing as dup
