### ISSUE TITLE
how to sync android with pc?

### ISSUE THREAD

**Issue by eveeve** [jberkel/sms-backup-plus#609]
There are many android phone users, and you would save some important files on it, like sms, contacts, photos, etc. To avoid losing them by accident, we should backup them to computer timely.

Coolmuster Android Assistant could backup android phone data to computer easily.

Step 1:Connect Android Phone to pc
The first thing you need to do is to download and install the Android file manager on your pc and launch it. The next is connecting your Android phone to pc via usb cable. Your device will appear on the screen. The manager would recognise your android device automatically.

Notice: If this is the you cannecting android phone to the problem on computer, you should enbale USB debugging first, and install a USB driver on your computer, then the app would detect your android phone automatically.

Step 2:Select Data and Start Export

That's all! 

A wide range of Android brands are supported by this Android managing tool, including HTC, Samsung, Motorola, Sony, ZTE, LG, HUAWEI, Dell and many more.
http://www.transfer-motorola-recovery.com/how-to/backup-files-from-android-to-computer.html

**Comment by jberkel** [comment]
https://github.com/jberkel/sms-backup-plus#faq-can-you-add-feature-x
