### ISSUE TITLE
IO errors: SocketTimeOutException / Wifi

### ISSUE THREAD

**Issue by Tuinslak** [jberkel/sms-backup-plus#614]
Hey,

I've noticed my Nexus 6 stopped backing up for past ~2 weeks (since 6.x release?).

I've now moved to a N6P, and there I can't restore at all (IO errors).

While backing up the missing SMSes (and SMS Backup+ starting from scratch when I relinked my account), I've noticed a lot of error happen every so often: either Timeout issues (Android putting the app in sleep mode?) or IO errors. 

Log:

![screenshot_20151126-160938](https://cloud.githubusercontent.com/assets/306680/11425911/988edc32-9458-11e5-83fc-a7d19d833b64.png)

Any idea what might be the cause ?

Speed is also really slow and it seem to hang at the same sms number for minutes on end (why I requested a new backup while it was apparently still running).

**Comment by jberkel** [comment]
yes, it could be that the connection goes down. is this with wifi / 3G?

**Comment by Tuinslak** [comment]
It's on WiFi. Keeps happening almost all the time.

It's also not reliably backing up.

Seems android related ?

**Comment by jberkel** [comment]
The app acquires a Wifi lock to make sure the connection does not go away. Somehow this is not working correctly on your device. Not sure why.

**Comment by jberkel** [comment]
Closing as dup
