### ISSUE TITLE
SMS Backup+ restore some, dups the rest.

### ISSUE THREAD

**Issue by BenjiPDX** [jberkel/sms-backup-plus#616]
Hi everyone,

I'm brand new here so please forgive my [technical] ignorance or carelessness. I've used SMS Backup+ successfully in the past to transfer text from my HTC Evo 4G over to my HTC One M8 HK on Sprint network. My M8 was softbricked recently one day out of the blue while charging. I had to reset it by updating a different rom and flash the update via my laptop. Prior to that, I had no idea how any of that works. Since getting it back up, it has been working fine, but my SMS Backup+ is not able to restore my text messages properly. I have all my text messages backed up to Gmail and I can see "SMS" folder in my Gmail account and all my text, past and current are there, but the SMS app will not restore all of them. I have done this 3 times and it takes a long time to backup each time (about 6 hours or more) since I have over 46K+ messages. After the third time, I was more careful to see what happens and at the end right after it read through all 46K+ messages, it says something like (39,238 dups). I looked up what that could mean and it says that the app assumed that I have that many text on my phone as duplicates already so it didn't restore those, while only the older text messages got restored on my phone. But I do not have those messages on my phone. At the same time, my Google sync is having issue with syncing my [Google] Task app as well, so I am not sure if that is related to what is going on my the SMS Backup. I could really use some guidance on how to fix this.

Here are the software I'm running on:
Andrioid version: 5.0.2
HTC Sense version: 6.0
Software version 4.25.654.18
HTC SDK API Level: 6.55
More: Baseband, Kernel version, etc.
PRI Version: 2.62_003
PRL Version 55030

Thank you.

**Comment by genginator** [comment]
I am having the same problem.  I am trying to restore my SMS on my new Nexus 6P.  After running several Restores, each time receiving a small batch of messages, the app has stalled.  No messages after June 2014 are being restored.  When I run a Restore now, the app restores 0 messages and counts everything as duplicates.  I did try installing the beta released on Oct 7 per another thread.  Please advise.

**Comment by zachryzion** [comment]
I have 52480 items and I see restored up to ~45k restoration. I am trying for the third time. I just installed Cyanogen Mod 13 (Android Marshmallow) on OnePlus One. In both previous runs I have restored to only 4 Month back (Jan 7) SMS. Call logs are not restored at all.

**Comment by ypnos** [comment]
I have the same problem. I backupped about 5900 messages. I even went through them in Thunderbird and deleted some that I am not interested anymore. 5439 remained. When I wanted to restore on my new installation (Android 6.0 coming from 5.1), SMS Backup+ would first download all messages. It would then claim it restored a few hundreds and 5001 were duplicates.

It seems the restored messages were stored chronologically, so only messages **up to 2013** were actually restored.

In the settings, I set to restore only 500 messages. Now running Restore again, I got the **latest** 500 messages restored correctly and no dups.

The Call log however, didn't get restored in either run.

**Comment by jcrben** [comment]
Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta

> In the settings, I set to restore only 500 messages. Now running Restore again, I got the latest 500 messages restored correctly and no dups.

Good to hear that worked at least. I tend to just leave old messages in Gmail.

**Comment by mtuyamstuni** [comment]
can i comment on this if closed... this will find out...

**Comment by mtuyamstuni** [comment]
I have just installed sms backup+ and it appears to only backup a limited number of texts - just a few months worth in 2015! I have reset the limit from 500 (which i noticed in trying to solve this) and the group of contacts to frequent only, and now it responds by starting a backup, and diminishing the number 0/5,000 down to 0/ of nothing to backup... Any ideas?

**Comment by jammrellim** [comment]
Hi,
Could anyone advise about how to have all the same messages between the same two people tied together?
I understand there's a 100 message limit, but I'm seeing where many of the messages between me and a single recipient are coming in in counts of far less than 100. Ideally, all messages would be in order and linked up to 100 before another convo thread is started. On my phone it's just 2 people back and forth for years of texts. In Gmail it appears as 100 here, 5 there, 1 here, 3 there, 37 here, 100 there, and on and on randomly despite the same person, subject line, phone numbers, etc.
