### ISSUE TITLE
Incomplete SMS Backup

### ISSUE THREAD

**Issue by jewhedon** [jberkel/sms-backup-plus#617]
Tonight I installed the app and followed the directions.  I made sure IMAP was enabled in Gmail.  I have over 6000 SMS messages on my phone.  After backing up for several hours the app showed completed.  When I logged into Gmail only 85 messages are shown under the SMS tag.  Are the messages backed up in a different location or are they just not backed up at all.  

Phone:  Verizon Droid Turbo

**Comment by jberkel** [comment]
They might be threaded. Gmail shows messages differently.
