### ISSUE TITLE
Request: Support FreedomPop

### ISSUE THREAD

**Issue by JonnyTech** [jberkel/sms-backup-plus#618]
I recently switched to FreedomPop (uk.freedom pop.com) but messages must be sent from their messaging app (https://play.google.com/store/apps/details?id=com.freedompop.ott) Is it possible to support that app? The SQL databases are located at /data/data/com.freedompop.phone/databases
com.freedompop.phone.* and I can provide samples. Thanks.

**Comment by jberkel** [comment]
Sorry, no. https://github.com/jberkel/sms-backup-plus#faq-can-you-add-feature-x
