### ISSUE TITLE
Failure during MMS backup

### ISSUE THREAD

**Issue by jacimac** [jberkel/sms-backup-plus#625]
Hi,

During MMS backup, the login to my Gmail was lost (?!) - it was only about half way through.

After re-verifying my login, the app says that all backups are done, but the app itself shows that the last MMS was backed up as of Nov 7.

I can see some recent MMS files have been successfully backed up, but can't confirm that all have (the progress bar had it at around 1000/1700 when I last checked - yes, I know that's a lot of files, I've been looking for a way to move them off for awhile, and just came across this app last night).

Is there any way to force the MMS backup to happen, even though the app believes that all items are backed up, so that it can download any missing files?

Thanks!

Note: hitting the backup button only elicits the response that there are no items to backup.
![screenshot_2016-02-27-14-23-01](https://cloud.githubusercontent.com/assets/17520218/13375855/210ae920-dd60-11e5-85ed-eebe648b0173.png)

**Comment by jacimac** [comment]
bump

**Comment by jberkel** [comment]
https://github.com/jberkel/sms-backup-plus#faq-backup-reset
