### ISSUE TITLE
IO Error, underlying=java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by dianareider** [jberkel/sms-backup-plus#626]
I am able to back up as long as I keep the application open on the screen and keep the screen on. As soon as I turn the screen off or switch to another app, I receive the attached error. I have to kill the service and restart the app to transfer messages again.

I have pointed the backups to a new label and wiped data, but no luck. I am backing up to Gmail. Any suggestions or items to check?

Error: 
General error: IO Error (exception: com.fsck.k9.mail.MessagingException: IO Error, underlying=java.net.SocketTimeoutException: Read timed out)

![screenshot952016-03-03-19-53-23](https://cloud.githubusercontent.com/assets/17659472/13544054/2bb0d626-e226-11e5-9d72-cca685a8d357.png)

**Comment by jcrben** [comment]
@dianareider could you try out the beta and open a new issue if it doesn't work? https://github.com/jberkel/sms-backup-plus#beta

@jberkel given the age of this, if we don't hear back I think we should close it rather than letting it block 1.5.11

**Comment by dianareider** [comment]
Yep, unfortunately I stopped using sms backup because of this issue. I have a new phone now (Pixel) so may be a moot point.

**Comment by jcrben** [comment]
Thanks!
