### ISSUE TITLE
App will not connect to my Gmail account

### ISSUE THREAD

**Issue by mhelvens** [jberkel/sms-backup-plus#627]
I recently got a new phone. SMS Backup+ has worked well on my Galaxy S4 for years. My new phone is the FreePhone 2. It's a dual-sim phone running Android 5.1.

I'd like to restore the texts and call logs from my previous phone to my new phone. I tap "Connect", then select my Google account. But nothing happens. The check-box does not get checked, but I don't get an error message either.

Let me know if I should provide more information.

**Comment by jberkel** [comment]
Hm, this is tricky to debug if there aren't any error messages. If you have root on your phone you might be able to read the logs to see if any thing gets flagged there.

**Comment by mhelvens** [comment]
Hi there. Sorry for ignoring this issue for so long. (I never got a notification of your reply.)

This was a bug in the Fairphone operating system, related to application access control. Nothing wrong on your end. It has since been resolved.

Thanks for the app!

**Comment by jberkel** [comment]
cool, good to hear!
