### ISSUE TITLE
Java. Security.cert.CertPathValidationException:

### ISSUE THREAD

**Issue by tbcatga** [jberkel/sms-backup-plus#633]
Trust anchor for certification not found.

Was working fine stopped few days ago with this error.
Nexus 6p stock 6.0.1 unlocked/rooted
![screenshot_20160327-222636](https://cloud.githubusercontent.com/assets/18107569/14069767/1d7936a4-f46c-11e5-8cfd-9cbc98482ce2.png)

**Comment by jberkel** [comment]
is this with gmail or custom IMAP?

**Comment by tbcatga** [comment]
This is gmail.

**Comment by tbcatga** [comment]
Since discovered that this happens/won't work when using wifi at work. They must have some policy that is blocking. 
Thanks
