### ISSUE TITLE
I am unable to backup using Wifi

### ISSUE THREAD

**Issue by wesweav** [jberkel/sms-backup-plus#634]
Every time I try to backup using Wifi I get an error stating "Error during backup/restore: Cannot connect to host"  Is there a router port I need to open to allow SMS Backup+ to backup over Wifi?  Everything works fine over mobile data?  Thank for the help!

**Comment by primaleph** [comment]
This appears to be the same issue as https://github.com/jberkel/sms-backup-plus/issues/451 .

Maybe post a log file in there, since that's been a known issue for a while but no one ever posted their log.

**Comment by jberkel** [comment]
duplicate (#451)
