### ISSUE TITLE
Handling of prefix

### ISSUE THREAD

**Issue by fencer** [jberkel/sms-backup-plus#637]
In a scenario where I have dialled a number without the country code (eg 21123456) and few minutes later I dial the same number using the country code (eg +356 21123456), SMS backup + will not back them up in the same thread but split them up in different threads on gmail. I believe these should be in the same thread since they are the same number.

![sms-backup](https://cloud.githubusercontent.com/assets/620966/14586043/245cc7ea-048b-11e6-8aac-76e1b11b70ac.jpg)

**Comment by jberkel** [comment]
Yes.. and no. there are two different numbers. If you have one contact for several numbers it should thread ok.
