### ISSUE TITLE
Move build system to gradle

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#638]
From an email:

> I have been looking into to your code sms backup plus it is very nice one request is to make it as a gradle project so that it can be easy to import and there are instructions on how to import the code.It could be great if u can share gradle project with all the dependencies added so that we can import it into Android studio .

Current blockers are maven-style apklib dependencies (pay-me).

**Comment by streeter** [comment]
This might help: http://gradle.org/migrating-a-maven-build-to-gradle/

**Comment by jberkel** [comment]
@streeter I'm familiar with gradle, the main problem is that gradle does not support apklibs, so that will have to be addressed first (by changing the dependency / converting it to .aar)

**Comment by jberkel** [comment]
done w/ 536fb09d240f76466ce733d30eac1228f9316391
