### ISSUE TITLE
Strange ip address in gmail security recent activity 

### ISSUE THREAD

**Issue by Adri1027** [jberkel/sms-backup-plus#640]
I found an ip address under gmail security recent activity that I don't recognize but seems it might be linked to your app 184.151.114.7. Is this the case?

**Comment by Adri1027** [comment]
Note even after changing my password the same ip appeared but with .117 at the end.

**Comment by jberkel** [comment]
Maybe your mobile phone's provider IP?

https://whois.arin.net/rest/nets;q=184.151.114.7?showDetails=true&showARIN=false&showNonArinTopLevelNet=false&ext=netref2

```
Bell Canada BELLCANADA-20 (NET-184-144-0-0-1) 184.144.0.0 - 184.151.255.255
Bell Mobility, Inc. BEL4-12-01067-20120809-CA (NET-184-151-112-0-1) 184.151.112.0 - 184.151.115.255
```

**Comment by Adri1027** [comment]
Could it be? My own ip address begins with 64. Sorry, I don't know too much about this stuff.

**Comment by Adri1027** [comment]
Sigh, Checked again today and now it shows other IP addresses 184.151.114.225(Bell mobility)  and 174.94.119.66 (this is on a Chrome Browser with Authorized Application (959061759285-uqnem9qtjr97856o7b6pkuek0ref5dnd.apps.googleusercontent.com

**Comment by Adri1027** [comment]
The string after authorized application is related to your app

**Comment by jberkel** [comment]
Well, if you want to be extra cautious I'd recommend to change your password and revoke access to everything you don't need / don't recognize. SMS Backup+ uses Android's own security / account log in mechanism and should therefore be reasonably safe.
