### ISSUE TITLE
Automatische Sicherung nur kurze Zeit 

### ISSUE THREAD

**Issue by jbarg60** [jberkel/sms-backup-plus#642]
Obwohl sich das Programm auf dem Telefon und nicht auf der sd Karte befindet und auch die app batterie Optimierung deaktiviert ist funktioniert nur die manuelle Sicherung, bzw. die automatische nur kurzfristig bei google. Ich habe ein samsung galaxy s5 neo.

**Comment by jberkel** [comment]
Dup: #572
