### ISSUE TITLE
Error during backup/restore

### ISSUE THREAD

**Issue by jrogado** [jberkel/sms-backup-plus#645]
Hi,

I keep getting this error with SMS Backup + version 1.5.10 after backing up about 670 SMS to my gmail account:
Command: SELECT "Call log", response #6#
[NO, [NONEXISTANT], Unknown Mailbox: Call log (failure)]

The weird thing is that this error started after backing up about 670 SMS to the corresponding SMS IMAP folder. I tried creating another empty SMS folder in my GMAIL inbox, but the error persists.

Once it started, the error persists with two different Android versions: Jelly Bean 4.3 and Marshmallow 6..0.1. which made suspect some problem related to the gmail inbox. But I can't figure what, since I changed nothing and I didn't set a limit to the number of messages in an IMAP folder.

Any help appreciated!

**Comment by RobinWillis** [comment]
I am getting this same error message.  Have you figured out how to fix it?

**Comment by RobinWillis** [comment]
This helped me:  https://github.com/jberkel/sms-backup-plus#i-get-the-one-of-following-errors-during-backuprestore-command-select-sms-response-6-no-unknown-mailbox-sms-failure-or-response-6-no-nonexistent-unknown-mailbox-sms-failure

**Comment by Woi** [comment]
I think this can be close: There is a documented solution and the initial reporter hasn't reported back.
