### ISSUE TITLE
Online access

### ISSUE THREAD

**Issue by turizhere** [jberkel/sms-backup-plus#650]
Is there a way to look at my sms backup online and edit?

**Comment by ghstridr** [comment]
Look in the folders you set the app to backup to.

**Comment by ghstridr** [comment]
Look in the folders you set the app to backup to.

**Comment by turizhere** [comment]
on my phone?

On Sun, Jun 12, 2016 at 10:01 PM, ghstridr <notifications@github.com> wrote:

> Look in the folders you set the app to backup to.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jberkel/sms-backup-plus/issues/650#issuecomment-225480435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASs_VjBpAPsifoP2XmJIma0EsrDrgapNks5qLMgJgaJpZM4IorRP>
> .
>



-- 
Keturah Franchell
Co-Owner
EnviroMinded Coatings, LLC
1327 La Mirada Ct.
Winter Springs, FL 32708
Phone: 321-282-5200
Fax: 877-892-2606

**Comment by dannybones** [comment]
On your email.  Here's how it works for me.
On main screen, it says "connected as xxxxxx@gmail.com"
In that gmail account, I found that 2 folders had been created.  One called "Call Log".  You can see who you talked to, if incoming or outgoing, and length.
There was also a label called "SMS".  In some cases messages I sent to a person were in separate thread than ones received, and in others, they were all in the same thread.  I do not know how you would edit, though.

**Comment by Woi** [comment]
I think this can be closed: It's answered and reporter haven't come back for quite a while

**Comment by turizhere** [comment]
Yeah you can close it, I couldnt figure out how to view the sms logs so i
wouldnt have t restore all 16000 or so after multiple backups so i stopped
using the app.
Thanks anyways
