### ISSUE TITLE
Filter out selected sender numbers in SMS backup

### ISSUE THREAD

**Issue by kibeb** [jberkel/sms-backup-plus#657]
I'd like to be able to create a list of numbers SMS Backup+ would not backup messages from.

Why?

More and more companies send SMS messages to deliver one-time passwords and some of them choose not to use flash SMS (I don't know why), so the sensitive info stores with other regular SMSes. SMS Backup+ then relays them into user's Gmail, so the confidence that only authorized user who is in possession of the SIM card can log-in is broken.

I'm aware that we can set SMS Backup+ to only backup messages from a specific group, but it could be very hard to maintain a group of all senders minus the few that pose the security risk. Plus the attacker who already cracked into user's Gmail can modify such Google Contacts Group to contain the number he's interested in without user's knowledge.

I know two factor authentication enabled on user's Google Account would mitigate this scenario to some extent, but then there are apps that can access user's Gmail and someone can crack into these etc. If we could prevent this sensitive info to ever reach Gmail, it would be a huge plus, IMHO. 
TIA -- and thank you for such a wonderful app.

**Comment by wilsoc5** [comment]
You can always spin up a linux vm on your computer with postfix and dovecot to backup to. That way it never leaves your local network.  See: https://help.ubuntu.com/community/MailServer

Just go into Advanced Settings and change the IMAP server settings with the ip address of your linux vm (in bridged networking mode). If your VM's behind your host NAT, the forward ports X and Y to the VM's 143 or 993 and update the imap settings to use ports X or Y.

Then again, your local computer could be hacked too. Alas. There's always some risk.

**Comment by kurahaupo** [comment]
re-reading the description of this issue, it's about backup up SMS rather than call logs.

Which means this is (yet another) duplicate of #254 and #984.

Closing this ticket, please send follow up on #984.
