### ISSUE TITLE
no calllog restore on Android Marshmallow

### ISSUE THREAD

**Issue by computersalat** [jberkel/sms-backup-plus#658]
backup and restore of SMS and calllog works on LP (5.1.1), but on Marshmallow only SMS are restored...the calllog keeps empty ... no error is shown.

**Comment by hapishyguy** [comment]
Same issue here... Ita march 2017 now... Any news or any fix.

**Comment by hapishyguy** [comment]
Download the old version from the link below and install it. Unislnstall the current version first. It should fix the problem. It has worked me. 
https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.9-BETA5

**Comment by computersalat** [comment]
obsolete
