### ISSUE TITLE
Call Logs Not Backing Up - Auto or Manual

### ISSUE THREAD

**Issue by duke69111** [jberkel/sms-backup-plus#662]
I've got the LG G5 on Marshmallow and the app backs up sms and mms just fine; however the call log doesn't backup correctly.  It picked a date to stop working and no longer backs up call logs.  Before it stopped, it would back up sporadically.  

I've got a screen recording of what its doing if you want to see it.  I've also enabled my log with the debugging info if you want that as well.

Thanks.

**Comment by kurahaupo** [comment]
@duke69111 are you still having trouble with backing up your call log?

If so, then yes please, debug logs would be very helpful.

**Comment by duke69111** [comment]
I no longer have the LG G5.  It was a horrible phone.  I'm positive it was the phone and probably not the app.  It works fine on my LG G6.
