### ISSUE TITLE
Auto backup issue (MI UI / Marshmallow)

### ISSUE THREAD

**Issue by P4ulo78** [jberkel/sms-backup-plus#664]
Hi 
I've recently changed to a xiaomi MI Max rooted on marshmallow and noticed that auto backup is not triggering, although it works if I do a manual sync. 
I've  added the app to auto start and configured doze so it does not hibernate bit it never auto syncs (configured to sync the fastest way possible) 

Any ideas? 
Tks
PL

**Comment by simplyQQ** [comment]
I have the same issue on Sony Z5 Compact. It used to work but since one of the updates no longer does.

**Comment by sdickinson** [comment]
Looks like I'm having the same issue on 3 different phones (mine, and my two childrens phones). They are running Lollipop and I am running Marshmallow. Seems to be a recent issue

**Comment by jmakovicka** [comment]
I guess the Alarms class needs to use android.app.job.JobScheduler for Lollipop and newer.

**Comment by kundusandeepan** [comment]
I have similar issue in OnePlus one. Backup doesn't always trigger in schedule sequence, however manual trigger does work. Also it sometime shows last backed up 3 or 4 days ago. I am usually connected to wifi and in work and home. And I have configured it to backup on wifi.

**Comment by P4ulo78** [comment]
Hi,

Just wanted to update that i seem to have fixed my issue:
I was also getting the same problem on 2 new smartphones (Xiaomis: mi6 + note 4)  but with nougat version. 
What i did to fix was accessing the recent/running apps (navigation buttons as in Recent - Home - Back), pull down and lock the app so that it keeps running all the time. The running app will show a LOCK icon.
The app is auto backing up sms calls and adding them to calendar.

Hope this helps someone
PL

**Comment by jberkel** [comment]
Closing as duplicate (#572)
