### ISSUE TITLE
AT&T Advancedo Messaging 

### ISSUE THREAD

**Issue by DrTwister** [jberkel/sms-backup-plus#665]
With the release of the recent android update on AT&T, a new advanced messaging feature has been introduced that allows att customers to track opens and real time texting.  However these messages are not recognizedoing by backup+ and are skipped.

**Comment by Woi** [comment]
Are you referring to [Rich Communication Services](https://en.wikipedia.org/wiki/Rich_Communication_Services)? As far as I know this is not supported and @jberkel has no plans to support it. I added documentation for this circumstances and crated a pull request:
https://github.com/jberkel/sms-backup-plus/pull/844/commits/349af0b913797e36ceb065852d31eeeaf8215128
