### ISSUE TITLE
Restoring problem

### ISSUE THREAD

**Issue by jagannathams18** [jberkel/sms-backup-plus#666]
Hi Please help me in this,
While restoring my conversations, sent and received messages  are restoring in different threads for the same number. Example if we had a conversation like me: how are u: recipient: fine, both restored  different thread not in same conversation. Please help on this.

**Comment by jagannathams18** [comment]
someone guide me please

**Comment by kurahaupo** [comment]
@jagannathams18 are you still finding that sent and received messages are filed in separate conversations?

There have been several releases of SMS Backup+ since you filed this report; please upgrade if you have not already done so.

**Comment by kurahaupo** [comment]
no response, closing issue
