### ISSUE TITLE
Quit working entirely [SELECT "SMS"; response: #6# [NO [NONEXISTENT]]

### ISSUE THREAD

**Issue by missmorte** [jberkel/sms-backup-plus#667]
I have used this app for years and only had one previous issue. My problem now is that it quit working on my Samsung Galaxy S5 despite having worked on that very phone for the last year. I only recently noticed things weren't backing up when I needed to find an important text. All previously backed up information is gone and both call log and SMS Folders empty. 

I get Error during backup/restore: Command: SELECT "SMS"; response: #6# [NO [NONEXISTENT], Unknown Mailbox: SMS (failure)

I tried googling for a fix and have tried all of the following: 
- Verified my gmail had IMAP enabled
- Verified my labels had IMAP enabled
- Verified the call log and SMS labels were there and both spelt and capitalized properly
- Uninstalled SMS Backup+ and reinstalled it

**Comment by jcrben** [comment]
@missmorte could you try out the latest beta 1.5.11? If that doesn't work, could you provide the log as discussed in https://github.com/jberkel/sms-backup-plus#faq-general-file-bug-report?

**Comment by mcmahonsport** [comment]
Ah!

My apologies, it is now working, I had disabled IMAP for SMS and have now reneabled and it works fine.

Thank you for this great piece of software, it has helped me out many times.
