### ISSUE TITLE
Didn't backup SMS - DELETED them! 

### ISSUE THREAD

**Issue by aknight121** [jberkel/sms-backup-plus#674]
I did a back-up because I need my text messages from one individual for court this week. The most important time frame is from May-present. Not only did the app fail to back-up any SMS from this person, but it deleted them all from this contact! I had them all backed up through my Samsung account, but it can't be restored because data is missing. I absolutely have to get these messages back! The only thing I have are the MMS. I don't know what happened or why. I have the Samsung Galaxy S7 edge using the current version of the app. 1.5.10 I believe.

**Comment by jberkel** [comment]
The app never deletes anything. Not sure what happened there.

**Comment by aknight121** [comment]
This was 1.5yrs ago, so I'm sure the data is long gone by now! I was hoping
to recover some. But I can assure you, it most definitely did delete most
sms messages, and left me primarily with mms.

**Comment by jberkel** [comment]
I'm sorry that you lost data, but I really don't understand how the backup process (which only reads, and never writes) could have deleted your messages. This is the first report of such behaviour.

I'm closing this issue now.
