### ISSUE TITLE
Source for k9

### ISSUE THREAD

**Issue by axet** [jberkel/sms-backup-plus#678]
Hello!

I'm trying to find source for the k9 component:

```xml
          <dependency>
            <!-- https://github.com/jberkel/k-9/tree/sms-backup-plus -->
            <groupId>com.fsck.k9.mail</groupId>
            <artifactId>lib</artifactId>
            <type>aar</type>
            <version>0.0.1.f2ef921</version>
        </dependency>
```

Do you know where I can find source exactly for this version?

**Comment by jberkel** [comment]
As it says in the comment above, https://github.com/jberkel/k-9/tree/sms-backup-plus
 
The version number contains the sha, so the above "0.0.1.f2ef921" translates to https://github.com/jberkel/k-9/commit/f2ef921
