### ISSUE TITLE
SocketTimeOut with dovecot IMAP server

### ISSUE THREAD

**Issue by llebegue** [jberkel/sms-backup-plus#680]
Hi
SMSBackup+ version : 1.5.10
Repository : F-Droid

When I try to save or restore SMS on my IMAP server (TLS enabled with a Let'sEncrypt certificate on port 993) the process is stuck on identification.
## Log on SMSBackup+ :

29-09 20:03 Sauvegarde demandée (manuel)
29-09 20:03 Démarrage de la sauvegarde (MANUAL)
29-09 20:03 Sauvegarde en cours (25 SMS, 1 MMS, 4 appels)
29-09 20:03 Utiliser la configuration BackupConfig{imap=BackupImapStore{uri=imap+tls://PLAIN:XXXXXXXXXXXXXXXXXXXX@mail.xxxxxxxx.org:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
29-09 20:04 Erreur générale : Unable to connect (exception: com.fsck.k9.mail.MessagingException: Unable to connect, underlying=java.net.SocketTimeoutException)
29-09 20:04 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=com.fsck.k9.mail.MessagingException: Unable to connect, state =ERROR}
29-09 20:04 Sauvegarde effectuée

And then on the server side
## Log on IMAP server :

Sep 29 20:04:58 server_1 dovecot: imap-login: Disconnected (no auth attempts in 60 secs): user=<>, rip=176.183.xxx.xxx, lip=94.23.xxx.xxx, TLS handshaking: Disconnected, session=<XKPUUKk9ngCwt4kS>

**Comment by jberkel** [comment]
Can you try again with the latest beta? (from https://github.com/jberkel/sms-backup-plus/releases)

**Comment by llebegue** [comment]
Hi
The problem is still there.

This time the local sms_backup_plus.log is empty


On IMAP server : 
Nov  8 19:14:27 dovecot: imap-login: Disconnected (no auth attempts in 60 secs): user=<>, rip=176.xx.xx.xx, lip=94.xx.xx.xx, TLS handshaking: Disconnected, session=<0rVpHM5AWgCwt2p5>

**Comment by jberkel** [comment]
There are some newer betas you can try, but it looks like a normal network problem

**Comment by llebegue** [comment]
Thanks I'll try one

**Comment by kurahaupo** [comment]
@llebegue Is this still a problem for you?

If it is still a problem, some things to consider.
As jberkel mentioned, this was probably a network issue, as both ends see the other as having disappeared.
Does this happen when you're connected via WiFi, or UMTS (mobile data), or both?
Do you have any kind of "firewall" installed on your phone?
Is it rooted?

**Comment by llebegue** [comment]
It looks OK with the latest version downloaded from Google store.
Thanks
PS : I made a donation ;-)

**Comment by kurahaupo** [comment]
Thankyou!
