### ISSUE TITLE
Beta updates not pushing to phone

### ISSUE THREAD

**Issue by graymoment** [jberkel/sms-backup-plus#697]
I have been part of the beta for some time. I recently purchased a Pixel XL from the Google store. The beta version of this app does not push to the phone and it is not listed in my "beta" tab in the Play app store. Any ideas how I can trigger this? I thought about manually downloading the APK from here, but not sure if that will be seen as a different approach and consequently not get future beta releases pushed to my phone.

**Comment by jberkel** [comment]
I've neglected the beta channel a bit, just added an update there, should show up soon.

**Comment by graymoment** [comment]
Perfect. Thanks. Is there a preferred method to the beta channel?

**Comment by jberkel** [comment]
i've updated the instructions: https://github.com/jberkel/sms-backup-plus#beta.
please reopen if you have trouble getting it installed.
