### ISSUE TITLE
Backup not triggered with incoming/outgoing calls

### ISSUE THREAD

**Issue by therealacademic** [jberkel/sms-backup-plus#701]
Hello,
I'm currently testing the latest beta version of SMS Backup Plus and remarked something that may appears as a small bug. First of all, I installed SMS Backup Plus on my Google Pixel XL Smartphone running Nougat 7.1.1. I've, I think, correctly set up SMS Backup Plus as when I send or receive an SMS, the backup is triggered automatically within the time I setup in the software. This is not the case with a phone call (outgoing/incoming call).

Any idea of what I maybe missed or is it a bug ?

Thx for your feedback and also thank you for the work made with this awesome application!

**Comment by jberkel** [comment]
This is possible in the latest [beta](https://github.com/jberkel/sms-backup-plus/#beta)

**Comment by jcrben** [comment]
Please try out the beta and let us know if it's still an issue https://github.com/jberkel/sms-backup-plus#beta
