### ISSUE TITLE
problem with chronology SMS/MMS in Gmail

### ISSUE THREAD

**Issue by guiyome78** [jberkel/sms-backup-plus#705]
Hello,

First of all, please excuse my english, it is talked by a french user :)

I have many hundreds messages with some contacts and I note that Gmail create one thread for every 100 backed up messages (not a real problem for me)
But I see that MMS don't appear in the right order of the conversation thread : they are apparently at the end of it.
Maybe due to the fact that MMS are backed up after SMS (?)

I have found 3 closed issues that describe problems which look the same of mine, but they are old, so...
#58 
#102
#509 

Is it a known problem ? Do you have a solution to tell me ?

my phone : Samsung Galaxy A5 2016
my Android version : 6.0.1

Thanks for reading

**Comment by jberkel** [comment]
This is gmail related, sorry!

https://github.com/jberkel/sms-backup-plus/#faq-backup-gmail-100
