### ISSUE TITLE
access sms message received during restore?

### ISSUE THREAD

**Issue by dingodebs** [jberkel/sms-backup-plus#707]
I am wondering if someone can help me to access messages received during an sms restore operation. I know that at least one, and possibly more sms message was received by my phone when using the SMS restore operation on my phone, and whiles SMS Backup+ was the default messaging handler. I currently can't see or read this message. Is there a way to access messages received during the restore operation (and while SMS Backup+ is the default messaging handler) or are these messages lost forever?
Thanks!

**Comment by nbali** [comment]
bump

**Comment by jberkel** [comment]
This is fixed in the beta, see #851
