### ISSUE TITLE
Restore IO Error

### ISSUE THREAD

**Issue by ragnardannes66** [jberkel/sms-backup-plus#710]
Successfully backed everything up, did a factory reset stock marshmallow (Dec 2016)

App will still backup any new messages I get/send, but if I try to restore it just says calculating and then goes to an IO Error

My first thought was that I have too many messages. I went into restore settings and set it to just 100 messages and still having the same issue.

**Comment by tmfa** [comment]
I am having the same issue.  I can back up all SMS and MMS.  When I try to restore, I get an I/O error.  Changing the number of texts to restore makes no difference.

**Comment by taps007** [comment]
Yes I have exactly the same issue on my Pixel (7.1.1)

**Comment by parker5635** [comment]
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by LittleTimmyHartwell** [comment]
Same problem. LG TP450, Android 7

**Comment by jberkel** [comment]
Duplicate of #675
