### ISSUE TITLE
No items to sync: last item date is in future time.

### ISSUE THREAD

**Issue by mm16467** [jberkel/sms-backup-plus#714]
after receiving bad sms that has date and time pointing some times in future, May because of bad date settings in sender phone, app sync them but next time compare to bad last time of synced items there is no new items!

**Comment by mm16467** [comment]
oh I have found issue
I have a scheduled message for 6 month later to be sent, so app use that date as last synced date and therefore there is nothing to be synced.

I have set last synced date to now and change the IMAP label, then I have started the sync and then I see one message form some one conversation, after checking that I have found a message that scheduled for the future.

**Comment by jberkel** [comment]
looks like this is resolved? closing.

**Comment by haroldong8** [comment]
help, ive the same problem, except i don't know how to implement mm16467's solution. how do you set the last synced date to now, and change the IMAP label? my future date due to a rogue sms is 2221!
