### ISSUE TITLE
MMS not backing up correctly [RCS]

### ISSUE THREAD

**Issue by tdinetta7** [jberkel/sms-backup-plus#725]
It seems that MMS messages are not always backed up.  
<br>
Device Details: Using a Pixel XL, with project Fi.
Message Details:  Its an MMS group chat, there are extremely long messages in the group chat. 
<br>
I uninstalled and reinstalled the app.  Did a force backup and still the messages in that chat did not backup.

**Comment by bheusinkveld** [comment]
+1  I have this issue as well.  Most of all my MMS messages are not being calculated for backups and they aren't backed up.  They are MMS group chats too, with long conversation history.  I had in MMS settings, "send messages as group conversations by default" enabled.  

Device Details:  Samsung Galaxy S6, Model SM-G920T
Android version:  7.0

**Comment by Woi** [comment]
Maybe this is an explanation: https://github.com/jberkel/sms-backup-plus/issues/665#issuecomment-368053785

**Comment by jberkel** [comment]
RCS not supported, closing
