### ISSUE TITLE
SMS Restore NOT working.

### ISSUE THREAD

**Issue by nafeasonto** [jberkel/sms-backup-plus#738]
This is VERY imporant that I restore these texts messages from GMAIL.  It could mean by livelyhood.  The restore keeps giving an I/O error, the Backup works fine.

I am running your latest release on this page.

I am useing a Galaxy S6 with XtroLite Firmware.  Also XPOSED.  Is something interfering?  Is an an adblocker?  What oculd be causing this?

**Comment by parker5635** [comment]
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by LittleTimmyHartwell** [comment]
There is No Support for this App.

**Comment by jberkel** [comment]
Duplicate of #675
