### ISSUE TITLE
Enhancement request: backup to CRM

### ISSUE THREAD

**Issue by kranix0** [jberkel/sms-backup-plus#739]
SMS Backup + has served me well for several years! Thanks for your dedication!

I like to store my important e-mails in a CRM system. To do this (many CRM systems support this), I can BCC a special address to have the message go into the CRM.

It would be great if my SMS messages and call logs could also be stored in the CRM, so that I have a more complete record of my communications with a person.

**Comment by leggewie** [comment]
does the CRM support IMAP?

**Comment by kranix0** [comment]
I've since switched to a CRM that does support IMAP, so my SMS Backup Plus messages automatically show up.

A lot of CRMs don't support IMAP and instead need you to send e-mail directly to them. The way people work with these is to BCC messages to the CRM.

**Comment by jberkel** [comment]
@kranix0 Can this be closed then?

**Comment by kranix0** [comment]
If there's no demand from anyone else, I suppose it can be closed. Thanks.
