### ISSUE TITLE
Lost info

### ISSUE THREAD

**Issue by tkriley17** [jberkel/sms-backup-plus#745]
Switch from a Galaxy Note 4 to a Motorola Moto Z Droid play and somehow lost messages in the process. I have version SMS backup+ 1.5.10. Went from 135000 and something to 9000 and something

**Comment by jberkel** [comment]
Are they all present in gmail?

**Comment by jberkel** [comment]
ok, not sure why they would disappear from gmail. emails never get deleted by the app. sometimes gmail changes the threading so the message/thread count goes down.

**Comment by tkriley17** [comment]
Ya I lost about 80000 messages somehow

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jcrben** [comment]
Sorry to hear about that. 

It sounds like they may never have been backed up into Gmail in the first place.

**Comment by tkriley17** [comment]
My messages was there January and then they were gone. Then they were there up until 6 months ago and now they're gone again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
