### ISSUE TITLE
Displayed and charged donation values are highly inconsistent

### ISSUE THREAD

**Issue by rutsky** [jberkel/sms-backup-plus#750]
For small donation application displayed value something like "46 RUB", but actual donation was for "1.49 USD" (which is about 83 RUB nowadays).

SMS Backup Plus need to display either in currency that will be charged (e.g. in USD in my case), or charge in currency that is being displayed (e.g. in RUB in my case).

Also I don't see donation option anymore, is it possible to do another donation?

**Comment by jberkel** [comment]
Thanks, I'll check, maybe the rates don't auto-adjust. The donation option disappears once you have donated, it's not possible to donate again.

**Comment by jberkel** [comment]
The rates don't adjust automatically and thus were stuck in 2014. 

Now they should reflect the current exchange values:

1.29€ (RUB 109.00, USD 1.49) / 4€ (RUB 339.00, USD 4.99) / 7.90€ (RUB 690.00, USD 9.99)
