### ISSUE TITLE
Not able to complete backup on Redmi

### ISSUE THREAD

**Issue by vaibhavjain1000** [jberkel/sms-backup-plus#752]
The app is not able to make complete backup of sms on redmi phones, it just backup person to person sms and not other sms. Also, it doesn't auto backup in redmi devices, you have to manually update every time

**Comment by cd-rom** [comment]
You can check out the following Step:
Security->Permissions->Other Permission->SMS Backup+->Service SMS(check) (read orther sms)
Security->Battery->App battery saver->SMS Backup+->No restrictions (run automatically)
After the step,press the Backup button may not backup all the sms,Press the Reset button on the upper right corner menu then you can re-backup all the sms

**Comment by jberkel** [comment]
Closing as duplicate (#572)
