### ISSUE TITLE
My entire SMS data is in SMS Backup+ cloud, can it be deleted if we revoke the permission to our Gmail accounts?

### ISSUE THREAD

**Issue by VenkateshSegu** [jberkel/sms-backup-plus#753]
After backup of my SMS data it will store in SMS Backup+ cloud, is it possible to delete my SMS data from SMS Backup+ cloud? If so how can it be done?

**Comment by ferdnyc** [comment]
SMS Backup+ doesn't use a cloud store, it sends/receives the SMS content directly from your phone into your GMail mailbox on your behalf. (Or a mail account on some other email server, if you configure it to use a different one.) The only two copies of the data that exist are the original on your phone, and the backup stored in your email, both of which you control access to.

You can see in the source code file [mail/BackupImapStore.java](https://github.com/jberkel/sms-backup-plus/blob/master/src/main/java/com/zegoggles/smssync/mail/BackupImapStore.java) that SMS Backup+ relies on a Java library called K9 Mail, which it uses to communicate with the email server where its data is stored. In [preferences/ServerPreferences](https://github.com/jberkel/sms-backup-plus/blob/master/src/main/java/com/zegoggles/smssync/preferences/ServerPreferences.java) the default server address is set to Google's mail server:
```java
    static class Defaults {
        /**
         * Default value for {@link ServerPreferences#SERVER_ADDRESS}.
         */
        public static final String SERVER_ADDRESS = "imap.gmail.com:993";
```

The app connects **directly** to that email server, and sends/receives the backup data in the form of email messages. The data doesn't pass through any sort of cloud provider (except to the extent that GMail is a "cloud provider", but still it's _your_ cloud account, not any sort of "SMS Backup+ cloud").

So, if you want to remove your backed-up data, simply delete the email messages that SMS Backup+ places in your email account. If you want to prevent the app from accessing your account, revoke the authorization as described [in the FAQ](https://github.com/jberkel/sms-backup-plus#how-can-i-revoke-the-apps-access-to-my-gmail-account). But that authorization only allows _your phone_ to access _your_ GMail account, no access is granted to any third parties as part of using SMS Backup+.

(Disclaimer: I'm not affiliated with the the app or its author, @jberkel. I'm just a user who's been using SMS Backup+ happily for 4+ years, and in that time it's greatly eased the pain of two device upgrades, and several more Android factory-resets on those devices. And I can read Java code well enough to be reasonably confident that the app is doing just what it says it's doing, and isn't spiriting all of my text messages and phone call history off for some nefarious purpose.)

**Comment by jberkel** [comment]
@ferdnyc thanks for your explanations!

**Comment by Woi** [comment]
Can this issue be closed then?
