### ISSUE TITLE
SMS Backup cannot access GMail

### ISSUE THREAD

**Issue by AtomicFlamingo** [jberkel/sms-backup-plus#762]
Configured GMail to enable IMAP.  Downloaded SMS Backup.
Checked on time and time zone.
Opened SMS Backup. 
When I click on "connect to GMail" and then select the account, it says "Could not get token from system."  It offers a browser authentication method which is then denied.
Now what?

**Comment by jberkel** [comment]
Browser auth ticket: #767

**Comment by jberkel** [comment]
@AtomicFlamingo was the app installed via F-Droid (or some other 3rd party store)?

**Comment by AtomicFlamingo** [comment]
No, just plain old downloaded, via Apple store, I think.

**Comment by jberkel** [comment]
Hm ok. Not sure why the authentication failed in your case. I'd need a debug log or similar. In any case the browser authentication has been fixed and will be released as part of 1.5.11.

**Comment by jcrben** [comment]
Please let us know if the 15.11 fix doesn't work for you https://github.com/jberkel/sms-backup-plus#beta

**Comment by jberkel** [comment]
@mrspete can you try disabling Family Link to verify that this is the case?
