### ISSUE TITLE
Get SMS Backup+ back in official F-Droid repo

### ISSUE THREAD

**Issue by herbsmn** [jberkel/sms-backup-plus#763]
F-Droid is important. Getting free software Android apps into F-Droid is important. SMS Backup+ should be in F-Droid again. What are the blockers?

https://gitlab.com/fdroid/fdroiddata/issues/772

**Comment by jberkel** [comment]
I have no idea.

**Comment by herbsmn** [comment]
I know you are on the other thread too @jberkel but in case others are following this thread and not the other, here's what the F-Droid person said about this issue: "It was automatically moved to the archive, since it had a MD5 signature, which is no longer valid.  See fdroidserver#323 for more info.  The easiest way to reenable it is to update it to a version newer than 1554, if one exists.  Otherwise, disable the most recent build, which will delete it, then re-enable it.  It'll get built again and signed with a fresh signature."

**Comment by jberkel** [comment]
I'll push a minor update soon which should resolve this issue

**Comment by herbsmn** [comment]
thank you for doing this. i greatly appreciate it.

**Comment by jberkel** [comment]
sorry took a bit longer, but 1.5.11-beta4 is now available in f-droid:

https://f-droid.org/packages/com.zegoggles.smssync/

**Comment by herbsmn** [comment]
i really appeciate your work to get this fixed @jberkel! keep up the great work!

**Comment by Kelvino9** [comment]
Can we please have the latest Betas on F-Droid too? It's still on Beta4 instead of Beta7. Thank you and a Happy New Year!

**Comment by jberkel** [comment]
@Kelvino9 I've submitted a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/2734) a while ago but it hasn't been merged yet.

**Comment by Kelvino9** [comment]
Thanks @jberkel !
Been giving SMS Backup+ a fair try since my yearlong  backup tool SMS Backup & Restore got acquired a second time by another company. Since you incorporated IMAP and restore options SMS Backup+ is a perfect replacement for me. Nice to have it back on F-Droid

**Comment by jberkel** [comment]
@Kelvino9 oh, i'll check. the f-droid build process is a bit bumpy.
