### ISSUE TITLE
CallLog Sync to Calendar not working

### ISSUE THREAD

**Issue by MysticMagican** [jberkel/sms-backup-plus#764]
Since the last months no scheduled backup of calls and sync to google calendar.
If I do a manual backup, all missed items since last backup are submitted and visible in calendar.

Almost all settings should be at their default values.

The scheduled backup always says, that there are no items to backup (according to log)

Removed app, cache cleared and reinstalled (1.5.9): no change.

**Comment by MysticMagican** [comment]
Just to know :
I've joined the beta, installed the update and it seems to work since that point.

**Comment by MysticMagican** [comment]
I revoking my last post - no sync since 07.07. 08:26
Every Log entry looks like this:

> 19-07 10:19 Sicherung angefordert (regulär)
> 19-07 10:19 Sicherung übersprungen, keine Verbindung
> 19-07 10:19 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=REGULAR, exception=com.zegoggles.smssync.service.exception.NoConnectionException, state =ERROR}
> 19-07 10:19 Sicherung fertiggestellt
> 19-07 10:19 Nächste Sicherung geplant für: 10:49

If I hit "manual Sync", it looks like:

> 19-07 10:40 Sicherung angefordert (manuell)
19-07 10:40 Starte Sicherung (MANUAL)
19-07 10:40 Sichere (4 SMS, 0 MMS, 5 call log)
19-07 10:40 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
19-07 10:40 need to perform xoauth2 token refresh
19-07 10:41 token refreshed, retrying
19-07 10:41 Sichere (4 SMS, 0 MMS, 5 call log)
19-07 10:41 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=1, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
19-07 10:41 BackupState{currentSyncedItems=9, itemsToSync=9, backupType=MANUAL, exception=null, state =FINISHED_BACKUP}
19-07 10:41 Sicherung fertiggestellt
> 

and all items are synced correctly.

Would be nice to receive some feedback...

**Comment by MagicFab** [comment]
Working fine for me using CalDAV (not Google Calendar).

**Comment by MysticMagican** [comment]
New update, great. Oh, just new app icon... 
Is there a chance to get any help or suggest what the perineum might be, @jberkel?

**Comment by kurahaupo** [comment]
Does this problem still exist in the most recent version of SMS Backup? (There have been some updates to SMS Backup since this issue was raised.)

**Comment by kurahaupo** [comment]
no response, closing issue
