### ISSUE TITLE
Call Log Not Restoring to Note 5 (Visible in Gmail)

### ISSUE THREAD

**Issue by Ganny61** [jberkel/sms-backup-plus#771]
I'm trying to restore my call log (which is backed up to Gmail) to my new phone, a Samsung Note 5.  I was able to restore my SMS messages to my new Note 5, but the call log is not restoring.  I tried restoring only call logs without also restoring SMS messages at the same time, and that did not work.  Any suggestions would be appreciated.

**Comment by jcrben** [comment]
Seems to be a duplicate of https://github.com/jberkel/sms-backup-plus/issues/754

Please double-check that restore call log enabled in the restore settings.
