### ISSUE TITLE
No label found on Gmail- no messages backed up

### ISSUE THREAD

**Issue by lille3lsa** [jberkel/sms-backup-plus#772]
I did the intital back up( I was already connected to my gmail account ) but when i was checking my gmail..  only the call log was backed up on my gmail .. I dont see my  SMS anywhere  I already clicked on " manage labels" and there is no such thing as SMS or SMS+.  I did not have the IMAP enabled when I was doing the backup I dont know if that played any role on not having the SMS label created and not getting my messages stored...  I enabled the IMAP and tried to do it again but it says  the back up was already done .. it doesnt let me do another one.. and  i already refresh my gmail a so many times and logged out and logged in and still there is no SMS label..  HELP

**Comment by jberkel** [comment]
you can reset the backup state:

https://github.com/jberkel/sms-backup-plus/#how-can-i-make-the-app-think-that-it-has-to-do-the-backup-again

the redo the backup.

**Comment by jcrben** [comment]
@lille3lsa let us know if reseting does not work for you - we can reopen this if so
