### ISSUE TITLE
MMS pictures not backing up

### ISSUE THREAD

**Issue by JR1DUDE** [jberkel/sms-backup-plus#793]
Hi- I am using Message+ on a LG3 on Verizon- texts do get backup (gmail) but not pictures.
I was using the regular Message applicaiton and pics were backed up no problem but I had to start using Message+ and since then pics do not get back up. Thanks for your help!

**Comment by baltas01** [comment]
UNSUBSCRIBE PLS


Com os melhores cumprimentos.

João Baltazar

pt.linkedin.com/in/joaobaltazar/
www.facebook.com/jlpbaltazar
Skype: *baltazar.joao*

2017-09-12 4:15 GMT+01:00 JR1DUDE <notifications@github.com>:

**Comment by Woi** [comment]
Maybe this helps: https://github.com/jberkel/sms-backup-plus/issues/665#issuecomment-368053785

**Comment by jcrben** [comment]
Looks like this should be closed by https://github.com/jberkel/sms-backup-plus/commit/349af0b913797e36ceb065852d31eeeaf8215128 @jberkel 

If you want some help triaging issues, I might be able to tag them or ask questions and whatnot

**Comment by jberkel** [comment]
@jcrben yes that would be great, thanks. do you need project permissions for that?

**Comment by kurahaupo** [comment]
@JR1DUDE are you still having this problem?

If so, do you have "advanced messaging" _aka_ "RCS" turned on?

**Comment by kurahaupo** [comment]
no response, closing issue
