### ISSUE TITLE
Is there an alternative method to restore MMS from Gmail account?

### ISSUE THREAD

**Issue by nathan323** [jberkel/sms-backup-plus#806]
I find without this feature supported, It makes restoration of long, MMS-heavy conversations useless.

I can see all of the MMS messages on the Gmail account - is there another app/program/method to getting them onto a messaging app? Perhaps someone knows of an Android messaging app that supports restore from Gmail, I would consider changing from Android Messages to something else so I can restore these conversations..

**Comment by jberkel** [comment]
I don't think there is, sorry!
