### ISSUE TITLE
Messages not showing after restore on Pixel 2

### ISSUE THREAD

**Issue by sirdodger** [jberkel/sms-backup-plus#825]
My restore procedure seemed to work fine.  I made SMS Backup+ my default SMS app, it counted through the messages, and then restored Messages as my default SMS app.  However, no old messages are displayed.  There is only a shimmering gray placeholder, as if they are attempting to load but failing.  New messages are displayed just fine.

Restoring again is quick, and only a few new messages are processed, but again, none of the restored messages are visible after the restore.

I am running Android 8.0.0, Messages 2.5.212 and SMS Backup+ 1.5.10.

**Comment by seemoritz** [comment]
Seems to be the same on my OnePlus 5t which also runs Android 8.0.0
I did a backup on my old phone and a restore on the new one, but the messages are not displayed.
I also tried Slight Backup and the behaviour is the same - maybe the fault lies with the Messages app?

**Comment by sirdodger** [comment]
Approximately three months after I imported the messages, I launched Messages to text someone, and it got very slow and my phone crashed.  When I booted it again, all my messages were there.

So apparently it just takes a really long time to import and index all those new messages, which doesn't seem like SMSBackup's fault.
