### ISSUE TITLE
Only restoring my sent SMS not the ones I recieved

### ISSUE THREAD

**Issue by Blue1173** [jberkel/sms-backup-plus#826]
Backed up Note 3 thru SMS+, restored to Note 4 thru SMS+, all the threads are there but only my side of the conversation is showing (what I send, not what I received). Any ideas? 

I tried moving most texts to a different folder in Google, still only my texts show up.

ver 1.5.11

**Comment by jberkel** [comment]
Do you use Google Voice/Hangouts to send messages? (#516)

**Comment by kurahaupo** [comment]
no response, closing issue
