### ISSUE TITLE
Error: Cannot connect to host 

### ISSUE THREAD

**Issue by zenihama** [jberkel/sms-backup-plus#829]
This app has been working great for me for a long while, thank you for developing it. 
However recently automatic backups no longer work for me and when I try to do a manual backup I get the connection error. 
Here are the details, thanks in advance :)

Google Nexus 5X, Android 8.0.0
App version 1.5.10 (I have tried uninstalling and reinstalling it)
IMAP is enabled in Gmail

Logfile info:
27-11 22:53 Backup requested (manual)
27-11 22:53 Starting backup (MANUAL)
27-11 22:53 Backing up (449 SMS, 59 MMS, 151 call log)
27-11 22:53 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
27-11 22:54 General error: Cannot connect to host (exception: com.fsck.k9.mail.MessagingException: Cannot connect to host, underlying=java.net.SocketTimeoutException: failed to connect to imap.gmail.com/108.177.97.108 (port 993) from /192.168.0.12 (port 49448) after 30000ms)
27-11 22:54 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=com.fsck.k9.mail.MessagingException: Cannot connect to host, state =ERROR}
27-11 22:54 Backup finished

**Comment by netstu** [comment]
this is a laji app

**Comment by jberkel** [comment]
Closing as dup.
