### ISSUE TITLE
[auto backup] NOT FUNCTIONING PROPERLY 

### ISSUE THREAD

**Issue by ladybug8299** [jberkel/sms-backup-plus#837]
The auto backup isn't working, it's not backing up MMS and roughly half of SMS. It's been doing it for awhile and I thought it would work itself out, but no such luck. I'd hate to have to find a new SMS Backup app cuz this one was working great until recently.

**Comment by androidbug18** [comment]
I'm having same issue, great network signal and all but it's only backing up some of the sms! Using beta version on note 5.

**Comment by jcrben** [comment]
@ladybug8299 this app is free so the maintainer isn't making money, which probably reduces their motivation to fix - have you donated?  😄

**Comment by ladybug8299** [comment]
I would if I wasn't on a limited fixed income, but I was mostly reporting
the malfunction so whoever was aware of it. 😁

Tabitha Tetrick

**Comment by jcrben** [comment]
What version are you actually running? That's important for a bug report. Also need your Android version, any logs you can get, etc...

**Comment by ladybug8299** [comment]
App version 1.5.10

Android version 7.1.1

I've included screenshots of the logs I have.

Tabitha Tetrick

**Comment by ladybug8299** [comment]
Screenshots of logs continued.

Tabitha Tetrick

On Mar 13, 2018 10:24 PM, "Ben Creasy" <notifications@github.com> wrote:

What version are you actually running? That's important for a bug report.
Also need your Android version, any logs you can get, etc...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jberkel/sms-backup-plus/issues/837#issuecomment-372908522>,
or mute the thread

**Comment by jcrben** [comment]
I don't see any screenshots, but I don't think that's necessary. 15.10 is pretty much known broken at this point - you can install 15.11 from f-droid https://f-droid.org/packages/com.zegoggles.smssync/

Do you know how to install from f-droid? Maybe we should add instructions on that to the readme (@jberkel )

**Comment by ladybug8299** [comment]
The screenshots were attachments and ok. Thank you! I'll download it from
f-droid.

Tabitha Tetrick

**Comment by jcrben** [comment]
Seems like Github does not attach attachments from emails.

**Comment by jcrben** [comment]
@ladybug8299 we'd appreciate a report back if this fixes things for you

**Comment by ladybug8299** [comment]
It seems to have fixed things. Thank you very much!

Tabitha Tetrick

**Comment by jberkel** [comment]
@ladybug8299 you're welcome, thanks for letting us know. closing this issue now.
