### ISSUE TITLE
SMS MMS Call Log not backing up on LG G6

### ISSUE THREAD

**Issue by jmarfey** [jberkel/sms-backup-plus#838]
Used sms backup on my old phone and worked great, very happy. Installed SMS backup on my new LG G6 and all appears the same but does not back up. Status reads 'last back up Dec 4' (my last backup before upgrading my phone). When I initiate backup it recognizes there are new items to back up then counts down the list of item numbers very quickly (seconds) but without displaying the progress bar indicating upload to gmail. When finished status reads done 'there are no items to back up'. Yet nothing appears in my gmail sms folder since Dec 4 backup from my old phone. Have tried reinstalling the app but keeps doing the same. Phone is LG G6, android version 7.0, SMS Backup version 1.5.10 set with 'XOAuth' for gmail authentication. Hoping you can help solve this problem. Thanks in advance. Johan

**Comment by jberkel** [comment]
Can you try the beta? 
https://github.com/jberkel/sms-backup-plus#beta-testing

**Comment by infectiousintegrity** [comment]
I have the beta and an LG Aristo with android 7.0 I have a few specific contacts, they seem to be all verizon customers that this simply does NOT backup incoming messages from.  I have been messing with this for over 3 months, tried uninstalling rooting and reinstalling and about every single other sms backup tool out there, I need this for court and its critical

**Comment by jmarfey** [comment]
Hi Jan,
Thank you so much.
Is the github link below to the beta? Anything I need to know before tryng
it?
Thanks,
Johan

**Comment by kurahaupo** [comment]
@jmarfey did the beta fix the problem for you?

Does this problem still exist in the most recent version of SMS Backup? (There have been more updates to SMS Backup since 1.5β.)

**Comment by infectiousintegrity** [comment]
This is the only SMS backup app I have ever successfully trusted but the
phone I could not ever get it to work on was an LG aristo. Rooting the
phone & beta didn't help at all---,I needed it for a custody battle,in
which the phone itself was physically stolen from my car right.before.court
so I cant even attempt to help problem solve now...sorry....I've never had
a problem with any other phone

..yet...I'm just getting ready to download it to my Samsung Note 9....but
it worked flawlessly with both my cheapo galaxy J-series phones.

**Comment by kurahaupo** [comment]
Ooof, I'm sorry about the theft and the court battle; each of those would be difficult to deal with on its own, but together, oh dang.

It seems like you're no longer using the LG Aristo so I'm going to close this ticket for now, but feel free to re-open it if you're still having trouble with that phone (or with any other).

**Comment by infectiousintegrity** [comment]
I am so sorry,I was unaware it was still open....the court battle ended
well actually,thanks in part to the fact that I had your app that enabled
me to obtain,in court approval format ALL of the other communication
between my daughters father & myself.  It proved a pattern of control and
intimidation as well as a disregard for communication and a refusal to
cooperate for  our daughters best interest...

So I owe you a very long overdue thank you!
