### ISSUE TITLE
Does not Backup SMS of Signal App

### ISSUE THREAD

**Issue by p3k** [jberkel/sms-backup-plus#841]
I am using [Signal](https://github.com/signalapp/Signal-Android) as my default SMS application. 

After the first backup with SMS Backup+ I noticed only 25 of the approx. billions of billions of billions messages on the phone were stored on my IMAP server.

In fact, these 25 are coming from the pre-installed system app to handle text messages.

What could I possibly do to remedy this behaviour?

**Comment by jasonab** [comment]
There are lots (and lots) of issues related to this in the Signal repo. Signal stores its messages in its own database on your phone, different from the default SMS location. There are many people requesting the ability to back it up, either in Signal or by putting the messages in the default location, but that hasn't happened yet.

**Comment by p3k** [comment]
Oh, I see. Thanks for the hint, was not aware of this at all.

**Comment by jberkel** [comment]
@jasonab thanks for the info. for later reference,  signalapp/Signal-Android#6012, signalapp/Signal-Android#339

**Comment by jasonab** [comment]
I'd also mention signalapp/Signal-Android#5729 as that actually mentions the Android SMS store
