### ISSUE TITLE
backups are not run according to schedule

### ISSUE THREAD

**Issue by mtross** [jberkel/sms-backup-plus#845]
version 1.5.10   LG G5 
regular schedule is 30 minutes incoming 3 minutes, yet the latest entry in my gmail is two days old.
When I hit the backup (now) button it works
Martin

**Comment by lth2h** [comment]
I've been having this problem too.  My last backup was Feb 22.  The log claims there's no connectivity.  However at least for the three times it tried today, I sure I have a connection around those times as I was definitely using the phone.  Running it manually seems to work just fine. I have SMS Backup+ 1.5.10 on a Samsung Galaxy S8 with Android 7.1.1.

**Comment by jberkel** [comment]
@mtross @lth2h please give the current [beta](github.com/jberkel/sms-backup-plus#beta) a try, it should work much better

**Comment by jberkel** [comment]
closing as dup (#572)
