### ISSUE TITLE
[Backup] Stalls when phone is turned off

### ISSUE THREAD

**Issue by IMeanReallyNow** [jberkel/sms-backup-plus#846]
I am finding that when the phone turns off for more than a few seconds, the app simply stalls. 

The items saves up to that point appear as expected. 

This is on a Note 4, connecting to Gmail. 

Any idea why this is happening? 

Thank you.

**Comment by jberkel** [comment]
By "phone turns off" you mean the screen turns off? Is this with power save mode activated?

**Comment by kurahaupo** [comment]
no response, closing issue
