### ISSUE TITLE
I should be able to view the log when i clicked on it.

### ISSUE THREAD

**Issue by darewealth** [jberkel/sms-backup-plus#847]
#### Expected behavior
I should be able to  view the log when i clicked on it.

#### Actual behavior
The view log showed a blank page with only ‘’OK’’ when clicked

#### How to reproduce

(1) Download[ sms backup +](https://play.google.com/store/apps/details?id=com.zegoggles.smssync) application

(2) Launch It and open the app

(3) clicked on the three dot at the top then clicked on view log   

Device used: Gionee P5 mini

Operating system: Android version 5.1

*App version: 1.5.10

#### Recording Of The Bug
https://youtu.be/ZwHFT_Y5ZKg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@darewealth/bug-report-on-sms-backup-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jberkel** [comment]
thanks,  this is already fixed in the current beta version

**Comment by jcrben** [comment]
Please try out the beta and open a new issue if it doesn't work https://github.com/jberkel/sms-backup-plus#beta

**Comment by jcrben** [comment]
@jberkel I could leave these open with that new "awaiting response" label like https://github.com/jberkel/sms-backup-plus/issues/809 - up to you. follow-up by bug submitters is probably unreliable.

I'm trying to triage the issues in https://github.com/jberkel/sms-backup-plus/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.5.11 so there can be a release.
