### ISSUE TITLE
SMS to calendar 

### ISSUE THREAD

**Issue by sdfg2** [jberkel/sms-backup-plus#848]
Hello, 

Any plans on allowing us to save SMS to calendar?

**Comment by jberkel** [comment]
Can you explain a bit more what you're after?

**Comment by jcrben** [comment]
I'm guessing they would like the Google Calender to show call logs? Seems out of scope to me. 

https://github.com/jberkel/sms-backup-plus#faq-general-can-you-add-feature-x

Closing for now - @sdfg2 feel free to respond.

**Comment by onvz** [comment]
> 
> 
> I'm guessing they would like the Google Calender to show call logs? Seems out of scope to me.
> 
> https://github.com/jberkel/sms-backup-plus#faq-general-can-you-add-feature-x
> 
> Closing for now - @sdfg2 feel free to respond.

I think what he meant is: I hope to write short text messages into the Google calendar, and the second is not call logs.

**Comment by sdfg2** [comment]
Sorry, I don't know how I missed this.

What I mean is that when an SMS comes in it creates a new entry in a calendar of choice on the phone.  So the backend is agnostic - I can use caldav, google, whatever for the calendar provider.
