### ISSUE TITLE
sms-backup logo-icon proposal

### ISSUE THREAD

**Issue by ahmeterbay** [jberkel/sms-backup-plus#852]
hi..
sometimes i design logo on utopian.io and i saw your open source project application..
ı wanted desıgn a logo for your app..
ı thınk u wıll lıke it.
plss check ıt and feedback me-like or not :))
https://steemit.com/utopian-io/@ahmeterbay/sms-backup-logo-icon-proposal

**Comment by jberkel** [comment]
@ahmeterbay thanks for your proposal! I'm actually quite happy with the current logo and don't plan to change it at the moment.

**Comment by ahmeterbay** [comment]
ok @jberkel 
good luck wıth your project :))

**Comment by jcrben** [comment]
@ahmeterbay thanks for the offer! if you're OK with the response feel free to close the issue - otherwise we'll get around to closing it eventually

**Comment by ahmeterbay** [comment]
ohh ok..srry for forget it :)
