### ISSUE TITLE
Call Log not saved to Calendar since switch to Android 8

### ISSUE THREAD

**Issue by kranix0** [jberkel/sms-backup-plus#857]
On my old phone, a Samsung Galaxy S6 with Android 7 Nougat, my call log was saved to my Google Calendar. Since moving to a Google Pixel 2 with Android 8 Oreo, this has not been the case.

In fact I can no longer see the option in the settings -- did I miss something?

SMS and call logging to Gmail works fine.

**Comment by jberkel** [comment]
@kranix0 which version of SMS Backup+ do you use? If it's 1.5.10, please try out the beta:https://github.com/jberkel/sms-backup-plus/#beta

**Comment by kranix0** [comment]
Thanks for the reply, @jberkel. It's 1.5.10, the latest from the Play Store. I'll try the beta.

**Comment by kranix0** [comment]
OK I've updated to the beta. It looks nicer but I still don't see any options for saving to my calendar.

**Comment by jberkel** [comment]
![screenshot_1522269546](https://user-images.githubusercontent.com/18891/38055013-d86334f4-32d8-11e8-86a2-6dff2a0842a7.png)

**Comment by kranix0** [comment]
Yep, I have just found it. I'll continue to test. I'm still quite sure it wasn't there in the stable version.

**Comment by kranix0** [comment]
Great, I've got it to log my calls since yesterday afternoon. That still leaves the calls between December (when I changed phones) and yesterday. Is there a way to force it somehow?

**Comment by jberkel** [comment]
You could reset the backup state, but that will reset everything, SMS included, and might create duplicate entries.

This is actually a requested feature: #639

**Comment by kranix0** [comment]
Thanks for your help. I think it's working now. I've added my vote to #639.

**Comment by amkniazi** [comment]
May I have any Idea why is it so
![IMG_20240921_163810](https://github.com/user-attachments/assets/394d905f-cbbf-4325-b745-e8c9678fae6e)
