### ISSUE TITLE
Incompatible API use in your codes.

### ISSUE THREAD

**Issue by jay2013** [jberkel/sms-backup-plus#860]
We notice that you use API "<android.provider.CalendarContract$Calendars: android.net.Uri CONTENT_URI>" in method "<com.zegoggles.smssync.calendar.CalendarAccessorPost40: boolean enableSync(long)>" on line 35 not exist in SDK level [9, 10 , 11, 12, 13].  This may cause problems to your APP when it was run on these platforms. 

please help to check it. Thanks very much.

other similar bugs:
BUG: <android.provider.CalendarContract$Calendars: android.net.Uri CONTENT_URI> called in <com.zegoggles.smssync.calendar.CalendarAccessorPost40: java.util.Map getCalendars()> on line 72 not in [9, 10 , 11, 12, 13]

BUG: <android.provider.CalendarContract$Events: android.net.Uri CONTENT_URI> called in <com.zegoggles.smssync.calendar.CalendarAccessorPost40: boolean addEntry(long,java.util.Date,int,java.lang.String,java.lang.String)> on line 58 not in  [9, 10 , 11, 12, 13]

### Please specify the following:

* Android version  level [9,10,11,12,13]
* Phone model / brand any  devices
* SMS Backup+ version installed
* Messaging app

**Comment by jberkel** [comment]
That's why it's called CalendarAccessor**Post40**, duh.

**Comment by jay2013** [comment]
Sorry for disturbing you.
