### ISSUE TITLE
RESTORE ISSUEs - Please Help - only restores 2 sms out of thousands - Then only 4 year old sms

### ISSUE THREAD

**Issue by TheMattD** [jberkel/sms-backup-plus#868]
Hey guys, 
I have used the restore from SMS Backup+ before with success but it takes 2-5 days for large amounts (thousands) of sms.. but it did work in the past for me on my phone. Although I am now doing a restore for my dad's phone but am having a problem..  
 
I'm now having an issue restoring where it's only finding 2 messages instead of the thousands which are on the gmail account.. 
I looked through some old threads but am not finding my same situation or a solution so far. 

Any ideas would be appreciated, thanks in advance.  
  

Before you report your issue, please search the issues page to see if it has already been reported. Also, if you'd like, you can try out the [beta version](https://github.com/jberkel/sms-backup-plus#beta).

### Expected behavior
Restore messages from previous backups... 

### Actual behavior
Only finding 2 messages to restore, but I have thousands of sms in gmail.. 

### Steps to reproduce the behavior
I just took the normal steps to restore my sms as usual, open the app, made sure my gmail account is connected, click "restore" and follow the normal prompts. Shortly there after it shows only 2 messages were restored..?

-------------------------------------
### Please specify the following:

* Android version
6.0.1 

* Phone model / brand
Samsung Galaxy S5 from Verizon (SM-G900V)

* SMS Backup+ version installed
1.5.10 

* Messaging app
Message+ (Verizon's app)

**Comment by TheMattD** [comment]
**UPDATE----

I just installed the BETA version 1.5.11 and now it appears to be running as it should and restoring the thousands of SMS it normally would. 

Won't know till it's done but it appears to be fixed in the beta version. I'll update later when I know more.
Hope this helps others if they come across the same issue.

**Comment by TheMattD** [comment]
*BAD UPDATE* 
I thought the RESTORE was going well but it now appears it did not. It ran for a couple hours but stopped and said it was canceled. 
While running it showed 48890 SMS were being restored but stopped itself around 32000. I then checked what restored and mainly found messages from 2014 and no where near 32000. 
To make matters worse it seems they are nearly all duplicates. 
I can do another factory reset and try again if need be but I'd sure like to be sure it's going to work somehow. OR is there a way to salvage whatever I have going on? 
I'd also like to know if there is a way to delete duplicates? 
PLEASE, ANY suggestions / solutions would be great. Dad's already been without his phone 2 days so sooner the better obviously.

**Comment by jberkel** [comment]
Restoring many thousand SMS doesn't work so well. Maybe limit the number to the most recent 500? (see #586)

Otherwise see https://github.com/jberkel/sms-backup-plus/#im-not-able-to-restore-all-of-my-insert-huge-number-messages

**Comment by jberkel** [comment]
@TheMattD thanks for the feedback. the app holds a wakelock during the restore so normally keeping the device awake should not be necessary. but i think some versions of android are quite aggressive about saving battery and will deactivate the network when the screen is turned off. at least that's my guess.

**Comment by jcrben** [comment]
@TheMattD if this is resolved, please close it?

Seems like we should investigate the issue of this working when the call log restore box is unchecked tho

**Comment by jcrben** [comment]
:thumb
