### ISSUE TITLE
SMB Backup+ is inactive

### ISSUE THREAD

**Issue by fkbreitl** [jberkel/sms-backup-plus#899]
I noticed that SMS Backup+ does not backup automatically after switching from my Samsung S4 to S7.
When I open SMS Backup+ it says `idle` in green letters in the first line.
In the next line it shows the last backup time. When I click on the backup button a backup is done.
But it never happen automatically although automatic backups are activated.

I have already removed SMS Backup+ from battery optimization standby and made sure it is active.
However this doesn't seem to help.

* Android version: 7.0
* Phone model / brand: Samsung Galaxy S7
* SMS Backup+ version: 1.5.11
* Messaging app: default

**Comment by jberkel** [comment]
Can you send some log files please, with "extra debug information" enabled? see

https://github.com/jberkel/sms-backup-plus/#i-want-to-file-a-bug-report-what-should-i-do

**Comment by jenicbear** [comment]
Same issue, only mine says idle instead of inactive
Same phone same versions of both

**Comment by fkbreitl** [comment]
Sorry, mine says "idle", too in English. In German it says "Inaktiv". I will fix this in my previous post.

Here is my [sms_backup_plus.log](https://gist.github.com/fkbreitl/15d14f2ffa6bda02e74353cd0824bdc4#file-sms_backup_plus-log)

**Comment by immae** [comment]
Same issue here, I just discovered the hard way that automatic backups stopped in April 2018. Without configuration change on my part, so probably due to the SMSBackup+ upgrade.

Android 6.0.1 (Fairphone 2 Open OS)
Sms Backup+ version 1.5.11 from F-droid store
Default sms application
I’m using my own IMAP connection
Manual backups seem to work

**Comment by jenicbear** [comment]
I've since upgraded to Samsung S9 
So running Android 8.0 
Still auto update isn't working, have to use manual

**Comment by jcrben** [comment]
Perhaps try other messaging apps? 

I'm using Pulse SMS https://messenger.klinkerapps.com/ with LGv20 Android 7.0 with 1.5.11 and automatic backup works reliably.

**Comment by fkbreitl** [comment]
Unfortunately Pulse SMS does not backup SMS to email, but some others do.

**Comment by wpcprez** [comment]
I have the same issue with 2 devices that upgraded from S5 to S7 and Galaxy Tab A to S7. My phone that upgraded from S7 to S8+ works fine.

**Comment by andreaallred76** [comment]
What messaging apps work with your app if Pulse doesn’t?

**Comment by LegoChicken** [comment]
Automatic backup doesn't work on Moto G6 Andriod 8. Manual back works.

**Comment by wpcprez** [comment]
I think I figured this out. It's related to power saving. When I turn off power saving it works fine but if it's on this app stops working.

**Comment by wpcprez** [comment]
new or old scheduler didn't make a difference for me. The power saver mode on samsung phones was causing the issue.

**Comment by fkbreitl** [comment]
Meanwhile I have Android version 8.0 on my Samsung Galaxy S7, but I am still seeing "inaktiv" after turning power saver mode off and old scheduler on.
It does not work!

**Comment by wpcprez** [comment]
On the s7 make sure to set the app to unmonitored in the device maintenance / battery screen. It could be putting it to sleep

**Comment by wpcprez** [comment]
On 2 of my kids s7 devices I had to unmonitored and leave power save off and then it started to work automatically again. Ymmv

**Comment by kurahaupo** [comment]
Thanks everyone for the feedback.

Using the new Oreo JobScheduler API is on the roadmap.

I'm marking this as a duplicate of #758 just so we can track one issue and keep all the feedback in one place.
