### ISSUE TITLE
Backup stops before the end

### ISSUE THREAD

**Issue by ericongithub1** [jberkel/sms-backup-plus#905]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Please specify the following:

* Android version 5.1.1
* Phone model / brand Samsung Galaxy Note 4
* SMS Backup+ version installed 1.5.10
* Messaging app

**Comment by ericongithub1** [comment]
Works fine but seems to stop before the end (963/1012)
Thks

**Comment by kurahaupo** [comment]
no response, assuming issue was resolved by upgrading to 1.5.11.
