### ISSUE TITLE
Only Restoring Messages Sent Not Messages Received

### ISSUE THREAD

**Issue by GreenThang3** [jberkel/sms-backup-plus#906]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Please specify the following:

* Android version: 7.0
* Phone model / brand: Samsung-sm-G920A
* SMS Backup+ version installed: SMS Backup+ 1.5.11
* Messaging app: The original Samsung messaging app on my phone

**Comment by jcrben** [comment]
98% of received messages and 0% of sent messages? How did you calculate that?

I probably can't help debug this, but note the FAQ https://github.com/jberkel/sms-backup-plus#faq-backup-automatic-backup:
> When reporting a bug related to auto backup it is essential to attach a sync log file. See the relevant FAQ for more information on how to do this.

**Comment by kurahaupo** [comment]
No response, closing issue
