### ISSUE TITLE
Not working with andorid message

### ISSUE THREAD

**Issue by waqas-mehmood-pk** [jberkel/sms-backup-plus#907]
### Expected behaviour
Open app clicks on backup button start backing up all SMS irrespective of any SMS default app. 
I am using SMS application 
1. truecaller SMS 
2. Android messages

### Actual behaviour
Open app clicks on backup button start backing up just those messages which I sent or receive using truecaller SMS app, if I send or receive SMS using google andorid messages app, that's messages not backup.

### Steps to reproduce the behaviour
Set Android Messages as a default SMS app. Send and receive SMS using android Messages app and then start the backup.
Sometimes when I open the SMS backup+ app first tap on the backup button, button caption change with "stopping" and then I close and reopen app. then its working.

### Please specify the following:

* Android version:  7.1.2 N2G47H  [MIUI Global 9.5 | Stable 9.5.10.0 (NAMMIFD)]
* Phone model / brand: Redmi 4x / Xiaomi 
* SMS Backup+ version installed : 1.5.11
* Messaging app: Google Android Messages

**Comment by jcrben** [comment]
Thanks for the report! 

I probably can't help debug this, but note the FAQ https://github.com/jberkel/sms-backup-plus#faq-backup-automatic-backup:
> When reporting a bug related to auto backup it is essential to attach a sync log file. See the relevant FAQ for more information on how to do this.

**Comment by kurahaupo** [comment]
no response, closing issue
