### ISSUE TITLE
won't back up old phone

### ISSUE THREAD

**Issue by gred22** [jberkel/sms-backup-plus#913]
I wanted to do a backup of an old galaxy s4 before I get rid of it.  SMS-backup-plus connected to my gmail account, but said there was an XOAuth error.  But it said it did a backup of 1211 items, but nothing came through my gmail.  I downloaded and installed the 1.5.11 but it says there is nothing to back up.  How can I get my SMS, MMS, and call log to gmail?  Thanks

**Comment by kurahaupo** [comment]
@gred22 can you please confirm that you've checked the SMS folder within your email account, and either found or not found the messages you're expecting?

**Comment by kurahaupo** [comment]
no response, closing issue
