### ISSUE TITLE
Completes successfully on device, but nothing in Gmail account

### ISSUE THREAD

**Issue by putztzu** [jberkel/sms-backup-plus#914]
Similar to open issues
https://github.com/jberkel/sms-backup-plus/issues/913
https://github.com/jberkel/sms-backup-plus/issues/909

Also, what is this thing about requiring "email account with IMAP enabled?"
Am only using the Google Web Client on my PC.
If you're talking about settings for the Android gmail app on the device, there is no configuration for IMAP vs POP but the behavior suggests it's POP. In any case, shouldn't your app be configured to send to an SMTP server or are you really integrating with an IMAP mail client?
If this is the real problem (requires an IMAP email client), shouldn't your app error when it can't connect to the required email client?

### Expected behaviour
Backup SMS messages.

### Actual behaviour
When email accounts are checked after completed backup, no messages have been received in Gmail accounts. Have tested against 3 gmail accounts I own, The total messages number over 2200, but have limited to 200 messages in Advanced settings (attached log file is this setting). Interesting your FAQ says gmail limit may be only 100 messages but assume your 200 message setting should work.

### Steps to reproduce the behaviour
Installed latest SMS Backup Plus from Play Store. 
Run your app, pointing to my Gmail account(s)
No errors reported on device, Backups complete successfully without reporting any error

### Please specify the following:
* Android version
4.1.2
* Phone model / brand
Samsung Galaxy SCH-1415
* SMS Backup+ version installed
1.5.11
* Messaging app
Android messaging
Also installed 
MySMS
Google Messenger

Contents of file sms_backup_plus.log

08-04 18:53 Backup requested (manual)
08-04 18:53 Starting backup (MANUAL)
08-04 18:53 Backing up (200 SMS, 0 MMS, 0 call log)
08-04 18:53 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX@imap.gmail.com:993}, currentTry=0, maxItemsPerSync=200, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS]}
08-04 18:55 BackupState{currentSyncedItems=200, itemsToSync=200, backupType=MANUAL, exception=null, state=FINISHED_BACKUP}
08-04 18:55 Backup finished

**Comment by gred22** [comment]
I have the same problem - says it is backing up, goes through all the messages, says they are backed up, but nothing ever comes to gmail.  Changed to custom IMAP server, set to same gmail, but with password specified.  Know it connects to gmail because had to set gmail to allow "less secure apps" to connect..  But same result.

**Comment by selvanair** [comment]
In case you are looking in INBOX, SMS messages are backed up to a label named SMS and will skip the INBOX. The label name can be changed in advanced settings.

**Comment by kurahaupo** [comment]
@putztzu & @gred22 can you please confirm that you've checked the SMS folder within your email account, and either found or not found the messages you're expecting?

(The reason for using IMAP rather than SMTP is because it allows messages to be placed in a particular folder, rather than just in the INBOX.)

**Comment by kurahaupo** [comment]
no response, closing issue
