### ISSUE TITLE
Restore not completing - auto canceling

### ISSUE THREAD

**Issue by JohnAnemone** [jberkel/sms-backup-plus#916]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Please specify the following:

* Android version
* Phone model / brand
* SMS Backup+ version installed
* Messaging app

**Comment by JohnAnemone** [comment]
Just factory restored galaxy s7, trying to restore texts. Have over 69k texts but the most I have been able to restore in any single pass has been approx 10k program runs for a while then reports canceled. First I though phone was idling out and blanking screen, but even trying to keep screen / phone active it still auto cancels restore. Any suggestions?

**Comment by gasher101** [comment]
This is a problem for me to. I'm running a galaxy S nine and it backs up maybe two to three hundred and stops the  backup all by itself. I dont have "Touchdown" so is there a fix for this?

**Comment by kurahaupo** [comment]
@JohnAnemone  Thanks for letting us know.
I'll close this but mark it as "helpful" in case anyone else needs to know.

@gasher101 By far the most common cause for incomplete backups is server-side limitations. In general this type of problem will resolve itself as successive retries get further through the backlog. If that doesn't seem to match your issue, please feel free to open a new ticket with more details.

**Comment by kurahaupo** [comment]
(Specifically, many IMAP servers do *not* support multiple concurrent sessions to the same account, and each new connection bumps off any previous one.)
