### ISSUE TITLE
Authorization Error when Google Advanced Protection is enabled on GMail account.

### ISSUE THREAD

**Issue by tehbra1n** [jberkel/sms-backup-plus#917]
### Expected behaviour
Sign into Google and back up SMS/MMS.
### Actual behaviour
Authorization error message, cannot sign into Google to upload/download messages.
### Steps to reproduce the behaviour
Attempt to initiate backup, receive the error in the screenshot below.
### Please specify the following:

* Android version - 9.0.0
* Phone model / brand - Essential PH-1
* SMS Backup+ version installed - 1.5.11
* Messaging app - Google Messages
![screenshot_20180825-181736](https://user-images.githubusercontent.com/17303996/44623054-47057900-a893-11e8-8128-e8385e6fbcd5.png)
(Choose my GMail address)
![screenshot_20180825-145014](https://user-images.githubusercontent.com/17303996/44623013-77004c80-a892-11e8-984b-636b1f2ab115.png)

**Comment by kurahaupo** [comment]
Refer to #959.
