### ISSUE TITLE
"Sign in with Google temporarily disabled for this app"

### ISSUE THREAD

**Issue by jberkel** [jberkel/sms-backup-plus#941]
Recent [Google policy changes](https://developers.google.com/terms/api-services-user-data-policy#additional-requirements-for-specific-api-scopes)  only allow certain types of apps access to Gmail. From what I can gather, storing non-email content on Gmail is no longer allowed. I'm not sure if it's even worth applying for an exception. As a result of this, new authentication tokens won't be issued. I'm not sure what happens with already issued tokens.

![screenshot_1551376718](https://user-images.githubusercontent.com/18891/53587594-188e9080-3b8b-11e9-8577-c78c9da78250.png)

**Comment by oomotosho** [comment]
**Please what is the resolution?

I'm still experiencing the issue**

**Comment by kurahaupo** [comment]
@oomotosho Please follow [these instructions](https://github.com/jberkel/sms-backup-plus/issues/959#issuecomment-513018820) to configure IMAP rather than XOAUTH access to your Gmail account.

**Comment by kurahaupo** [comment]
PLEASE DO NOT FOLLOW UP OR REPLY TO THIS TICKET.

THIS ISSUE IS A DUPLICATE
of issues #934, #959 (and many others)
