### ISSUE TITLE
Android Q - "no default sms package set"

### ISSUE THREAD

**Issue by gotmikhail** [jberkel/sms-backup-plus#958]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Expected behaviour
Connected to you account, access granted to contacts, tapping "RESTORE" should be able to restore Call Logs & SMS. Instead, you get the small notification at the bottom saying "no default sms package set".

### Actual behaviour
Tapping "RESTORE" you get the small notification at the bottom saying "no default sms package set".

### Steps to reproduce the behaviour
Fresh install of SMS Backup+, when prompted to "Change SMS app?", say yes. Grant access to contacts and select correct google account.h In "Advanced Settings" -> "Restore settings", confirm "Restore SMS" is checked. Return to main SMS Backup + page and tap "RESTORE".

### Please specify the following:

* Android Q
* Pixel 2 XL
* SMS Backup+ version 1.5.11
* Default android "Messages" app

**Comment by jberkel** [comment]
@gotmikhail  Please try the new beta version (1.6.0-BETA1), from https://github.com/jberkel/sms-backup-plus/#beta

**Comment by gotmikhail** [comment]
@jberkel well overdue, but the update fixed it (as others have acknowledged) - I was out of commission for a couple months
