### ISSUE TITLE
Doesn't show up in my e-mails

### ISSUE THREAD

**Issue by arnauldb** [jberkel/sms-backup-plus#960]
Hello,

* LineageOS 15.1
* Asus Zenfone Max pro M1
* SMS Backup+ 1.5.11
* Silence

I have my own server at home.
My set up in the app:
imap.xxxx.xxxx.org:993
xxxx@xxxx.org
my imap passwd
TLS
(I also tried with and without 'Trust all certificates', I have a Let's encrypt certificate)

The app says the backup is successful but nothing shows up in my e-mails on my server.

Thank you for any suggestions.

**Comment by kurahaupo** [comment]
Have you checked for an `SMS` folder on your mail server?
if you want SMSes to appear as newly-arrived Email messages, under "Backup settings":
* set "Gmail label/IMAP folder" to `INBOX`
* set "Mark as read (emails)" to "Always mark as unread".

**Comment by kurahaupo** [comment]
Closing; please re-open ticket #960 if you need further assistance.

**Comment by arnauldb** [comment]
Hello, having been notified you closed this ticket, I gave sms-backup+ another try and this time it was successfull, thank you for this app. I opened a new ticket, [#1000](https://github.com/jberkel/sms-backup-plus/issues/1000) , regarding the sms app Silence which seems not to work well with sms-backup+.
