### ISSUE TITLE
Google Policy - 15.07.2019

### ISSUE THREAD

**Issue by Piotr1122** [jberkel/sms-backup-plus#961]
Hello

I just got an email from Google:

> Hey,
> Although you do not need to do anything, we wanted to let you know that the following apps may no longer have access to certain data in your Google account, including Gmail content. If these applications do not meet our updated data policy requirements by the deadline, you will lose access to your account on July 15, 2019.
> SMS Backup +

Is there anything to worry about? There is a chance for updates adapting the application to Google's policies or rather I have to look for an alternative?

**Comment by malversan** [comment]
This issue is already being discussed here:
https://github.com/jberkel/sms-backup-plus/issues/959

Please read before posting repeated issues.

**Comment by ner00** [comment]
This title is better though :)
