### ISSUE TITLE
Problem with getting wrong text messages

### ISSUE THREAD

**Issue by Mikeb124125** [jberkel/sms-backup-plus#962]
Hi There,

Currently having issues that I am getting wrong text messages from unintended people that are not showing up on my phone, however showing up in the SMS backup conversion. I have checked with my phone provider. There is no trace of this number on their records. Looks to be some kind of escort service. I traced there number and it said it was a landline. Furthermore, it shows when backed up a separate communication thread from sent to received messages. I am using a blackberry key 2.  If anyone can give me some insight on this that would be great.

Thanks

**Comment by malversan** [comment]
I am sorry to say it, but I really cannot see how receiving unwanted SMS messages from a scort service is related to the SMS Backup+ app.

You should better try an SMS app that can filter messages from people that is not in your contacts. A lot of SMS apps have that feature.

**Comment by kurahaupo** [comment]
@Mikeb124125 Does a Blackberry have some sort of "hide spam" feature? That might account for why you're seeing messages in Gmail that are not apparent on your phone.

**Comment by kurahaupo** [comment]
Closing. Please reopen ticket #962 if you need further assistance.

**Comment by kurahaupo** [comment]
PS: another possibility is that there is a second phone also saving messages into your account, and _it_ is the one receiving the SMS spam.
