### ISSUE TITLE
Permission is required: Access SMS Messages

### ISSUE THREAD

**Issue by boxorandyos** [jberkel/sms-backup-plus#965]
I have my Google Pixel XL running version QPP5.190530.014 and I just received a security update. After installing the update I got a notification that says Permission problem: the following permission is required: Access SMS Messages. 

I have allowed this app all permissions. 
It has always worked before this latest update. 

I always keep everything updated. 
I am running the very latest version of SMS Backup+ that it shows available in the play store version 1.5.11.
Android version 10, all updates installed. 
Stock Google Messaging app. 

-randall

**Comment by partounian** [comment]
Confirmed issue also affects Q DP5 for the Pixel 2 XL.

**Comment by krknopp** [comment]
And Pixel 3 on Android Q DP5.

**Comment by jaxidian** [comment]
In case it's useful info, I'm seeing the same behavior with TiBu (an older APK) on both a Pixel 3 and Pixel 3 XL. Worked fine on DP2 on both phones but not on DP3.

**Comment by kurahaupo** [comment]
Does it keep asking, or was that a one-off?

Google adjusts the Android permissions system from time to time, and newly created permissions are not automatically granted to any app, even if the user previously said "grant all".

**Comment by boxorandyos** [comment]
In my case the messages always displayed. 

Again speaking in my case I have checked a few times to make sure that all permissions are granted. So even if any new ones came along I would see that.

**Comment by kurahaupo** [comment]
This is possibly a duplicate of  #958.

There was a change to some permission handling in Android Q which required a patch to the app. 

Please try the new [beta version (1.6.0-BETA1)](https://github.com/jberkel/sms-backup-plus/#beta).

**Comment by boxorandyos** [comment]
Different error message received at a separate time than #958 but unknown if it was the same root cause. 

I can confirm that I just tried this for the first time since 1.6.0-BETA1 and this issue is now resolved and the app is working again.
