### ISSUE TITLE
Google ERROR

### ISSUE THREAD

**Issue by ccleven** [jberkel/sms-backup-plus#971]
Mine says:
sign in with Google temporarily disabled for this App.  The app has not been verified by Google in order to use google sing in

**Comment by Fuzzweed** [comment]
Yes, this too

**Comment by 3choBoomer** [comment]
Same

**Comment by Spinak627** [comment]
Same

**Comment by hughh** [comment]
Ditto

**Comment by hmhecht** [comment]
Same here. Mine says:

Login error XOAuth authorization error. Please maek sure you enabled IMAP in your Gmail account settings.

Note that I *do* have IMAP enabled and have since verified that.

Also, here's what's in my log:

"Authentication error: Command: null; response: #2# [NO, [AUTHENTICATIONFAILED],Invalid credentials (Failure)] (exception: com.fsck.k9.mail.store.imap.XOAuth2AuthenticationFailedException: Command: null; response: #2# [NO, [AUTHENTICATIONFAILED],Invalid credentials (Failure)]

**Comment by Trudgy** [comment]
Same issue. Anyone find an alternative to this app. Really need this working

**Comment by hughh** [comment]
I got it to work with Yahoo mail by generating a third-party app password (following [these instructions](https://help.yahoo.com/kb/new-mail-for-desktop/generate-third-party-passwords-sln15241.html), then in SMS Backup+, under _Advanced settings_, _Custom IMAP server_, using [these settings](https://help.yahoo.com/kb/new-mail-for-desktop/imap-server-settings-yahoo-mail-sln4075.html?impressions=true), specifically `imap.mail.yahoo.com:993` with my Yahoo _email address_, the third party app _password_ I generated, and TLS _Security_. Although I didn't try I it, I did wonder if generating a Google application-specific password would have worked also.

**Comment by MaKali42** [comment]
Having this problem as well. Super irritating especially after dealing with the automatic back-up no longer working/running for a couple months which has been requiring any back-ups to be done manually. I've relied on this app for years but might have to find a replacement at this rate. Anyone have comparable recommendation?

**Comment by hmhecht** [comment]
App-specific password for Google/Gmail/etc. did NOT work for me while 2-factor authentication is on. Anyone else have any luck with that?

**Comment by gasher101** [comment]
> Same here. Mine says:
> 
> Login error XOAuth authorization error. Please maek sure you enabled IMAP in your Gmail account settings.
> 
> Note that I _do_ have IMAP enabled and have since verified that.
> 
> Also, here's what's in my log:
> 
> "Authentication error: Command: null; response: #2# [NO, [AUTHENTICATIONFAILED],Invalid credentials (Failure)] (exception: com.fsck.k9.mail.store.imap.XOAuth2AuthenticationFailedException: Command: null; response: #2# [NO, [AUTHENTICATIONFAILED],Invalid credentials (Failure)]
> 
> Note also that I use 2-Factor Authentication, and can't/won't turn that off. So, I can't use the solution posted along with Issue #970 (#970)
> 
> Looking forward to getting a fix soon as I rely heavily on this app. Even willing to move to a paid version if that's what it takes!

Whats the paid version?

**Comment by hmhecht** [comment]
> Whats the paid version?
There isn't a paid version to my knowledge, but I want the developer to know that if he published one, I'd be willing to pay and/or subscribe as I do rely heavily on this functionality. Been really missing it the past week+!

**Comment by pizzamx** [comment]
Same for me, last successful signin was on Aug 8th.

**Comment by kurahaupo** [comment]
follow-ups to #959
