### ISSUE TITLE
Offline SMS backup to file (without Gmail or IMAP)

### ISSUE THREAD

**Issue by szpak** [jberkel/sms-backup-plus#979]
### Expected behaviour
I can just export SMS messages to a local file (json, sqlite, etc.), transfer it via a cable/wifi/whatever to computer and use to restore (on that or an another phone) if wanted/needed. All without Gmail or an IMAP server access.

### Actual behaviour
Looking through the FAQ I'm aware only about export to Gmail (I don't want to send my sms messages to the cloud) or my own IMAP (I would prefer not to have setup one).

### Steps to reproduce the behaviour
Try to backup and restore SMS message without internet access (and without IMAP server).

**Comment by szpak** [comment]
Duplicate of #974...

**Comment by pintspin** [comment]
I have already done that , here is the app ,  ( simply read all SMS and write it on a text file ) in external memory at the moment but functionality for internal is also there 

published app  Link here 
https://www.amazon.com/dp/B0891VGDXJ/ref=cm_sw_r_tw_dp_U_x_TBiZEb3AKC72G

Source code here 
https://github.com/pintspin/ReadSMS.git
