### ISSUE TITLE
Different app behavior using new authentication method

### ISSUE THREAD

**Issue by ekw** [jberkel/sms-backup-plus#982]
I switched over to the IMAP method and it's working, but it seems to behave a little differently than before.

So SMS Backup+ transfers my SMS messages to my gmail account and label them "SMS".  Nothing surprising here.

Before Google hamstrung the app, if I delete messages or label them as something else in my gmail account (remove the "SMS" label), SMS Backup+ would not re-transfer the SMS from my phone to gmail.  It would transfer only new messages.

With the new IMAP method, if I delete a message or label it as something else in my gmail account, SMS Backup+ will now re-transfer the SMS from my phone to gmail.  In other words, it will transfer new messages, but also any old messages that were deleted or re-labelled in gmail.

Is this expected when using this IMAP method?  I liked the old behavior because now I get duplicate of messages that I re-labelled in gmail and the messages that I deleted from gmail will keep coming back.

**Comment by teezeu** [comment]
my deleted do not come back

**Comment by ekw** [comment]
Never mind, when I started using the IMAP method, my phone started transferring all the SMS messages to gmail again (which is unfortunate but I understand). And it was still in the midst of syncing, so messages were still being transferred even as I was manipulating them on gmail and I got confused.
