### ISSUE TITLE
Offer to triage issues list

### ISSUE THREAD

**Issue by kurahaupo** [jberkel/sms-backup-plus#985]
Hi @jberkel 

I notice the issues list has grown rather rapidly, and perhaps is overwhelming for you.

Would you like to appoint some additional project participants who could triage issues, reply to users, and close duplicates, to reduce the clutter for you to deal with?

I offer my services, and I'm sure there are others who would help as well.

There is also a build-up of negative reviews on PlayStore from users who haven't understood the instructions; we might be able to help with that too.

**Comment by jberkel** [comment]
@kurahaupo yes, that would be great, thanks. I've just picked up work on the app again. first step is to upgrade dependencies, then I'll have a look at removing the broken features. and the documentation definitely needs to be updated.

**Comment by kurahaupo** [comment]
@jberkel 

Let me know (by email to martin@kurahaupo.gen.nz) if/when you add me as a contributor, and I'll start going through the issues and closing duplicates so that the list is more manageable.

Let me know what else you'd like me to work on.

I've submitted #981 to fix some of the documentation, if you want to check me writing style.

**Comment by jberkel** [comment]
@kurahaupo sorry, missed you reply, I've just added you

**Comment by kurahaupo** [comment]
Joined now...
