### ISSUE TITLE
Group SMS messages not backed up

### ISSUE THREAD

**Issue by gmills2822** [jberkel/sms-backup-plus#987]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Expected behaviour
Any SMS (group or individual) will be backed up; automatically or manually.

### Actual behaviour
Group SMS Messages don't seem to be getting backed up.  Caveat, I am using Textra as my texting App.

### Steps to reproduce the behaviour
Received a group SMS, noticed it wasn't backed up hours later.  Sent a reply to ensure there was a new message to be checked by SMS Backup+.  Immediately attempted backup.  SMS Backup+ Reported no messages to backup.  And received and sent messages were not in gmail under SMS Label.

### Please specify the following:

* Android 10 - Sec Patch 2019-10-06
* Google Pixel 2
* SMS Backup+ version installed: 1.5.11
* Textra 4.18

**Comment by nikkopt** [comment]
Group "sms's" are either MMS's or RCS messages. (Which are stored as mms's by this app). Do you have the option to backup mms's turned on? If so, be sure to look for the messages in seperate converations. I just tried with the stock google messages app and it works, even if every participant gets his own conversation instead of just one for all.

**Comment by gmills2822** [comment]
I do have MMS backup enabled.  Confirmed, it is working.  I was expecting all participants conversations to update when I send a group message and have all their separate conversations bubble up to the top.  Instead, it looks like the first person in the list is the only recipient and gets pulled up to the top, and only when the others respond do they get updated.  But even then, the only copy of the message I sent is in the conversation with the first person in the list.  I'll try sending one with Messages to see if that behaves differently than Textra.

So with Messages, I get a copy of the sent message as from me to me.  Yes it is backing up the messages.  I think it could be improved to show the entire group list in the subject, so that I know who I sent a group message to.  I realize that is more a feature, that I could attempt myself.  And might just give it a try.

**Comment by gmills2822** [comment]
Closing as it is confirmed working.

**Comment by gmills2822** [comment]
Shoot, hit comment by accident.
