### ISSUE TITLE
Remove requirement for having a label on Gmail Email

### ISSUE THREAD

**Issue by brhunt1958** [jberkel/sms-backup-plus#990]
Hello,

I would like to inquire about removing the requirement for having a label for the Gmail emails that are created from backing up SMS messages.

SMS Backup+ is creating the emails properly, but they do not appear in the Gmail Inbox.  Instead they show up under the label "SMS" which is what my SMS Backup+ client is set to.  

I uses a POP3 scraper to pull those emails out and move them to a more permanent home.  With the labels on (not in Gmail Inbox), the POP3 scraper does not see them.  If I remove the labels in Gmail, the emails "move" to the Inbox and are then picked up by the POP3 scraper.  

I can see why the label would be desirable for someone who lived in Gmail.  But for those who are using the Gmail account as a pass-through, it causes problems.

If the Gmail label field was optional, that would resolve my issue but still allow true Gmail users to add whatever label they might want.

Thanks.

Bryan Hunt

**Comment by nikkopt** [comment]
Why don't you just send the messages directly to where you want? You are not forced to use gmail, you can put whatever server you want in the imap configuration.

**Comment by brhunt1958** [comment]
Mike,

The scraper was already in place for other emails coming in, so seemed like it would be a simple add to pick up the additional messages.

Little did I know...

Thanks.

Bryan

**Comment by kurahaupo** [comment]
I would try setting the label to `INBOX` which is defined in [RFC 3501 §5.1](https://tools.ietf.org/html/rfc3501#section-5.1) as "the primary mailbox for this user on this server".

**Comment by brhunt1958** [comment]
My God, who knew that it would be that simple...

Actually I thought that I had tried that, but obviously not.

Thanks Martin, for that spot-on correct answer.
