### ISSUE TITLE
Can't backup From android 

### ISSUE THREAD

**Issue by heapxor** [jberkel/sms-backup-plus#991]
Hi, 
I am not Able To backup because tool says enable imap Which Is already enabled. During reathorization I'm getting error Sign in with Google temporarily disabled for this app. 

Can't find any workaround if there is any? 
* Android version 
9x
* Phone model / brand
S10
* SMS Backup+ version installed
Latest
* Messaging app
Android default

**Comment by nikkopt** [comment]
You are trying both the imap method and the "legacy" discontinued method which might not work anymore (i haven't tested it lately)?
Just stick with the imap method. If you have 2FA turned on on your google account, you will have to make an app specific password.
Which version are you using? 1.5.11 or the new beta unreleased one? I haven't tried that one yet so i'm not sure how the config process is.

**Comment by heapxor** [comment]
When I try to connect with my Gmail account I got error

Sign in with Google temporarily disabled for this app
This app has not yet been verified by Google in order to use Google Sign in.


I don't see any option to provide any login /pass

**Comment by heapxor** [comment]
Is there any update or app is not use able anymore?

**Comment by nikkopt** [comment]
The app is usable but like i said on my first reply, only by imap. You should not be using XOauth2.
Go to advance configurations/server settings and In authentication, change it to imap (these might have different names, i'm using the app in another language). Then enter your credentials in that same window. If you have 2FA enabled on your google account, you will have to make an app specific password and use it here.
The readme here on github is outdated.
Here is a better article explaining step by step: https://www.androidpolice.com/2019/08/12/sms-backup-is-now-broken-due-to-gmails-api-changes-but-theres-a-workaround/

**Comment by heapxor** [comment]
Okay works. Thanks
