### ISSUE TITLE
automatic backup error

### ISSUE THREAD

**Issue by Tali76** [jberkel/sms-backup-plus#992]
Hello,

My android version : 7.0NRD90M
My phone model : Xiaomi Redmi Note 4
SMS Backup+ version installed : 1.5.11

I managed to get around the Gmail authorization issue, allowing IMAP in GMAIL, allowing the use of less secure apps, and setting up the server manually in the SMS Bacup + application like this:

Authentication: Simple text
Server address: imap.gmal.com:993
Email address: my Gmail address
Password: my Gmail account password
Security: TLS
Trust all applications: checked

In addition I set the regular automatic backup on 30mn (number of max sms to save on 100), and the planning of incoming messages on 1mn

Regular automatic backup worked well, but the incoming backup did not work often ...
And lately I got the following error messages when opening the log:

Example of an error message:

29-10 16:30 Requested backup (regular)
29-10 16:30 Start backup (REGULAR)
29-10 16:30 Backup in progress (11 SMS, 2 MMs, 0 calls)
29-10 16:30 General error: unable to connect (exception: com.fsck.k9.mail.MessagingException: Unable to connect, underlying = java.net.UnknownHostException: Unable to resolve host "imap.gmail.com": No address associated with hostname).

Message incomprehensible to me sorry ... ????
Would someone have the answer?
Thank you.

**Comment by kurahaupo** [comment]
The last line of that error message contains the key:
* `Unable to resolve host "imap.gmail.com"`

This indicates a problem that's somewhere between your device and your ISP or phone service provider.

Normally such an error would be transient and will resolve itself, but if you'd like to trouble-shoot, start by checking whether you're connected by WiFi or using mobile data, as that will affect which DNS resolver your phone is connecting to. Try switching from one to the other and see if that helps.

If the problem only occurs when connected to your home WiFi, try rebooting your WiFi router, or try "flush DNS cache" if it has that feature.

**Comment by kurahaupo** [comment]
no response, closing issue
