### ISSUE TITLE
Only Old Version v1.5.11 (1576) on F-Droid and Play Store

### ISSUE THREAD

**Issue by MatthewGitter** [jberkel/sms-backup-plus#995]
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.
DONE

### Expected behaviour
App versions later than v1.5.11 (1576) available in F-Droid app/website and in Google Play Store. That version is from April 2018, but there's been lots of updates in the Github repo since then.

### Actual behaviour
Latest version of app in F-Droid app/website and in Google Play Store are v1.5.11 (1576) .

### Steps to reproduce the behaviour
- Visit [F-Droid app page](https://f-droid.org/en/packages/com.zegoggles.smssync/):
https://f-droid.org/en/packages/com.zegoggles.smssync/

- Visit [Google Play Store page](https://play.google.com/store/apps/details?id=com.zegoggles.smssync):
https://play.google.com/store/apps/details?id=com.zegoggles.smssync

### Please specify the following:

* Android version
10 (any)

* Phone model / brand
any

* SMS Backup+ version installed
That's the problem

* Messaging app
N/A

**Comment by bolbishvili** [comment]
1.5.11 is the latest version which is not marked BETA.

**Comment by jberkel** [comment]
Yes, there hasn't been a release since then. see [CHANGES](/jberkel/sms-backup-plus/blob/master/CHANGES)
