### ISSUE TITLE
No autobackup after work around

### ISSUE THREAD

**Issue by Hippchikk** [jberkel/sms-backup-plus#998]
I have applied the workaround for the google issue and was able to perform a manual back up. However, it is still not backing up automatically. I am including a screenshot of the log. It says Backup skipped, no connectivity and I get a NoConnectionException. I do not have the wifi option checked and I definitely had cell service so I am not sure what the problem is. I would appreciate any suggestions.

### Please specify the following:

* Android version 9
* Samsung Galaxy S8
* SMS Backup+ 1.5.1.1
* Messaging app: Google Messages
![Screenshot_20191214-194850_SMS Backup+](https://user-images.githubusercontent.com/58894775/70856463-be598480-1eab-11ea-862b-c9d67babdef6.jpg)

**Comment by kurahaupo** [comment]
Text in image reads:

### /storage/emuilated/0/Android/data/com.zego...
_(some text scrolled out of view)_
type=EVERYBODY}. backupType=INCOMING, debug=true, typesToBackup=[SMS,MMS,CALLLOG]}
12-14 10:20BackupState{currentSynedItems=3, itemsToSync=3, backupType=INCOMING, exception=null, state=FINISHED_BACKUP}
12-14 10:20 Bckup finished
12-14 18:26 Backup requested (incoming)
12-14 18:26 Backup skipped, no connectivity
12-14 18:26 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=INCOMING, exception=com.zegoggles.smssync.service.exception.NoConnnectionException, state=ERROR}
12-14 18:26 Backup finished

**Comment by kurahaupo** [comment]
This would appear to be a simple case of "connectivity loss".

Questions for research: Does this model of phone or OS version block internet access from background tasks?

@Hippchikk can you also check whether it makes any difference whether mobile data is disabled or wifi is disabled. (Typically, radio connections may be turned down or off to conserve power, and mobile data can be brought back up much more quickly than WiFi as long as the phone is still registered to a cell site.)

Also in your phone's settings, can you check the power optimisation settings and make sure it allows this app to run in the background? And that it's been granted all requested permissions?

**Comment by kurahaupo** [comment]
no response to follow-up questions
